Step3 지하철 구간 관리 기능 구현
next-step/atdd-subway-map pull request #1082
Opened 2024-01-30 04:17 UTC by samkimpepper

리뷰 잘 부탁드립니다!

2024-01-30 11:31 UTC, dbeod2 requested changes
안녕하세요. 3단계 미션 요구사항에 맞게 진행해주신 것 같아요 👏👏👏

생각해보면 좋을 것 같은 부분 코멘트 남겨두었습니다.
확인해보시고 수정 후 리뷰 요청 주세요 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

2024-01-30 11:31 UTC, dbeod2 commented on src/main/java/subway/exception/InvalidInputException.java
> +@Getter
@Getter를 추가하신 이유가 따로 있으신가요? 🧐

2024-01-30 11:31 UTC, dbeod2 commented on src/main/java/subway/exception/InvalidInputException.java
> +}
일반적으로 예외 클래스에서 필드를 선언하지 않고 상속받은 RuntimeException의 생성자를 호출하여 예외 객체를 생성할 수 있습니다.

아래와 같이 RuntimeException을 상속받은 예외 클래스를 만들 수 있습니다.
```suggestion
public class InvalidInputException extends RuntimeException {
    public InvalidInputException(String message) {
        super(message);
    }
}
```
여기서 RuntimeException의 생성자를 호출하여 예외 객체를 생성하면, 
부모 클래스에서 이미 예외 메시지를 처리하는 로직이 구현되어 있기 때문에 별도의 필드를 선언할 필요가 없는데요.

code와 message 필드를 추가해주신 이유가 더 많은 정보를 제공하기 위함인지 궁금합니다 🧐

2024-01-30 11:31 UTC, dbeod2 commented on src/main/java/subway/section/SectionService.java
> +public class SectionService {
SectionService가 필요한지 고민해보시면 좋을 것 같습니다.

구간 저장/삭제 시 Line 도메인 객체 내 CasecadeType를 사용해서 지정을 하셨기 때문에 저정/삭제를 따로 안해주셔도 됩니다.
JPA에서는 포함관계에 있다면 cascade옵션을 통해 같이 영속화 시킬 수 있기 때문입니다.

참고하실만한 [영속성 전이](https://hongchangsub.com/jpa-cascade-2/) 관련되서 URL 전달 드려볼께요~

2024-01-30 11:31 UTC, dbeod2 commented on src/main/java/subway/line/Line.java
> +    private List<Section> sections = new ArrayList<>();
Section 컬렉션에 대해서 일급컬렉션으로 리팩토링해보면 어떨까요?
컬렉션에 대한 비지니스 로직이 일급컬렉션으로 모여서 응집도를 높일 수 있어요.
아래글을 참고해보세요.

https://jojoldu.tistory.com/412

관련되서 참고해보시다 보면 로직들이 어디에 있어야 하는지 자연스럽게 알게 될 것 같아요 🙏🏻

2024-01-30 11:31 UTC, dbeod2 commented on src/main/java/subway/section/SectionController.java
> +public class SectionController {
구간은 노선과 종속관계라고 생각이 드는데요.
노선에 해당하는 구간을 등록/제거를 해주는 기능이라 lineController에 해당 API가 있어도 무방 할 것으로 보이는데 어떻게 생각하시나요~?

2024-01-30 11:31 UTC, dbeod2 commented on src/test/java/subway/SectionAcceptanceTest.java
> +        // 아래와 같이 하면 예외가 발생하지 않았다고 에러가 납니다 그래서 위와 같이 썼는데 이렇게 해도 되는 걸까요?
네 ☺️
SectionFactory.createSection 메서드는 서비스에서 예외가 발생하더라도, 사용하고있는 RestAssured는 HTTP 요청을 보내고 응답을 검증하는 역할을 합니다. RestAssured는 서버에서 발생한 오류를 자동으로 처리하며, 오류 상태 코드와 함께 응답 메시지를 반환합니다. 

따라서 createSection 메서드에서는 오류가 발생하지 않고 응답값이 전달되기때문에 예외가 발생하지 않는다고 판단되어, assertThatThrownBy를 사용한 검증 대신에 상태 코드와 응답 메시지를 확인하여 테스트할 수 있습니다.

2024-01-30 11:31 UTC, dbeod2 commented on src/test/java/subway/SectionFactory.java
> +    public static ExtractableResponse<Response> createSection(Long lineId, Long upstationId, Long downstationId) {
개인적인 의견이지만, 메서드명을 한글로 더 명확하게 표현되어도 좋을 것 같습니다. 
아래와 같이 네이밍을 하면 테스트코드를 읽을 때, 더 명확하게 표현되고 이해할 수 있을 것 같습니다.
참고부탁드립니다 🙏🏻

```suggestion
    public static ExtractableResponse<Response> 노선에_구간을_추가한다(Long lineId, Long upstationId, Long downstationId) {
```

2024-01-30 11:31 UTC, dbeod2 commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @DisplayName("지하철노선 구간 추가 실패2")
@DisplayName에  ("지하철노선 구간 추가 실패2")로 추가해도 좋지만, 조금 더 명확하게 실패 시나리오로 작성해보면 어떨까요?
그렇게 된다면, 어떤 실패 상황을 다루고 있는지 즉시 이해할 수 있고, 테스트 코드의 가독성을 높일 수 있을 것 같습니다.
 
참고부탁드립니다~

```suggestion
    @DisplayName("새로운 구간의 하행역은 이미 노선에 존재하는 역이면 안 됩니다.")
```

2024-01-30 11:31 UTC, dbeod2 commented on src/test/java/subway/SectionAcceptanceTest.java
> +
구간 테스트 케이스잘 작성해주신 것 같아요~ 👍

2024-01-31 00:40 UTC, samkimpepper commented on src/main/java/subway/exception/InvalidInputException.java
> +}
아닙니다! 별도의 필드를 선언할 필요가 없는지 몰랐습니다 ㅎㅎ...

2024-01-31 02:54 UTC, samkimpepper commented on src/main/java/subway/section/SectionController.java
> +public class SectionController {
맞습니다! 변경했습니다!

2024-01-31 02:55 UTC, samkimpepper commented on src/main/java/subway/line/Line.java
> +    private List<Section> sections = new ArrayList<>();
처음 들어보는 개념이네요. 어렵지만 어떻게든 적용해봤습니다! 감사합니다...

2024-01-31 02:55 UTC, samkimpepper commented on src/main/java/subway/exception/InvalidInputException.java
> +@Getter
이걸 빼면 에러가 발생해서 추가했습니다...

2024-01-31 07:48 UTC, dbeod2 commented on src/main/java/subway/exception/InvalidInputException.java
> +@Getter
오홋..지금도 혹시 동일한가요? 제가 빼고 했을때는 괜찮아가지구 질문드린거였어요 :)

2024-01-31 08:10 UTC, samkimpepper commented on src/main/java/subway/exception/InvalidInputException.java
> +@Getter
아앗... 그러네요. 빼도 잘 돌아가네요. ㅎㅎㅎ 제거하고 커밋했습니다! 감사합니다!

2024-01-31 15:54 UTC, dbeod2 approved these changes
피드백 반영 빠르게 해주셨네요 👍 
벌써 3단계 미션 마지막이라니 잘 진행해주셨습니다 💪🏻

1주차 마지막미션 여기서 머지하도록 하겠습니다 👏🏻👏🏻👏🏻

남은 미션도 잘 하실거라 생각들어요 ☺️☺️☺️ 
수고하셨습니다 ☺️

2024-01-31 15:54 UTC, dbeod2 commented on src/main/java/subway/section/Sections.java
> +public class Sections implements Iterable<Section> {
일급컬렉션을 적용해주셨네요 👍

2024-01-31 15:54 UTC, dbeod2 commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @DisplayName("하행종점역을 상행역으로 하지 않는 구간 추가 실패")
실패 케이스를 명확하게 작성해줌으로써 코드읽기가 더 쉬워진 것 같아요 👍

2024-01-31 15:54 UTC, dbeod2 commented on src/main/java/subway/section/Section.java
> +        //sectionRepository.save(section);
주석은 제거해주셔도 좋을 것 같아요 🙏🏻

2024-01-31 15:54 UTC, dbeod2 commented on src/main/java/subway/line/Line.java
미사용 되는 import문은 제거해주셔도 될 것 같아요~

2024-01-31 15:54 UTC, merged