🚀 2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #1087
Opened 2024-01-30 13:06 UTC by gutenLEE

구현 기능 목록

- [x] 지하철 노선 생성
- [x] 지하철 노선 목록 조회
- [x] 지하철 노선 조회
- [x] 지하철 노선 수정
- [x] 지하철 노선 삭제

2024-01-30 13:58 UTC, seovalue requested changes
안녕하세요~! 2단계 미션 잘 수행해주셨네요.
하지만 테스트가 잘 동작하지 않는데 이 부분 확인해주신 뒤 다시 리뷰 요청 부탁드릴게요!

2024-01-30 13:58 UTC, seovalue commented on src/test/java/subway/StationAcceptanceTest.java
>  package subway;
혹시 테스트 돌려보셨을까요?

2024-01-30 13:58 UTC, seovalue commented on src/main/java/subway/line/LineService.java
> +        Line line = lineRepository.save(new Line(lineRequest.getName(), lineRequest.getColor()));
Line의 distance를 not-null value로 지정해주셨는데, 실제 insert 시에는 값이 지정이 안되어서 exception이 발생해요.

2024-01-30 13:58 UTC, seovalue commented on src/main/java/subway/line/LineRequest.java
> +public class LineRequest {
Line 요청 시 역을 전달받는 것은 어떨까요?

2024-01-30 13:58 UTC, seovalue commented on src/test/java/subway/LineAcceptanceTest.java
> +    private static LineResponse createLine(Map<String, String> param) {
👍 재사용될 가능성이 높은 메서드들을 한데 모아 Util로 만들어봐도 좋을 것 같아요.

2024-01-30 13:58 UTC, seovalue commented on src/test/java/subway/LineAcceptanceTest.java
> +        RestAssured.given().log().all()
BAD_REQUEST로 검증하게 되면 다른 오류와 구분하기가 어렵지 않을까요?

2024-02-01 10:38 UTC, gutenLEE commented on src/test/java/subway/StationAcceptanceTest.java
>  package subway;
앗 최종으로 안돌려보고 올렸네요

2024-02-01 10:38 UTC, gutenLEE commented on src/main/java/subway/line/LineRequest.java
> +public class LineRequest {
역을 전달받는게 잘 이해가 안갑니다!

2024-02-01 11:22 UTC, gutenLEE commented on src/main/java/subway/line/LineRequest.java
> +public class LineRequest {
아아아 이해했습니다ㅎㅎ

2024-02-02 01:20 UTC, seovalue requested changes
안녕하세요!ㅎㅎ 리팩터링 해주신 것 확인했어요.
2단계 - 지하철 노선 관리 문서의 요구사항을 보면, `노선 생성 시 상행종점역과 하행종점역을 등록합니다. 따라서 이번 단계에서는 지하철 노선에 역을 맵핑하는 기능은 아직 없지만 노선 조회시 포함된 역 목록이 함께 응답됩니다.` 이러한 부분이 있는데요, 이 요구사항을 만족시킬 수 있도록 한번 수정해보는 것은 어떨까요? 자세한 리뷰는 코멘트에 남겨두었어요!

2024-02-02 01:20 UTC, seovalue commented on src/test/java/subway/StationAcceptanceTest.java
>  package subway;
<img width="857" alt="Screenshot 2024-02-02 at 10 12 30" src="https://github.com/next-step/atdd-subway-map/assets/48412963/0cf5ed44-6865-4a41-830c-3177cce8924a">
StationAcceptanceTest에도 LineAcceptanceTest에 적용해주신 것과 같은 teardown을 적용해주세요~!

2024-02-02 01:20 UTC, seovalue commented on src/main/java/subway/line/LineRequest.java
> +public class LineRequest {
@gutenLEE 혹시 이해 되셨을까요?
Line 객체를 보면 upStationId와 downStationId가 필드로 존재하는데요, 각 상행/하행역 없이도 노선이 존재할 수는 있지만 노선 생성 요청 시 실제 상행/하행역을 전달받을 수 있도록 하는 것은 어떨까요?
```java
public class LineRequest {
    private String name;
    private Color color;
    private Long upStationId;
    private Long downStationId;

    public String getName() {
        return name;
    }

    public Color getColor() {
        return color;
    }

    public Long getUpStationId() {
        return upStationId;
    }

    public Long getDownStationId() {
        return downStationId;
    }
}
```
그리고 Line 생성 시 upStationId와 downStationId를 함께 전달할 수 있을 것 같아요.

2024-02-02 01:20 UTC, seovalue commented on src/main/java/subway/line/LineRequest.java
> +public class LineRequest {
<img width="954" alt="Screenshot 2024-02-02 at 10 18 08" src="https://github.com/next-step/atdd-subway-map/assets/48412963/90b76f46-321b-40c8-b0e8-cc7b538e5498">
<img width="641" alt="Screenshot 2024-02-02 at 10 18 18" src="https://github.com/next-step/atdd-subway-map/assets/48412963/eb77e457-859e-49ba-9461-09bd22dede48">

[요구사항 문서](https://edu.nextstep.camp/s/vLaUvWbK/ls/muRYj6XH)에 있는 위 캡쳐된 부분을 한번 봐주시면 좋을 것 같아요~!

2024-02-03 10:32 UTC, gutenLEE commented on src/main/java/subway/line/LineRequest.java
> +public class LineRequest {
요구사항 다시 확인하여 반영했습니다!

2024-02-03 10:52 UTC, gutenLEE commented on src/test/java/subway/StationAcceptanceTest.java
이렇게 테스트 격리하려고 했다가 실패해서 주석 처리하고 `@DirtiesContext` 사용했습니다. 
실패 원인을 분석하려고 주석 처리 해두었습니다.

2024-02-03 10:52 UTC, gutenLEE commented on src/main/java/subway/line/LineService.java
LineService 가 `StationRepository`에 의존할지 'StationService'에 의존할지 고민이 됩니다. 
StationRepository에 의존하면 로우 레벨에 의존하게 되는듯하여 StationService를 의존할지
Line의 도메인 로직에 Station도 포함이니까 StationRepository를 의존하는게 맞는지 고민됩니다

2024-02-04 01:22 UTC, seovalue commented on src/main/java/subway/line/LineService.java
> +                .orElseThrow(() -> new StationNotFoundException(stationId));
commit이 꼬인 것 같은데 StationNotFoundException이 존재하지 않네요 😢

2024-02-04 01:22 UTC, seovalue commented on src/main/java/subway/line/LineService.java
저는 최대한 circular dependency를 없애려고 repository를 의존할 때가 횟수로 따지면 많긴 한데요, 제 생각엔 지금은 repository로 해주신 김에 repository로 해주시고, 어떤 장/단점이 있는지 직접 경험해보신 뒤 경험적으로 선택하는게 좋을 것 같아요!

2024-02-04 01:33 UTC, seovalue approved these changes
안녕하세요, 유희님! 리팩터링 잘 수행해주셨네요ㅎㅎ
이번 단계 요구사항은 모두 만족해서 이만 머지할게요!
사소한 코멘트 몇가지 남겼는데 다음 단계 진행하시면서 확인해주세요~!

2024-02-04 01:33 UTC, seovalue commented on src/main/java/subway/line/Line.java
> +    private Station upStation;
기존처럼 ID를 참조하는 것과 객체 자체를 참조하는 것은 어떤 장단점이 있을까요?

2024-02-04 01:33 UTC, seovalue commented on src/test/java/subway/LineAcceptanceTest.java
> +    public void findLines() {
목록에 포함된 지하철역까지 검증할 수 있으면 좋을 것 같아요!

2024-02-04 01:33 UTC, merged