[Step3] 지하철 구간 관리
next-step/atdd-subway-map pull request #109
Opened 2021-03-10 04:32 UTC by perelandrax

* 다른 도메인에 있는 데이터는 어떤 레이어(Repository, Service, Controller)에서 참조하는게 좋을까요?

* 
구간 등록기능에 보면 “새로운 구간의 상행역은 현재 등록되어있는 하행 종점역이어야 한다.” 라는 조건때문에 
추가되는 역이 늘 맨 마지막에 추가되고 중간에 역이 끼거나 할 수 없다고 생각했는데 (정렬됨)
힌트에 적어주신 역 목록 조회, 하행 종점 찾기 내용은 역이 정렬이 안되어 있는 상태를 가정한 탐색 방식인것 같아서
제가 등록기능 조건을 잘못 이해한건지 궁금합니다. (안그러면 힌트에 나온조건은 무의미해 보여서요)

*
보통 실무에서 서버 Exception은 Reponse을 어떤식으로 처리하는지 궁금합니다. 
(현재 실패테스트를 BadRequest 응답받는 테스트케이스를 만들었는데 Wrapping해서 의미있게 표현한다던지 하는… 등등의 방법이 궁금하네요)

* 다른분들 코멘트 보고 알았는데 참고 예제 소스는 어디있는건가요? ㅎ;

2021-03-10 13:14 UTC, junwoochoi requested changes
질문은 언제든지 환영입니다 😆 
1. 저 같은 경우는 서로 다른 도메인간에는 서비스 레이어에서 참조하고 있습니다 . 정답은 없지만, [클린아키텍처](https://blog.coderifleman.com/2017/12/18/the-clean-architecture/)에서 말하는 것처럼 바깥에서 안으로 흐르는 방향이 맞다고 생각해서 컨트롤러는 아닌 것 같고, repository를 의존하면 중복 코드가 많이 생겨나고 서로 다른 도메인간에 다른 레이어에서 의존성이 생기는 부분이 별로인 것 같아서 서비스 레이어단 끼리 참조하고 있습니다 ㅎ.ㅎ
2. 이해하신 요구사항이 맞습니다 :)
3. 실무에서는 각 팀마다 다르겠지만, 저희팀의 경우 공통 에러 객체를 만들어서 일관된 모양으로 만들어서 응답해주고 있습니다. 제가 중간에 드린 코멘트를 참고하시면 조금 더 도움이 되실 것 같아요 😃 
4. 참고 예제소스 링크는 성현님이 주말에 슬랙 채널에 올려주셨습니다! 
[링크](https://github.com/next-step/atdd-subway-map/tree/map-sample-without-refactoring)  다만, 브랜치명에서 아시겠지만... 리팩토링 전인 코드입니다 ㅎㅎ...

---

3단계 미션 기능 구현 및 인수테스트 작성, 리팩토링까지 잘해주셨습니다 👍 👍 

몇가지 코멘트 추가로 드렸는데, 확인 후 적용 부탁드립니다! 😃

2021-03-10 13:37 UTC, perelandrax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (!findAllStations().contains(section.getDownStation())) return;
근거가 있는 피드백 너무 좋습니다! 저도 변경해야겠네요. (근거는 없고 한줄이 좋아서 쓰고 있습니다 ㅎ;;)

2021-03-10 14:07 UTC, perelandrax commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    private LineRequest line2Request;
넵 변경토록 하겠습니다!!

2021-03-11 11:25 UTC, junwoochoi approved these changes
안녕하세요! 피드백 잘 적용해주셨습니다. 👍 
첫주차 미션 진행하시면서, ATDD에 관해 많은 이해도를 쌓으신 것 같아요 😄 

다음 미션도 화이팅입니다!!! 👏

2021-03-11 11:25 UTC, junwoochoi commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (sections.size() == 1) throw new OnlyOneSectionLeftCannotBeDeletedException();
매직넘버를 제거해보면 더 좋을 것 같아요!

https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

2021-03-11 11:25 UTC, merged

2021-03-11 11:29 UTC, perelandrax commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        if (sections.size() == 1) throw new OnlyOneSectionLeftCannotBeDeletedException();
넵! 다음번 PR에 반영하도록 하겠습니다! 감사드려요!