🚀 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #1122
Opened 2024-02-04 12:00 UTC by xonic789

안녕하세요.
말씀해주신 인수테스트 요청하는 부분 공통적으로 메소드를 만들어서 호출하는 방법으로 리팩토링 진행하였습니다.
하지만 시간이 없어서 말씀해주신 테스트 격리 리팩토링은 진행하지 못했습니다 ㅠㅠ
3단계 미션도 해피케이스에 대한 인수테스트만 작성하였는데요. 

일단 리뷰라도 받아보자는 마음으로 PR 올립니다!

2024-02-05 01:26 UTC, xonic789 commented on src/main/java/subway/domain/SectionRegister.java
> +public class SectionRegister {
DDD에서 말하는 DomainService를 만들어보았는데요,
도메인 객체간의 인터페이스를 도와줍니다!

2024-02-05 01:26 UTC, xonic789 commented on src/test/java/subway/Fixtures.java
> +public class Fixtures {
테스트 객체를 가지고 올 때 두 가지를 나누어서 뭉쳐보았습니다.
RequestBody에 대해 모아놓은 Fixtures,
HTTP 요청하고 응답 객체를 리턴하는 RequestFixtures
입니다.

2024-02-05 01:26 UTC, xonic789 commented on src/test/java/subway/StationLineAcceptanceTest.java
> +     * Given 지하철 역을 2개 생성하고
Line 인수테스트도 지하철역을 먼저 생성하고 노선을 생성하도록 변경하였습니다.

2024-02-05 08:58 UTC, bactoria requested changes
승우님 안녕하세요.
앞선 미션보다는 양이 좀 있는 편이라, 이렇게 리뷰를 쪼개서 보내주신 것도 좋은 것 같아요! 🙌

코멘트 몇가지 남겨두었는데, 이번 미션에서의 쟁점 중 하나인 인수테스트의 DirtiesContext에 대한 개선이 왜 필요한지, 어떻게 할 수 있는지의 개념은 확실히 가져가시면 좋을 것 같아요!
2주차 강의에서도 성현님이 자세히 설명을 해주셔서 혹시나 놓치셨다면 다시 보셔도 좋을 것 같아요!
어디서 막히시는지 제가 알면 도움 드릴 수 있을 것 같은데, 도움 필요하시면 디엠 주세요!

그리고 말씀주신 것 처럼 예외케이스에 대한 인수테스트도 챙겨주시면 좋을 것 같아요.
eg) 이미 등록된 지하철역을 구간으로 추가하는 케이스, 하행종착역이 아닌 역을 삭제하는 케이스

이어서 계속 진행 해 주세요!! 화이팅 💪 💪

2024-02-05 08:58 UTC, bactoria commented on src/main/java/subway/domain/SectionRegister.java
> +public class SectionRegister {
어떠한 불편함으로 도메인 서비스를 별도로 만드신 계기가 궁금해요. 😊
현재 라인에 구간을 추가하는 기능은 도메인 모델(Line과 Sections 클래스) 에서도 충분히 처리할 수 있어 보여서요!

sections에 대한 기능들이 Line에 있는 것이 불편하셨다면 sections를 [일급클래스](https://jojoldu.tistory.com/412) 로 추출 해 보는 건 어떨까요?

아래는 제가 재미있게 보았던 반버논의 도메인 주도 설계 구현 내용 중 일부인데요~
도메인 서비스는 좋지만, 가능하다면 도메인 모델에서 해결하는 것도 도메인 서비스로 빼내게 되면 무수히 많은 도메인 서비스가 만들어 질 것이고, 이는 결국 비즈니스 기능이 도메인 모델에 존재하지 못하고 도메인 서비스로 흩어지게 되어 단점이 될 수 있다고 생각 했어요.

<img width="460" alt="CleanShot 2024-02-05 at 11 35 40@2x" src="https://github.com/next-step/atdd-subway-map/assets/25674959/57129811-89bb-4e17-a4bb-19d950805510">

2024-02-05 08:58 UTC, bactoria commented on src/main/java/subway/domain/Line.java
> +    private Long downStationId;
Line에 sections가 있기 때문에 아래 3가지는 sections으로 부터 유추해 볼 수도 있을 것 같은데요.
- distance(총 거리)
- upStationId(상행종점역)
- downStationId(하행종점역) 

두벌쓰기는 관리해야 할 코드가 늘어나고, 버그를 발생시키는 포인트가 되기 쉬우므로
꼭 필요한 경우가 아니라면 지양하는 편입니다.

이 부분은 꼭 반영은 하지 않으셔도 괜찮지만, 
이런 상황에서 어떤게 유리할지는 한번 고민 해 보시면 좋을 것 같아요. 😊

2024-02-05 09:14 UTC, xonic789 commented on src/main/java/subway/domain/SectionRegister.java
> +public class SectionRegister {
도메인 서비스를 만든 이유는 단순히 Station 과 Line 과 Section이 노선 구간 등록할 때 필요하다고 생각했기 때문에  어느 객체에 책임을 쥐어줘야할지 고민이 돼서 도메인 서비스를 만들었습니다.
지금 생각해보니 Sections 에서 Line의 상행종점역, 하행종점역만 알 수 있다면 굳이 도메인 서비스까지 필요 없을 거 같네요 ㅎㅎ 
최대한 Line에서 해결해보도록 하겠습니다.

2024-02-05 15:49 UTC, xonic789 commented on src/main/java/subway/domain/SectionRegister.java
> +public class SectionRegister {
도메인 서비스 제거되었습니다
[5211bdf](https://github.com/next-step/atdd-subway-map/pull/1122/commits/5211bdf3f1bf21df96358898654681a1e2d85ea6)

2024-02-05 15:50 UTC, xonic789 commented on src/main/java/subway/domain/Line.java
> +    private Long downStationId;
[5211bdf](https://github.com/next-step/atdd-subway-map/pull/1122/commits/5211bdf3f1bf21df96358898654681a1e2d85ea6)
제거 되었습니다.

2024-02-06 00:22 UTC, bactoria requested changes
승우님 리뷰 반영 잘 해주셨네요!

추가로 사소한 버그가 있는 것 같아, 수정이 되면 좋을 것 같아요~
확인 후 리뷰요청 부탁드립니다!

2024-02-06 00:22 UTC, bactoria commented on src/main/java/subway/domain/Line.java
> +        return sections.stream().max(Comparator.comparing(Section::getId));
id가 최대인 구간이 마지막 구간이 되는군요!
다음 미션에서는 중간에도 구간을 추가할 수 있어서, 그 때는 수정이 필요 할 것 같아요.
참고 차 말씀드러요!

2024-02-06 00:22 UTC, bactoria commented on src/main/java/subway/domain/Line.java
> +            .orElseThrow(() -> new IllegalArgumentException("새로운 구간의 상행역은 기존 구간의 하행역과 일치해야 합니다."));
section 파라미터의 상행역와 비교하는 부분이 빠져있어서 기대한대로 동작하지는 않을 것 같아요. 🥹

2024-02-06 00:22 UTC, bactoria commented on src/main/java/subway/domain/Line.java
> +                if (!section.getDownStationId().equals(stationId)) {
[묻지말고 시켜라!](https://upcurvewave.tistory.com/478)
section 에 책임을 부여하도록 아래와 같이 변경 해 보는건 어떨까요?
```java 
if (section.isDownStation(stationId)) {
```

조금 더 리팩토링 해본다면 앞서 언급한 일급컬렉션을 활용한다면
라인 74~82의 코드들도 LINE에서 구현하는 것들이 아니라 SECTIONS 라는 클래스에 위임이 가능해서 유지보수하기 더 좋은 코드가 될 거에요!

2024-02-06 00:22 UTC, bactoria commented on src/main/java/subway/domain/Line.java
> -
제거 되었군요!! 👍 👍 👍 
리팩토링 하시면서 두벌쓰기에 장단점을 느끼셨으면 좋겠어요

2024-02-06 12:33 UTC, bactoria approved these changes
승우님 피드백 반영 잘 해주셨네요!
이번 미션은 이만 머지하도록 하겠습니다.
다음 미션들도 끝까지 힘내주시고, 도움 필요하시면 언제든 디엠주세요! 
고생 많으셨습니다. 👏 👏

2024-02-06 12:33 UTC, bactoria commented on src/main/java/subway/domain/Line.java
> +        if (!lastSection.getDownStationId().equals(section.getUpStationId())) {
section에서 만들어둔 isDownStationId 함수를 사용 해 볼 수 있겠네요!

2024-02-06 12:33 UTC, merged