3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #113
Opened 2021-03-10 15:06 UTC by eunsolJo

기능구현으로 들어오니..굉장히 헤매었습니다.
JPA 및 stream에 대한 공부가 더 필요할거 같네요..ㅜ
시간이 너무 지체된거 같아서, 우선 요구사항 구현이 완료되어 pr 생성 하였습니다. (;-;)
확인 부탁드립니다~ 

추가로, 몇가지 문의사항이 있어서 여쭙습니다!
- JPA에서 조회는 Entity객체로하고, 응답은 Response객체로 하게 되는데, 보통 어떤 식으로 해당 객체간의 호환(?) 이 이루어 지나요? (LineResponse.java 에서 of 메서드 관련 문의) 
- 테스트 코드 작성시 HashMap으로 Request객체를 대신해서 작성하였는데, Requset객체를 사용하는것이 보편적인가요? 아니면 HashMap을 사용하는것이 보편적인가요?
- 간단한 조회의 경우, 서비스에서 다른 도메인의 레파지토리를 접근하여도 무방할까요? 아니면, 그래도 서비스단을 통해 조회하는것이 좋을까요? (LineService에서 StationRepository주입받아 사용)
- 수정/삭제와 같은 기능에서 리턴값에 Response객체를 body 받아와 뿌리는 것이 콘솔을 통해 리턴값을 보기 좋은거 같아서, 구간추가/삭제 에서도 리턴값을 받아왔는데..보편적으로는 수정/삭제의 경우는 body값을 비워오는 것이 좋을까요..?

2021-03-11 15:30 UTC, heesunjeong requested changes
은솔님 3단계 미션 인수테스트 작성과 리팩토링까지 잘 해주셨어요 👍
로직구현에서 리팩토링 해보면 좋을 점에 대한 내용과 질문해주신 내용에 대해서 코멘트 추가했으니 확인해보세요 :)
혹시 답변이 모자라거나 더 좋은 의견이 있으시다면 언제든지 dm 주셔도 좋습니다 ! ~ :) 

—

> JPA에서 조회는 Entity객체로하고, 응답은 Response객체로 하게 되는데, 보통 어떤 식으로 해당 객체간의 호환(?) 이 이루어 지나요? (LineResponse.java 에서 of 메서드 관련 문의)

entity와 dto간에 변환 하는 여러 방법들이 있는데요. 제공된 코드처럼 dto에서 생성자나 빌더 패턴, 정적팩토리메서드 등를 활용해서 할 수도 있고, assembler를 따로 두어서 entity<>dto 변환하기도 해요. 아래글을 참고해보세요. ^^
[http://redutan.github.io/2016/04/15/poeaa-distribution-pattern](http://redutan.github.io/2016/04/15/poeaa-distribution-pattern)

> 테스트 코드 작성시 HashMap으로 Request객체를 대신해서 작성하였는데, Requset객체를 사용하는것이 보편적인가요? 아니면 HashMap을 사용하는것이 보편적인가요?

테스트 코드에서는 편하신 방법을 사용하시면 될 것 같습니다. 저같은 경우에는 HashMap을 사용했을때 key값 오탈자 같은 이슈가 있을 수 있고, dto의 변경이 있을때 바로 알 수 있어서 dto객체를 사용하는 편이에요. :)

> 간단한 조회의 경우, 서비스에서 다른 도메인의 레파지토리를 접근하여도 무방할까요? 아니면, 그래도 서비스단을 통해 조회하는것이 좋을까요? (LineService에서 StationRepository주입받아 사용)

우선, 직접 repository를 참조하게 되면 저장시에 필요한 유효성같은 부분들에 대한 중복이 일어날 수도 있기때문에 service를 참조하는게 맞다고 생각해요. 
그치만 서비스에서 서비스를 참조하게되면 언제든 순환참조가 발생할 수 있게되는데요, 순환참조가 일어나지 않게 위해서 서비스간에 단방향으로만 호출될 수 있도록 계층 구조를 가질 수 있도록 설계가 되어야 할 것 같아요. 아래 글은 비슷한 고민을 한 분의 글인데 controller를 활용하는 방법도 있다고하니 참고해보세요.
[https://velog.io/@sumusb/Spring-Service-Layer에-대한-고찰](https://velog.io/@sumusb/Spring-Service-Layer%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B3%A0%EC%B0%B0)

> 수정/삭제와 같은 기능에서 리턴값에 Response객체를 body 받아와 뿌리는 것이 콘솔을 통해 리턴값을 보기 좋은거 같아서, 구간추가/삭제 에서도 리턴값을 받아왔는데..보편적으로는 수정/삭제의 경우는 body값을 비워오는 것이 좋을까요..?

이건 상황에 따라 다를 것 같아요. 주로 응답값을 사용할 때, 수정, 삭제의 경우에는 status code만으로 결과를 충분히 표현할 수 있기 때문에 body가 없어도 되는 api인 것 같습니다. :) 물론 필요하다면 body에 값을 넣어줄 수도 있지만요!

> 예외의 경우.. 사용자 예외를 따로 생성하는것에 대한 이점을 ..잘 모르겠어서, 모두IllegalArgumentException 를 throw 하게끔 처리를 하였는데, 혹시 이런경우 각케이스 사용자 예외를 만드는것이 좋을까요?

답이 없는 질문이지만 상황에 따라 다를 것 같아요. 좀 더 이름이 명확한 exception을 사용하고, 공통적으로 처리하기 위해서 커스텀한 예외를 만들어서 사용하지만, 너무 많아지면 관리 차원에서 힘들어지기도 해요. 저 같은 경우에는 공통으로 메세지나 예외처리가 필요하다고 생각할때 커스텀하게 생성해서 사용하고 있습니다.
아래에 글에서도 같은 고민을 하지만 결론은 내지 못했는데요, 어떻게 생각했는지 참고해보세요. :)
[https://woowacourse.github.io/javable/post/2020-08-17-custom-exception/](https://woowacourse.github.io/javable/post/2020-08-17-custom-exception/)

2021-03-11 15:30 UTC, heesunjeong commented on src/main/java/nextstep/subway/line/application/LineService.java
> +import static nextstep.subway.line.domain.Section.createSection;
불필요한 import는 제거해주세요 :)

2021-03-13 11:59 UTC, eunsolJo commented
리뷰해주신 내용을 기반으로 소스 리팩토링 하여 재 리뷰요청 드립니다! :)

2021-03-14 04:26 UTC, heesunjeong approved these changes
피드백 드린 내용에 대해서 잘 반영해주셨네요. 💯 
추가로 몇가지 코멘트를 추가했는데요, 확인해보시고 앞으로 미션 진행하실 때 참고해주시면 좋을 것 같습니다! :)
1주차 미션 너무 고생 많으셨습니다 👏 2주차 미션도 화이팅입니다! 🔥

2021-03-14 04:26 UTC, heesunjeong commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        line.getSections().removeLastSection(stationId);
line을 탐색해서 가져온 sections가 아닌 line에 메세지를 보내고, line이 직접 가지고있는 sections에 removeLastSection() 메세지를 보내보면 어떨까요? 디미터 법칙에 대해서 알아보시면 좋을 것 같아요. :)
https://woowacourse.github.io/javable/post/2020-06-02-law-of-demeter/

2021-03-14 04:26 UTC, merged