3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #1210
Opened 2024-07-09 16:32 UTC by jin-mook

안녕하십니까 정진묵입니다.
3단계 미션도 피드백 잘 부탁드립니다!!

2단계에서 피드백 주신 내용도 반영했습니다

JPA를 실무에서 사용하지 않아서 좀 헷갈리는 부분이 있는것 같습니다.

특히 Line 엔티티와 Section 엔티티가 일대다 관계라고 생각해서 List<Section> 형태가 아닌
Sections 객체인 일급 컬렉션 객체를 사용했는데, 평소에 개인적으로 사용할 때는 List 형태로 정의해서 사용하다,
DDD에 관심이 생기며 공부하다 이번에 일급 컬렉션 객체를 사용해봤는데 제대로 사용한게 맞는지 헷갈리네요 ㅠㅠ

해당 일급 컬렉션 객체를 통해 Section 을 추가하고 삭제하는 부분의 코드들을 조금 봐주시면 감사할것 같습니다.
나름 테스트도 꼼꼼하게 하면서 기능 구현은 잘 된것 같은데 JPA를 잘 사용했는지 모르겠네요, 실무에서도 이렇게 사용하나 싶어서 질문 남겼습니다.

감사합니다!!

2024-07-10 10:32 UTC, catsbi requested changes
진묵님 3단계 미션도 빠르게 구현해주셨네요. JPA를 처음쓰셨다고 하셨는데, 적절히 잘 사용해주신 것 같습니다. 구간정보의 종속성 개념에 맞게끔 적절히 애노테이션 속성들을 설정해주셨네요 👍 

추가적으로 고민해보면 좋을 피드백을 좀 남겨드렸으니 확인 후 다시 리뷰요청 부탁드려요!

2024-07-10 10:32 UTC, catsbi commented on src/main/java/subway/common/ErrorResponse.java
> +    }
Error가 4XX 예외만 있는건 아니지 않을까요?

2024-07-10 10:32 UTC, catsbi commented on src/main/java/subway/common/ErrorMessage.java
> +public class ErrorMessage {
문자열 메세지만 담을 것이라면 그냥 String으로 처리해도 문제가 없습니다. 
봉투 패턴(Envelop Pattern)을 활용할 것이라면 좀 더 의미있는 정보들을 추가해볼 수 있을 것 같아요

2024-07-10 10:32 UTC, catsbi commented on src/main/java/subway/common/SuccessResponse.java
> +        httpHeaders.addAll(HttpHeaders.VARY, List.of("Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers"));
이 부분도 추상화가 될 수 있을 것 같네요!

2024-07-10 10:32 UTC, catsbi commented on src/main/java/subway/line/Line.java
> +    }
Sections 일급 컬렉션으로 책임 위임 적절히 잘 해주셨네요 👍

2024-07-10 10:32 UTC, catsbi commented on src/main/java/subway/line/LineResponse.java
> +                .collect(Collectors.toList());
직접 구간정보 목록을 꺼내서 작업하는 방식도 있지만 저는 고차함수를 이용한 방식도 좋아하는 편인데 고려해봐도 좋을 것 같아요.

```suggestion
        List<LineStationsResponse> stationList = line.mapSectionStations(LineStationsResponse::new)
```

2024-07-10 10:32 UTC, catsbi commented on src/main/java/subway/section/Section.java
> +    public void addLine(Line line) {
addLine이라는 네이밍이 적절할까요?

2024-07-10 10:32 UTC, catsbi commented on src/main/java/subway/section/SectionService.java
> +public class SectionService {
구간정보는 노선에 종속되는 개념이라 독립적으로는 존재하지 않는 객체죠. 그렇기에 별도의 서비스가 나올 필요가 있을지 고민해보면 좋을 것 같습니다!

2024-07-10 10:32 UTC, catsbi commented on src/main/java/subway/station/Station.java
> +        if (o == null || getClass() != o.getClass()) return false;
한 줄짜리 코드도 블럭`{}` 생략은 지양해주세요. 코드의 일관성을 떨어트리면 가독성 저하로 연관되거든요. 
IDE에 의해 자동생성된 코드 역시 동일합니다!

2024-07-10 10:32 UTC, catsbi commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +        Assertions.assertThat(result.jsonPath().getString("message")).isEqualTo("구간 정보가 올바르지 않습니다.");
해당 예외 메세지를 하드코딩으로 작성하게 될 경우 나중에 기획의도로 인해 메세지가 변경될 때 이 부분을 놓치면 바로 테스트가 깨질 수 있어요. 어떻게 고치면 좋을까요?!

2024-07-10 10:32 UTC, catsbi commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest {
꼼꼼하게 테스트를 잘 작성해주셨네요 👍 
여유가 되신다면 JUnit구조의 계층 구조를 활용한 BDD 방식의 인수테스트도 가능한데 확인해보시면 좋을 것 같습니다. 
https://johngrib.github.io/wiki/junit5-nested/

2024-07-10 10:32 UTC, catsbi commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +                .then().extract().jsonPath().getLong("id");
해당 given절이 반복되게 전체적으로 사용된다면 beforeEach로 분리해도 좋을 것 같네요!

2024-07-11 01:10 UTC, jin-mook commented on src/main/java/subway/common/ErrorResponse.java
> +    }
처음에는 요구사항에 따로 에러 응답에 대한 내용이 없어서 간단하게 진행하려고 4XX 예외만 우선 작성했습니다.
추가로 NOT_ACCEPTABLE, INTERVAL_SERVER_ERROR 2개 더 추가했습니다!!
감사합니다~~

2024-07-11 01:12 UTC, jin-mook commented on src/main/java/subway/common/ErrorMessage.java
> +public class ErrorMessage {
봉투 패턴은 처음 들어봤는데 좋은 패턴에 대해 알려주셔서 감사합니다!!

지금은 에러 응답 형식에 대한 요구사항이 없어서 간단히 문자열 메세지만 담도록 수정했습니다
이후 추가 요구사항이 생긴다면 봉투 패턴을 활용해보겠습니다!!

감사합니다~~

2024-07-11 01:35 UTC, jin-mook commented on src/main/java/subway/common/SuccessResponse.java
> +        httpHeaders.addAll(HttpHeaders.VARY, List.of("Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers"));
넵!!
FunctionalInterface 를 이용해서 Location 정보를 주도록 코드 수정했습니다

감사합니다~~

2024-07-11 01:49 UTC, jin-mook commented on src/main/java/subway/section/Section.java
> +    public void addLine(Line line) {
네이밍이 addLine만 본다면 Section 객체가 더 상위 객체라고 느껴지는것 같습니다. 다시 보니,
따라서 연관관계를 위한 메서드라고 좀 더 명확하게 느껴지도록 addMappingWithLine 이라는 이름으로 변경해보았습니다!

감사합니다~~

2024-07-11 01:50 UTC, jin-mook commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +        Assertions.assertThat(result.jsonPath().getString("message")).isEqualTo("구간 정보가 올바르지 않습니다.");
이러한 메시지 정보를 담는 enum 클래스를 추가했고 해당 클래스에 모든 메시지 정보를 갖도록 했습니다.
테스트할때도 해당 클래스를 이용하도록 수정했습니다!!

2024-07-11 02:30 UTC, jin-mook commented on src/main/java/subway/line/LineResponse.java
> +                .collect(Collectors.toList());
말씀하신 부분이 DTO 객체에 엔티티를 DTO로 변환시킬 메서드를 작성할 것인가, 아니면 엔티티 객체에 엔티티를 DTO로 변환시킬 메서드를 작성할 것인가를 선택해야 하는 문제가 아닌가 생각이 들었습니다.

우선 저렇게 코드를 작성하게 된 저의 생각을 조심스럽게 공유드리겠습니다.
1. 변화의 관점에서 LineResponse 응답의 형태가 바뀐다면 기존에 작성한 부분만 변경하면 될거라고 생각했습니다.
- Line에 존재하는 데이터를 조작해서 응답의 형태로 맞춰주기만 하면 된다고 느껴서 LineResponse 클래스만 수정하면 되지 않을까 생각했습니다.


2. 이 이유가 좀 더 큰데 Line 객체가 핵심 도메인 엔티티라고 생각했기 때문에 DTO 변환과 같은 로직을 엔티티 내부에 작성하고 싶지 않았습니다.
- 핵심 도메인 엔티티에서는 비즈니스와 관련된 메서드가 주로 오는게 좋을거라고 생각했습니다.
- 현재는 LineResponse DTO 한 개이지만 이후에 여러 DTO가 추가될때마다 도메인 엔티티에 변환 로직이 들어가는 것보다는 각 DTO 클래스에서 엔티티를 의존해서 변환하는 로직을 갖는게 좋지 않을까?? 라는 생각을 했습니다.


제가 현업 경험이 많지 않아서 실제 현업에서 어떻게 주로 사용하는지 잘 모르다보니 개인의 주관이 좀 많이 들어간 부분이 있는것 같습니다. 리뷰어님의 경험을 바탕으로 어떤식으로 처리한다고 경험을 공유해주시면 많은 도움이 될 것 같습니다!!

코드는 말씀하신 대로 고차함수를 이용해 추상화 시키도록 변경했습니다!!
감사합니다~~

2024-07-11 04:29 UTC, jin-mook commented on src/main/java/subway/line/LineResponse.java
> +                .collect(Collectors.toList());
아 코드를 수정하다보니 제가 답변을 좀 잘못 이해한것 같습니다.
고차 함수가 결국 추상화 해서 DTO를 변환하는 부분을 Line 엔티티에 두는 것으로 이해를 했는데

함수형 인터페이스를 활용하라는 의도로 피드백을 주신것 같습니다.
피드백 주신 내용 이해를 좀 잘못 한것 같은데, 그래도 혹시 위 질문과 겹치는 부분이 있는것 같아서 답변 주시면 감사하겠습니다!!

코드는 고차함수를 이용하도록 변경했습니다!!
감사합니다!!

2024-07-11 04:37 UTC, jin-mook commented on src/main/java/subway/section/SectionService.java
> +public class SectionService {
음... 혹시 그러면 Section 패키지 내부에 있는 클래스들을 Line 패키지 하위로 옮기고
위 클래스 이름을 LineSectionService 이런식으로 수정을 하면 괜찮을까요??

구간 자체는 노선에 종속되는 개념인데 구간을 추가하거나 삭제하다보니 따로 Section 패키지로 두고 작업했는데
도메인 개념으로 보면 Line 패키지에 있는게 좀 더 어울리는 것 같다는 생각을 피드백을 받고 하게 되어서 질문 남깁니다!!

감사합니다~~

2024-07-11 04:42 UTC, jin-mook commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +                .then().extract().jsonPath().getLong("id");
넵 반복되는 부분인 upStationId, downStationId, lineId 생성 로직은 beforeEach로 분리했습니다
감사합니다!!

2024-07-11 04:43 UTC, jin-mook commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest {
좋은 내용 공유해주셔서 감사합니다~~

관련 내용은 공부해보고 적용하도록 하겠습니다!!

2024-07-11 09:47 UTC, catsbi commented on src/main/java/subway/line/LineResponse.java
> +                .collect(Collectors.toList());
네 두 번째 댓글처럼, 제 의견은 엔티티에 dto를 의존하는 로직이 있어야한다가 아니라 ㅎㅎ 행위 자체를 전달하여 동작하게 함으로써 엔티티는 별도의 dto 의존성을 두지 않으면서 내부 값을 외부로 다 꺼내어 제공하는것도 최소화 하면 좋겠다는 취지의 피드백이였습니다 ㅎㅎ

2024-07-11 09:47 UTC, catsbi commented on src/main/java/subway/section/Section.java
> +    public void addLine(Line line) {
앗, 그런 의미보단 Line은 복수가 아닌 단수의 개념인데 add가 아니라 set이나 update가 적절하지 않을까 하는 의미였습니다 ㅎㅎ

2024-07-11 09:50 UTC, catsbi commented on src/main/java/subway/section/SectionService.java
> +public class SectionService {
이건 정답이 있는 개념은 아니라고 생각해서 고민해보면 좋겠다고 피드백을 드렸는데요. 
제 개인 사견을 좀 더 담아보자면, 구간 정보는 Line에 종속되어있을 뿐 아니라 Line이 제거되면 같이 사라지는 고아객체이기도 합니다. 
그렇기에 오히려 구간정보가 별도로 관리되고 제어되는게 관리의 범위가 넓어져서 유지보수성이 떨어질 수 있다는 생각이에요.

그리고 구간을 제어한다는건 결국 노선의 정보를 제어한다는 의미랑도 일맥상통하다고 생각하거든요. 

이정도의 생각이 제 의견인데, 진묵님도 고민해보시고 좀 더 괜찮겠다 생각하는방향으로 설계해보시면 좋을 것 같습니다.

2024-07-11 09:54 UTC, catsbi approved these changes
진묵님, 피드백 반영 잘 해주셨어요. 3단계 미션인만큼 꼼꼼하게 확인했는데, 크게 문제없이 깔끔하게 잘 만들어주신 것 같습니다 💯 

3단계 피드백 질문에 대한 답글과 몇가지 피드백 남겨드렸으니 확인해보시면 좋을 것 같습니다. 
미션은 여기서 마무리하겠습니다. 다음 미션에서도 화이팅입니다! 👍

2024-07-11 09:54 UTC, catsbi commented on src/main/java/subway/common/ErrorMessage.java
> +public enum ErrorMessage {
열거타입이 상속이나 리플렉션에 의한 외부 공격에도 안전한 타입이라 나쁘지 않은 선택입니다 👍 
다만, 예외의 구체적인 메세지를 중앙집중화로 관리한다는건 즉, 각 도메인의 비즈니스 정보가 한 클래스에 집중되어 책임의 영역이 커질 수 있다는 말도 되니 주의해서 사용하면 좋을 것 같아요

2024-07-11 09:54 UTC, catsbi commented on src/main/java/subway/common/ErrorResponse.java
> +        return new ResponseEntity<>(message, makeJsonHeader() , HttpStatus.BAD_REQUEST);
ResponseEntity는 builder 패턴도 제공을 하니 찾아보면 좋을 것 같습니다.

2024-07-11 09:54 UTC, merged