🚀 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #1216
Opened 2024-07-11 08:21 UTC by dahyeong-yun

안녕하세요 승연님! 3단계 리뷰 요청을 드립니다.

해결하지 못한 것들이 더러 있는데 짧은 시간안에는 해결이 안될 것 같아, 먼저 리뷰 요청을 올립니다.

### 해결하지 못한 부분
- 예외 처리에 및 관련 테스트를 거의 고려하지 못했습니다.
- 로직 상 지하철 역이 삭제 요청이 되는 경우, 노선과 구간에 포함된 역에 대해 아직 처리 방법을 만들지 못했습니다. 여기서 구간에 포함여부를 검증하게 된다면 인수테스트에서 지하철 역 삭제 테스트가 복잡해질 것으로 염려가 되어서, 쉽게 삭제 방법을 못찾았네요.
- 이 밖에 생각보다 시간이 촉박하다는 것을 알았는데, 다음 주차 부터는 좀 더 시간 관리를 신경 써보겠습니다.

확인  부탁드릴게요~!

2024-07-12 07:19 UTC, heoseungyeon requested changes
안녕하세요 다형님.
3단계까지 잘 수행해주셨네요!! 
커멘트 드린 부분 있는데 말씀 주신 부분을 구현하는데에 도움이 됐으면 해요. 
한번 확인 부탁드리며 다시 PR 요청 부탁드리겠습니다 👍

2024-07-12 07:19 UTC, heoseungyeon commented on src/main/java/subway/application/LineService.java
> +        sectionRepository.save(section);
SectionRepository가 LineService에 반드시 있어야 될까요? Line 내부에서 Section을 생성해보면 SectionRepository 의존성을 가지고 있지 않아도 될 것 같아요.

2024-07-12 07:19 UTC, heoseungyeon commented on src/main/java/subway/application/SectionService.java
> +    }
구간 등록, 삭제에 대한 비즈니스 로직을 Line의 Sections 필드가 책임을 갖게 하면 어떨까요? 
'Sections' 클래스에 등록 및 삭제 예외 케이스들을 잘 정리하면 예외처리하기 편해질거에요:)
그리고 특정 노선(Line)에 구간(Section)을 추가/삭제한다는 관점에서 위 행위에 대한 정의를 LineService에서 가져가고 Line -> Sections 흐름의 비즈니스 로직을 고려해보면 좋을 것 같습니다.

2024-07-12 07:19 UTC, heoseungyeon commented on src/test/java/subway/SectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(201);
```suggestion
        assertThat(response.statusCode()).isEqualTo(HttpStatus.Created);
```

2024-07-12 07:19 UTC, heoseungyeon commented on src/test/java/subway/SectionAcceptanceTest.java
> +
역 생성이 각 테스트별로 겹치는 부분이 있는데 @BeforeEach 메서드를 통해 테스트 픽스쳐들을 생성해보면 중복을 제거할 수 있을거에요!

2024-07-15 13:40 UTC, dahyeong-yun commented on src/main/java/subway/application/LineService.java
> +        sectionRepository.save(section);
save method에서 연관관계를 맺어주면 둘 다 insert 문이 나가는 군요. JPA가 아직은 익숙치가 않아서 이렇게 접근할 생각을 못했네요 👍🏼

2024-07-15 14:12 UTC, dahyeong-yun commented on src/test/java/subway/SectionAcceptanceTest.java
> +
테스트 클래스별 멤버 변수를 만드는 것으로 @BeforeEach 형태를 만들어 보았습니다. 상태를 가지는 것이 살짝 걸리는 데, @Sql로 테스트 격리를 처리하고 있으니 큰 문제는 없는 것 같네요.

2024-07-15 14:16 UTC, dahyeong-yun commented on src/main/java/subway/application/SectionService.java
> +    }
노선에 역을 추가하는 책임을 Sections로 옮기고, 일부 커스텀 예외 클래스를 추가 했습니다. 아직 눈에 띄는 변화인지는 모르겠는데, 다음 미션에서 계속 구간 추가에 대한 비즈니스 로직이 추가될 시점에 더 와닿는 포인트가 생길 것 같네요.

2024-07-15 14:17 UTC, dahyeong-yun commented
안녕하세요 승연님! 조금 텀이 있었지만, 코멘트 주신 부분들 다시 수정 해보았어요. 확인 한번 부탁 드릴게요!

2024-07-16 10:34 UTC, heoseungyeon approved these changes
안녕하세요 다형님.
피드백 잘 적용해주신 것 확인했습니다.
이번 주차 미션 끝까지 수행하시느라 고생많으셨습니다👍
다음 미션도 지금처럼 잘 수행하실거라 믿습니다🎉 
앞으로도 응원하겠습니다🔥🔥🔥

2024-07-16 10:34 UTC, heoseungyeon commented on src/test/java/subway/LineAcceptanceTest.java
> +        또다른역 = Long.valueOf(StationSteps.createStation("또다른역").body().jsonPath().getString("id"));
👍

2024-07-16 10:34 UTC, heoseungyeon commented on src/test/java/subway/LineAcceptanceTest.java
> +        Long fifthLineId = Long.valueOf(response.body().jsonPath().getString("id"));
```suggestion
        Long fifthLineId = response.body().jsonPath().getLong("id");
```

2024-07-16 10:34 UTC, heoseungyeon commented on src/main/java/subway/exception/LineNotFoundException.java
> +        super("지하철 노선 ID " + id + " 가 존재하지 않습니다.");
중복되는 에러메세지를 ErrorMessage Enum 클래스를 선언해 관리해도 좋을 것 같네요.

2024-07-16 10:34 UTC, heoseungyeon commented on src/main/java/subway/domain/Line.java
> +        Line createdLine = new Line(lineRequest.getName(), lineRequest.getColor());
피드백 잘 적용해주셨네요👍 라인을 생성할 때 this 메서드를 활용해보면 더 깔끔해질 수 있습니다!

2024-07-16 10:34 UTC, merged