3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #1219
Opened 2024-07-11 15:48 UTC by sazzeo

안녕하세요 리뷰어님~ 3단계 리뷰 요청 드립니다.
2차 수업 듣기 전 절반, 2차 수업 듣고 나서 절반 작성한 거라 오늘 수업 피드백 부분을 일부 반영했습니다. 

인수테스트에 있었던 부분을 일부 단위 테스트로 옮겨서 작성했습니다.

특히 section-station 간 연관 관계를 간접 참조로 변경하면서 역을 반환할 때 어떻게 매핑해줄건지 여기서 시간을 제일 많이 쓴 것 같습니다. 

이번에도 잘부탁드립니다

2024-07-11 15:52 UTC, sazzeo commented on src/main/java/subway/line/payload/AddSectionRequest.java
> +    }
테스트 코드 만을 위한 생성자를 만들어도 되는걸까요?

2024-07-11 15:55 UTC, sazzeo commented on src/main/java/subway/line/service/LineService.java
>      }
단순 조회 로직이 매핑 때문에 길어졌는데 클래스를 따로 빼는게 좋을까요? (CQRS 패턴)

2024-07-11 15:57 UTC, sazzeo commented on src/main/java/subway/line/service/LineService.java
>      }
단순 조회 로직이 매핑 때문에 길어졌는데 클래스를 따로 빼는 게 좋을까요? (CQRS 패턴)

2024-07-12 16:00 UTC, Flamme1004K requested changes
안녕하세요! 

3단계 미션 잘해주셨습니다! 인수 테스트에 대해서 방향을 점점 잡아나아가시는 것 같아서 기쁘네요.

몇 가지 피드백을 드렸으니, 확인 후 다시 리뷰 요청 부탁드립니다.

감사합니다!

2024-07-12 16:00 UTC, Flamme1004K commented on src/test/java/subway/line/LineAcceptanceTest.java
> +    private Long 삼성역;
피드백 반영 좋습니다! 👍👍

2024-07-12 16:00 UTC, Flamme1004K commented on src/test/java/subway/line/domain/LineTest.java
> +class LineTest {
단위 테스트 좋습니다 👍

2024-07-12 16:00 UTC, Flamme1004K commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest {
단계가 지남에 따라 점점 인수 테스트에 대한 감을 잡아나아가시는 부분이 매우 훌륭하시네요!

이대로 `구간 등록과 제거 기능의 예외케이스들에 대한 시나리오를 정의` 에 대한 인수 테스트도 같이 진행해볼까요?

2024-07-12 16:00 UTC, Flamme1004K commented on src/main/java/subway/line/domain/Line.java
> +        sections.removeLastStation();
로직 좋네요!

2024-07-12 16:00 UTC, Flamme1004K commented on src/main/java/subway/line/domain/Sections.java
> +    }
section에 대해 존재하지 않는다면 line에게 책임을 건네주는 것보다 boolean으로 반환하는 것보다는 예외 처리를 하는 게 좋지 않을까 하네요~

2024-07-12 16:00 UTC, Flamme1004K commented on src/main/java/subway/line/domain/Sections.java
> +    }
jpa에서 이미 station 정보를 불러올 텐데, 이에 대해서 getStationIds를 다시 가져와서 불러오지 않아도 될 것 같네요.

2024-07-12 16:00 UTC, Flamme1004K commented on src/main/java/subway/line/domain/Sections.java
> +    public boolean isLastStation(final Long stationId) {
```suggestion
    private boolean isLastStation(final Long stationId) {
```

private로 접근제어를 하는게 좋지 않을까요~?

2024-07-12 16:00 UTC, Flamme1004K commented on src/main/java/subway/line/payload/AddSectionRequest.java
> +    }
테스트 코드 만을 위한 생성자에 대해서는 선택인 것 같습니다. 저 같은 경우에는 테스트 코드에 대한 생성자를 만드는 편입니다.

2024-07-12 16:00 UTC, Flamme1004K commented on src/main/java/subway/line/service/LineService.java
>      }
해당 부분이 CQRS 패턴인지는 잘 모르겠네요. 구조적인 부분도 있고,  저는 현재 로직이 그저 도메인에 대한 로직을 DTO로 변환하는 것이라고 생각합니다.

CQS와 CQRS에 대한 개념을 체크해 보시길 바래요~

2024-07-12 22:12 UTC, sazzeo commented on src/main/java/subway/line/service/LineService.java
>      }
이부분이 CQRS라는게 아니라 단순 조회를 위한 매핑 로직 밖에 없어서 이 부분을 다른 클래스로 빼서 조회로직들을 분리해보면 어떨까에 대한 질문이었습니다 
CQS 패턴이 CQRS 상위 개념인 줄은 몰랐네요
제가 실무에서도 CQRS 패턴을 어느 정도 적용해보고 있는데 피드백 받을 곳이 마땅치 않아서 리뷰어님의 생각이 궁금했습니다

2024-07-12 22:18 UTC, sazzeo commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest {
이 부분은 원래 인수 테스트가 있었는데요, 지난 강의에서 강사님께서 기능과 비즈니스 로직을 분리해서 기능은 인수테스를하고 비즈니스 로직은 단위테스트를 한다라고 하셔서 단위 테스트로 해당 예외케이스들을  넣으면서 없앴습니다. 

해당 부분을 중복 검증하는 게 좋을까요?

그리고 검증시 
1. 새로운 구간의 상행역은 해당 노선에 등록되어있는 하행 종점역이어야 한다.
2. 이미 해당 노선에 등록되어있는 역은 새로운 구간의 하행역이 될 수 없다.
실패 케이스가 두개의 조건에 걸리는데 어디서 실패했는지 블랙박스 테스트로 검증하려면 어떻게 하시는지 궁금합니다.

두 케이스는 결과가 상태 코드와 데이터에 변화가 없는 점에서 똑같고 에러메시지나 코드로 검증하자니 이부분은 언제든 바뀔 수 있는 부분이라고 생각해서요

2024-07-12 22:22 UTC, sazzeo commented on src/main/java/subway/line/domain/Sections.java
> +    public boolean isLastStation(final Long stationId) {
엇 이부분은 Line 클래스에서 쓰고있습니다 ㅠ
혹시 이부분 피드백이 Line에 있는 add와 remove의 책임을 Sections에 옮겨보라는 의견이실까요?

2024-07-12 22:25 UTC, sazzeo commented on src/main/java/subway/line/domain/Sections.java
> +    }
이 부분은 이미 불러온 Sections에서 역id들을 추출하는 코드인데요
해당역이 3개인 경우 구간은 2개이기 때문에 모든 역들의 상행역 + 마지막역의 하행역을 추가해서 역들을 가져오게끔 만들었습니다
사실 이 부분이 꽤 애매했는데 메소드명을 좀 더 자세하게 바꾸는 게 좋을까요?

2024-07-13 01:40 UTC, Flamme1004K commented on src/main/java/subway/line/service/LineService.java
>      }
아하~ 이해했습니다. 이번 기회에 조회 로직을 분리시키는 것도 좋아 보이네요 :) 

command와 query에 대한 클래스를 나누면, 확실히 클래스 간 역할이 단순화되어서 좋네요.

다만, command와 query가 나눠지는 경우에는 command에서는 query를 읽어야 하는 건 없어야 되겠죠?

2024-07-13 01:45 UTC, Flamme1004K commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest {
저는 두 개의 예외 테스트가 결국에는 인수자도 알아야 하는 시나리오라고 생각해요.

단위 테스트는 개발자를 위한 테스트이지만 ,인수 테스트는 인수자를 위해서 만드는 테스트입니다. 그래서 단위 테스트와 인수 테스트는 다른 목표를 가지고 있습니다. 독자가 다르죠! 인수 테스트에 대한 독자는 인수자이기 때문에 시나리오에 대해 잘못된 요청에 대한 케이스도 인수 테스트로써 제공한다면, 인수 테스트는 인수자를 위한 친절한 테스트가 되겠죠?

2024-07-13 01:45 UTC, Flamme1004K commented on src/main/java/subway/line/domain/Sections.java
> +    public boolean isLastStation(final Long stationId) {
엇! 제가 잘못봤네요! 요건 그대로 하셔도 될 것 같습니다.

2024-07-13 06:58 UTC, sazzeo commented
안녕하세요. 
리뷰내용 반영하여 인수테스트를 추가했습니다.
그리고 원래 Line 이 가지고 있는 책임을 Sections에게 넘기면서 새 테스트 코드들을 추가해봤습니다. 

이번에도 리뷰 잘부탁드립니다

2024-07-13 12:45 UTC, Flamme1004K approved these changes
안녕하세요! 

3단계 피드백 반영 고생하셨습니다! 이만 머지하도록 하겠습니다. 👍

다음 인수 테스트와 TDD 화이팅하시길 바랍니다!

감사합니다.

2024-07-13 12:45 UTC, Flamme1004K commented on src/main/java/subway/line/domain/Sections.java
> +    }
역id를 추출하여 stationRepository를 통하여 station정보를 가져오는 로직이였군요. 😅

해당 부분에 대해서는 메서드명을 좀 더 자세히 하는 것보다는 주석을 추가해놓는 방법도 저는 좋다고 생각합니다.

2024-07-13 12:45 UTC, Flamme1004K commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +
예외에 대한 인수테스트 좋네요 👍👍

2024-07-13 12:45 UTC, merged