Step3
next-step/atdd-subway-map pull request #1220
Opened 2024-07-11 16:33 UTC by mlbase

한 주 동안 미션 진행하면서 얻어가는게 많은 코드 리뷰였습니다.
우선 피드백 주신 부분은 대부분 code 에 반영되었습니다.
test 가 실패했었던건 script 가 변경되었는데 이게 기존의 통과했던 test 에는 변경되는 내용을 테스트하는 것을 놓쳤던 것 같습니다...(아무래도 파일로 테스트를 돌려서 발생했던것 같습니다. test 폴더 내에 있는 전체를 test 하도록 변경했습니다.)

2024-07-11 16:39 UTC, mlbase reviewed
전체적으로 파일 구조를 도메인 별로 잡아서 파일 변경이 많아진것 처럼 보입니다만 실제로는 피드백 받은 부분만 수정했습니다.

2024-07-11 16:39 UTC, mlbase commented on src/main/java/subway/commons/HttpException.java
> +public class HttpException extends RuntimeException {
시스템적으로 중요할 때 exception 을 띄우기보다는 edge case 들에 대해서 띄우기 때문에 unchecked 바꾸는게 맞는거 같아서 변경했습니다

2024-07-11 16:39 UTC, mlbase commented on src/main/java/subway/line/Line.java
> +
도메인에서 직접 business logic 을 관리하기 위해 연관관계를 추가했습니다. cascade 를 놓쳐서 조금 고생했지만 확실히 코드가 관리하기 편해진 것 같습니다.

2024-07-11 16:39 UTC, mlbase commented on src/main/java/subway/line/Line.java
> +    @OrderColumn(name = "section_order")
추후에 중간 순서에도 구간을 추가할 수 있다는 점을 고려해서 @OrderColumn 을 사용했습니다

2024-07-11 16:39 UTC, mlbase commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @DisplayName("기존의 노선에 구간을 등록한다.")
@DisplayName 지난번에 놓쳤는데 피드백 반영해서 다시 작성했습니다

2024-07-11 23:28 UTC, seondongpyo requested changes
피드백 잘 반영해주셨네요 👍
지하철 구간 관련해서 조금만 더 개선해보면 좋을 것 같아 코멘트 드렸습니다.
확인 후 다시 리뷰 요청 부탁 드릴게요 🔥

2024-07-11 23:28 UTC, seondongpyo commented on src/main/java/subway/line/Line.java
> +    private List<Section>  sections = new ArrayList<>();
`List<Section>`을 일급 컬렉션으로 만들어보면 어떨까요?

2024-07-11 23:28 UTC, seondongpyo commented on src/main/java/subway/commons/ErrorCode.java
> +    CANNOT_REMOVE_LAST_SECTION(HttpStatus.BAD_REQUEST, "마지막 구간은 제거가 불가능 합니다.");
- 에러 메시지에 원인이 되는 값들을 함께 포함해서 출력해보면 어떨까요?
(ex. `IS_NOT_TERMINAL_STATION`의 `지금 제거하는 역`)
- `upStationId` 보다는 조금 더 이해하기 쉬운 단어로 표현해보면 어떨까요?

2024-07-11 23:28 UTC, seondongpyo commented on src/main/java/subway/line/Line.java
> +        if(isExist) {
- `isExist`라는 변수 이름만으로는 위의 주석이 없다면 무엇이 존재하는지 이해하기 어려울 것 같아요
조금 더 구체적인 이름으로 변경해보는 건 어떨까요?
- 전체적으로 코드 포맷팅을 한 번 점검해주시면 좋을 것 같습니다
```suggestion
        if (isExist) {
```

2024-07-12 05:40 UTC, mlbase commented on src/main/java/subway/commons/HttpException.java
> +
field 를 error message 에 추가하기 위해 생성자를 추가했습니다. 처음에는 enum 변경을 시도했었는데 싱글턴 객체라 동시성 요청이 오면 영향이 있을 것 같아서 exception 에 field 추가하는 방향으로 변경했습니다

2024-07-12 05:43 UTC, mlbase commented on src/main/java/subway/commons/ErrorCode.java
> +    DOWN_STATION_NOT_VALID(HttpStatus.BAD_REQUEST, "이미 등록되어 있는 역(id:{0})은 새로운 하행종점역으로 등록할 수 없습니다."),
역 이름을 넘겨주는 것이 가장 좋을것 같기는 한데 Section에서 station 이 일급객체나 entity 가 아닌 id 로 들고 있어서 우선은 id 를 넘기는 방향으로 수정했습니다.

2024-07-12 05:44 UTC, mlbase commented on src/main/java/subway/commons/GlobalExceptionHandler.java
> +    private String fieldFormatting(ErrorCode errorCode, String field) {
exception 에 field 가 주입되었을 때는 formatting 해서 처리하게 됩니다

2024-07-12 05:46 UTC, mlbase commented on src/main/java/subway/line/Sections.java
> +public class Sections {
일급 객체는 많이 사용해봤는데 일급 컬렉션은 처음 사용해보는데 관리하기나 가독성이나 훨씬 좋은것 같습니다.

2024-07-12 05:47 UTC, mlbase commented on src/test/java/subway/SectionAcceptanceTest.java
> +        String errorMessage = MessageFormat.format(ErrorCode.IS_NOT_TERMINAL_STATION.getMessage(), Integer.toString(removingStationId));
에러 메세지 포메팅이 들어가면서 인수테스트에도 포메팅이 들어가게 되었습니다

2024-07-12 11:51 UTC, seondongpyo approved these changes
피드백 잘 반영해주셨네요 👍
몇 가지 코멘트와 함께 이번 미션은 여기서 마무리하겠습니다.
즐거운 주말 되시고 마지막 미션까지 완주하시길 응원하겠습니다 🔥

2024-07-12 11:51 UTC, seondongpyo commented on src/main/java/subway/line/LineController.java
> +    public ResponseEntity<?> deleteLine(@PathVariable Long id) {
`HttpException`이 unchecked exception이라 `throws` 구문을 제거해주셨네요!
위의 `updateLine()`도 챙겨서 `throws` 구문을 제거해주면 좋을 것 같습니다.

2024-07-12 11:51 UTC, seondongpyo commented on src/main/java/subway/line/Sections.java
> +public class Sections {
일급 컬렉션 👍

2024-07-12 11:51 UTC, seondongpyo commented on src/main/java/subway/line/Sections.java
> +        if (lastSection.getDownStationId() != creatingSection.getUpStationId()) {
객체에서 값을 꺼내서 비교하는 대신에, 객체에게 메시지를 보내서 처리해보면 어떨까요?

2024-07-12 11:51 UTC, seondongpyo commented on src/main/java/subway/line/Sections.java
> +        Section lastSection = sections.get(sections.size() - 1);
하행 종점역을 가져오는 로직이 반복적으로 보이는데, 메서드로 분리하여 중복을 제거해보면 어떨까요?

2024-07-12 11:53 UTC, seondongpyo commented on src/test/java/subway/SectionAcceptanceTest.java
> +        ExtractableResponse response = postAPIResponse("/lines/" + testingLineNumber + "/sections", params);
제네릭 타입을 명시해주시면 좋을 것 같습니다.
```suggestion
        ExtractableResponse<Response> response = postAPIResponse("/lines/" + testingLineNumber + "/sections", params);
```

2024-07-12 11:54 UTC, merged