Step2 완료 했습니다!
next-step/atdd-subway-map pull request #1235
Opened 2024-07-17 13:31 UTC by JHyunJung

너무 미션 완료에 기준점을 두고 하지 않은지 걱정되기는 하네요.

미션페이지에 있는 @SQL 같은 것들을 활용하는게 좋을까요?

2024-07-18 10:28 UTC, heoseungyeon requested changes
안녕하세요 재현님!
2단계도 잘 수행해주셨네요. 몇가지 코멘트 남긴 부분 있는데요,
확인 후 다시 PR 요청 부탁드릴게요! 🙇

2024-07-18 10:28 UTC, heoseungyeon commented on src/test/java/subway/LineAcceptanceTest.java
> +        station3 = createStation("양재역");
1,2,3 처럼 변수명을 넘버링 하는 습관은 좋지 않아요, 아래와 같이 변수명에 의미를 담으면 좋을 것 같습니다.
```suggestion
        강남역 = createStation("강남역");
        역삼역 = createStation("역삼역");
        양재역 = createStation("양재역");
```

2024-07-18 10:28 UTC, heoseungyeon commented on src/test/java/subway/StationAcceptanceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
인수 테스트 격리 방법으로 DirtiesContext 어노테이션을 사용해보셨네요! @Sql 을 통해 truncate 명령어를 사용하는 것과 비용 측면에서 무엇이 유리했나요?

2024-07-18 10:28 UTC, heoseungyeon commented on src/test/java/subway/LineAcceptanceTest.java
> +        ExtractableResponse<Response> response = findLine(1L);
`1L`과 같이 DB의 PK 생성 규칙을 알고 id를 예상하고 테스트를 작성하는 것은 테스트의 신뢰성을 낮출 수 있어요. given절에서 id를 받아 when 절에서 수행하도록 하는게 좋은 방법이라고 생각합니다.

2024-07-18 10:28 UTC, heoseungyeon commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
상태코드 검증은 여러 인수테스트에서 자주 사용되니 유틸성 코드로 따로 관리해도 좋을 것 같아요:)

2024-07-18 10:28 UTC, heoseungyeon commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
각 스텝을 메서드로 분리해주셨네요 👍

2024-07-18 10:28 UTC, heoseungyeon commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
응답값에서 검증에 필요한 부분을 추출하는 과정을 메서드로 분리해주셨네요,
조금 더 가독성을 높이기 위해 응답값에서 필요한 부분을 추출하는 과정에 대한 통일성을 고려해보면 좋을 것 같아요.
`jsonPath.getXXX()`로 추출, DTO로 추출, 검증에 필요한 부분을 모두 메서드로 분리(ex)`노선_이름_추출(response)`)
등 여러가지 방법이 있을텐데 여러 방법을 시도해보는 것 추천드립니다!

2024-07-22 12:01 UTC, JHyunJung commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
getNameFromResponse 와 같은 형식을 얘기하시는 걸까요?

2024-07-22 12:04 UTC, JHyunJung commented on src/test/java/subway/StationAcceptanceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
비용측면에서는 @Sql이 DB만 초기화 하면 되니 더 유리했습니다.

2024-07-22 12:18 UTC, heoseungyeon commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
네! 만약 검증해야되는 필드들이 많아지면 응답 json을 DTO로 추출 후 equals 비교를 해보는걸 추천 드려요.

2024-07-22 12:29 UTC, heoseungyeon approved these changes
안녕하세요 재현님! 
피드백 적용 부분 확인했습니다.
나머지 부분은 3단계 진행하면서 보셔도 충분하다고 판단하여 머지하도록 할게요.
마지막 단계도 화이팅입니다🔥🔥

2024-07-22 12:29 UTC, dia312 commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(lines.get(1).getStations().get(1).getId()).isEqualTo(yangjaeStation.getId());
위에 노선 목록의 크기, 이름 검증을 통해 노선 목록 조회에 대한 충분한 검증을 했다고 생각해요. 해당 부분은 삭제해도 무방해보여요

2024-07-22 12:29 UTC, dia312 commented on src/test/java/subway/LineAcceptanceTest.java
> +        createTestLines();
메서드로 추출해보는것도 좋지만 테스트 메서드의 given절에 테스트 픽스쳐 정보가 보이지 않아 오히려 테스트 가독성을 해칠 수 있다고 생각해요. 메서드로 추출하지 않거나 argument로 텍스트 픽스쳐를 보여주면 어떨까요?.?

2024-07-22 12:29 UTC, merged