🐷 : 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #231
Opened 2022-01-24 13:53 UTC by minyul

이슬님! 안녕하세요! 

제가 문제를 풀다가 막바지에 삭제하는 기능에서 놓친 부분이 있다는 것을 알았어요.
'지하철 노선 생성 시 필요한 인자 추가하기' 에서 RequestDto에만 추가를 했지.. 
Entity에는 추가를 하지않았네요. 그래서 삭제하는 기능에서 전부 다 수정을 해야해서 잠시 멈춘 상태입니다.

즉슨, 지금 삭제하는 기능. 조회하는 기능을 하지 못한 상태에서 리뷰를 신청했는데요!

그 이유는 현재 코드가 좀 많이 더럽다는 걸 느껴서요!
그리고 추후에 리뷰를 할 때 너무 많은 양이 있어서 한번 중간정도 미리 리뷰를 하는 것도 나쁘지않다 생각했습니다.

이번에 리뷰에서 제일 궁금했던 것은
`line/{line_id}/section ` 이 path 에 대해서 Controller Service Dao 를 어떻게 짤까 고민을 많이했습니다.

root path가 Line 이라서 LineController 에 section에 대한 기능을 전부 넣어야하는지..
아니면 SectionController 을 따로 만들어야하는지..

![image](https://user-images.githubusercontent.com/86240112/150794764-4a0cf8ea-8da8-4d55-8363-e4c3df6a4a9f.png)

전자 웃고 있는 형태가 이상적이며 뒤에 울고 있는 형태가 제 구조인데...
이게.. 의존성이 너무 sectionService에서 모든 Dao에 의존성을 가져버려서 

결합도가 강하고 복잡해지고 유지보수에 좋아보이지가 않습니다.
이게 과거부터 `line/{line_id}/section` 이 Path로 인해 계속 고민하던 부분이었는데
까먹고 있다가 마침 ATDD에서 나오네요.

`line/{line_id}/section` 
더 나아가 `line/{line_id}/section/{section_id}/temp` 등등.. 
혹시 좋은 방법이 있으신가요?

감사합니다!

2022-01-25 10:06 UTC, parkeeseul requested changes
민율님 많은 고민을 하고 계시군요 👍 
질문 주신 사항에 대한 저의 의견과 코멘트 남겨두었으니 확인 부탁드립니다!
즐거운 저녁 되세요 😄

2022-01-25 12:39 UTC, minyul commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        ExtractableResponse<Response> extract = SectionStep.saveSection(1L, 2L, 10, 1L);
`인수 테스트는 end-to-end 테스트로 내부 구현에 의존하지 않고 구현하는 것이 좋은데요`
감사합니다. 댓글 읽지마자 아차 싶었습니다. 감사합니다! 👍

2022-01-25 12:40 UTC, minyul commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    }
네네 맞습니다! 그래서 CONFLICT 라는 상태코드를 넘겨주고 있는데 혹시 잘못이해하고 있는 것일까요!?

2022-01-25 12:41 UTC, minyul commented on src/main/java/nextstep/subway/ui/path/LinePath.java
> +	public static final String ID = "/{id}";
아 즉슨, LinePath, StationPath, SectionPath 자체를 하나의 클래스안에 넣고 관리하는게 더 좋다는 말씀이시죠!?
굳이 따로 빼지않구요!

2022-01-25 12:43 UTC, minyul commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +	private final static int NUMBER_ZERO = 0;
네넹

2022-01-25 13:16 UTC, parkeeseul commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    }
`새로운 구간의 하행역은 현재 등록되어있는 역일 수 없다` 가 테스트의 목적이라면
새로운 구간의 하행역인 성균관역이 새로운 구간이 생성되기 전에 구간에 등록되어 있어야 할 것 같아요 😄

2022-01-25 13:28 UTC, minyul commented on src/main/java/nextstep/subway/domain/Line.java
>      }
이 부분에 대해서 찾아보니까! 
우선 처음 흐름이 캡슐화를 위해 private를 쓰는 게 이상적이다. 다만, 
Entity를 생성할 때, **Line을 상속한 Proxy**를 불러서 우선 생성을 한다고 하더라구요. ( lazy 지연 호출 일 경우 ! )
껍데기만 우선 갖고 온다는건데.. 이때 **상속**을 했으므로 private 기본생성자를 할 경우 에러를 내뿜기 때문에.

public, protected 를 써야하며 좀 더 내부를 숨기기위해 protected를 써야한다. 
이 결론이 나오는데 맞을까요?

2022-01-26 12:09 UTC, minyul commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +	}
아 저는 이제까지 구현하는 부분에 있어서 public, private 를 따로 나눠서 구현했는데요!
회사에서 맡은 서비스가 계속 부피가 커지다보니 private 메소드를 찾는데 어려움이 있더라구요!
그래서 최근에 이 부분에 대해서 '어떻게 해야할까?' 하는 고민이 있었는데 마침 딱! 해주셔서 
정말 감사합니다!  😤

2022-01-26 12:49 UTC, minyul commented on src/main/java/nextstep/subway/domain/Section.java
> +	private Station downStation;
음 !! 제가 이부분을 몰라서 찾아보고 답변드립니다!
우선 공부해본 결과 CascateType.PERSIST 를 선언할 경우, 연관된 엔티티도 전부 persist(). 즉, DB저장이 아닌 영속성컨텍스트안에 들어가는 걸로 알고잇습니다!

음 결론적으로는 Line Entity에서는 Section 들을 전부 CascadeType.PERSIST 를 해주는 것이 나은 방향이고
Section의 필드 Line , Station 같은 경우 이미 영속성 상태이기에 필요가 없다고 생각합니다.

이게 맞는 결론일까요!? 즉슨!! Line에는 CascadeType.PERSIST를 쓰는게 좋다! Section에는 CascadeType.PERSIST를 전부 안써도된다! 

맞나요!?

2022-01-26 13:15 UTC, minyul commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +	private final static int NUMBER_ZERO = 0;
음.. 이부분 찾아보려했으나 찾지못했습니다. ㅠ-ㅠ 혹시 어떤 부분을 말씀하시는걸까요

2022-01-26 13:18 UTC, minyul commented on src/main/java/nextstep/subway/domain/Section.java
> +	private Station downStation;
음.. 근데 더 생각해보니까 CascadeType.PERSIST 쓰고 안쓰고가 차이가 클까요!? 어떤 이점이 있으며 어떤 불이익이있을까요?

2022-01-26 13:41 UTC, minyul commented on src/main/java/nextstep/subway/README.md
> +- 2022-01-24
처음에 구현을 했을 당시에는 최대한 역할을 나눠야한다는 생각에 '당연히' 나눠야한다라는 느낌이 있었는데
구현하면서 굳이 그럴필요가 없다고 느꼈고 이슬님 의견처럼 SectionService 또한 필요가 없다고 느껴서 혼동이 있었습니다. 
Line이 존재해야 Section을 생성할 수 있다는 말에 매우 공감하는 바입니다! 감사합니다 😄😄😄

2022-01-26 16:07 UTC, parkeeseul commented on src/main/java/nextstep/subway/ui/path/LinePath.java
> +	public static final String ID = "/{id}";
뭐가 좋다라고 이야기 하려했다기 보다는 민율님이 어떠한 생각으로 나눠주셨는지 궁금해서 질문을 드려보았습니다 😄 
개인적으로는 해당 상수들의 클래스를 따로 분리하지 않고 사용하는 클래스 내에 위치하도록 하는 것이
조금 더 응집도가 있을 것 같다는 생각도 되네요 😄

2022-01-26 16:09 UTC, parkeeseul commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +	private final static int NUMBER_ZERO = 0;
Number.ZERO 라는 네이밍으로 보았을 때는 단순히 0이라는 값을 나타내게 되는데요
반면 Number.MIN 이라는 네이밍은 Number 의 최소값을 나타내는 의미를 가지게 됩니다.
상수화를 통해 값이 어떠한 의미를 가지는지를 표현할 수 있는데요,
단순히 값을 나타내기 보다는 의미를 나타내는 네이밍을 해보면 어떨까요? 😄

2022-01-26 17:12 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/Section.java
> +	private Station downStation;
persist 를 하게 되면 디비에 바로 저장되지는 않고 1차캐시에 엔티티를 저장해 엔티티를 영속 상태로 만들지만
transaction 이 종료되기 전에 flush 를 호출해 persist 된 entity 들의 변경사항을 디비에 반영하게 됩니다.

Section 이 영속화 될때 Line 또한 영속화를 하게 되면 
Section 을 persis 할때 Line에 persis 되면서 Section 을 통해 Line 이 변경될 수 있을 것 같은데, 이는 의도하신 부분이 맞으실까요?
Section 은 Line 에 포함된다(?) 라고 볼 수 있을 것 같은데 Section통 통해 Line 이 변경이 일어나는 것은 문맥상 어색하다고 생각합니다 😄

2022-01-27 15:55 UTC, minyul commented on src/main/java/nextstep/subway/domain/Section.java
> +	private Station downStation;
와.. 진짜 너무 감사합니다! 짱짱 사전에 변경될 만한 부분을 방지하는 거군요! 감사합니다!

2022-01-28 10:46 UTC, parkeeseul requested changes
피드백 잘 반영해주셨네요! 👍 
추가 코멘트 남겨두었으니 확인 부탁드립니다 😄 
즐거운 연휴가 시작되네요! 미션 화이팅 입니다 🔥

2022-01-28 10:53 UTC, minyul commented on src/main/java/nextstep/subway/ui/path/SubwayPath.java
> +}
아아 맞습니다. 이 부분을 놓쳤네요! 응집도가 있다는 것에 공감합니다! 감사합니다!

2022-01-28 12:52 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/Entity/Line.java
> +
끝점을 알아야할 이유는 무엇일까요? 🤔 
요구사항에 따라 양 끝점을 알아야 할 수는 있겠지만
지금의 미션으로는 굳이 알아야 할 필요성이 있을까 하는 생각이 드네요 😄

2022-01-28 12:55 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요!
말씀주신 부분에 추가로 저의 의견 남겨두었으니 확인 부탁드리고
이번 미션 이만 머지하도록 하겠습니다 😄 
그 동안 많은 피드백 반영해주시느라 정말 고생 많으셨습니다.
남은 미션도 꼭 완주하셔서 많은 인사이트 얻어가시길 바라요!
마지막까지 화이팅 입니다! 🔥

2022-01-28 12:55 UTC, merged

2022-01-28 15:46 UTC, minyul commented on src/main/java/nextstep/subway/domain/Entity/Line.java
> +
아아 현시점에서 .... 🤔 미션은 완주했지만 복습하면서 한번 다시한번 고민해봐야겠습니다!

이슬님!! 정말 감사했습니다! 존경합니다!