[2단계 - 인수 테스트 리팩터링] 리뷰 부탁드립니다.
next-step/atdd-subway-map pull request #234
Opened 2022-01-24 17:16 UTC by kwj1270

안녕하세요 리뷰어님 우선 저번 리뷰 감사드립니다 :) 

# 저번 PR에서 궁금했던점(3번) 
우선, 저번에 3번 질문에 대해서 제가 명확히 말씀을 못드린 것 같습니다.(죄송합니다.)  
 
![image](https://user-images.githubusercontent.com/50267433/150830317-0c385f5e-9117-4027-92d6-be87198568a1.png)

* Response의 값으로 위 그림과 같이 여러 데이터들이 담겨있습니다.   
* id/name/color 에 대해서는 제 테스트 코드를 보면 알 수 있듯이 테스트가 가능했습니다.   

![image](https://user-images.githubusercontent.com/50267433/150830661-ce4f14f3-0e38-47c5-8218-a1bf0c80d521.png)

* createdDate와 modifiedDate에 대해서는 `jsonPath()`를 사용한 후 사용할 메서드가 애매합니다.  
* `get("createdDate")`을 사용한다해도 얻게 되는 문자열이 `생성 시간값`이기 때문에 이를 명확히 측정하기 힘들었습니다. 

![image](https://user-images.githubusercontent.com/50267433/150831023-0d6fb081-462c-4efe-acc3-c08c96cfb791.png)

* `assertThat()`의 `isBlank()`를 사용하기 위해 뒤에서 자동완성을 사용해도 관련 메서드들이 없더라고요   

그래서 위와 같이 시간을 측정할 방법이 마땅히 떠오르지 않아서 어떻게 해야할지 난감해했었습니다.   
테스트를 하지 않고 넘어간다면 `createdDate` 값이 안 들어오는 상황에서 검증을 못

2022-01-25 08:45 UTC, kang-hyungu commented
line 객체를 테스트할 때 왜 생성시간과 수정시간을 검증하시나요?
두 값을 테스트해서 어떤 걸 확인하고 싶으신건가요?
무조건 모든 값을 테스트하지 마세요.
이 테스트가 어떤 의미가 있는지, 변경사항이 생겼을 때 생길 수 있는 문제를 체크할 수 있는지 같은 이유가 있어야 합니다.
테스트 코드도 유지보수하고 리팩터링이 필요합니다.
불필요하게 코드량을 늘리지 마세요.

2022-01-25 08:57 UTC, kang-hyungu requested changes
우재님 몇 가지 피드백 남겼습니다.
질문주신 내용도 답변 남겼으니 참고하세요.
수정해보시고 리뷰 재요청주시기 바랍니다.

2022-01-25 08:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        if (Strings.isBlank(lineName)) {
이 유효성 검사는 서비스 클래스에서 할 필요가 없겠네요.
repository가 필요한 유효성 검사는 제외하고 다른 검사는 line 객체 내부에서 처리하도록 바꿔보아요.
validateLineColor도 마찬가지입니다.

2022-01-25 08:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        if (Strings.isBlank(lineName)) {
다른 클래스에서도 비슷한 패턴이 보이네요.
같이 점검해보시기 바랍니다.

2022-01-25 08:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/line/LineBlankColorException.java
> +public class LineBlankColorException extends LineBusinessException {
모든 유효성 검사마다 예외 클래스를 만들게 되면 관리해야될 클래스가 너무 많아지지 않을까요?

2022-01-25 08:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/line/LineErrorCode.java
> +public enum LineErrorCode implements ErrorCode {
비즈니스 로직이 발전하면서 다양한 예외 조건이 생길텐데 이 enum 클래스가 너무 비대해지겠네요.
각 예외 클래스가 필요한 상태 코드와 메시지를 가지고 있는데 enum으로 다시 뽑아내는 이유가 무엇인가요?

2022-01-25 08:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/station/StationControllerAdvice.java
> +public class StationControllerAdvice {
도메인 단위로 예외를 관리해야 하는 이유가 있나요?
이 클래스랑 LineControllerAdvice랑 처리하는게 큰 차이가 없어 보이는데 왜 분리해야 하나요?

2022-01-25 08:57 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/station/StationErrorCode.java
> +public enum StationErrorCode implements ErrorCode {
LineErrorCode랑 어떤 점이 다른건가요??

2022-01-25 08:57 UTC, kang-hyungu commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        final ExtractableResponse<Response> response = RestAssured.given().log().all()
인수테스트가 늘어날 수록 RestAssure를 사용한 http 호출이 반복적으로 나타나겠네요
중복을 제거할 방법이 없을까요?

2022-01-25 09:04 UTC, kwj1270 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        if (Strings.isBlank(lineName)) {
이 점도, 서비스에서 검증을 하는것이 좋은지 내부에서 검증하는 것이 좋은지 잘 판단이 서지 않아서 애매했습니다.  

지금 다시 생각해보면 아래와 같이 생각해볼 수 있을 것 같네요 
* 중복과 관련된 검증: Repository를 활용해야하므로 서비스 레이어에서의 검증이 필요
* 공백이나 널값과 관련된 검증: 
    * 서비스에서 할 경우, 해당 엔티티를 다른 서비스에서 활용할 경우 또 예외처리 로직을 구현해야함
    * 도메인 내부로 옮겨서 위와 같은 문제를 해결하는 것이 더 나은 방법

2022-01-25 09:20 UTC, kwj1270 commented on src/main/java/nextstep/subway/exception/line/LineBlankColorException.java
> +public class LineBlankColorException extends LineBusinessException {
네 리뷰어님의 의견에 동의합니다.   
말씀대로 예외클래스를 만들게 되면 관리해야될 대상이 많아진다고 생각하고  
저 자신도 "기존에 잘 만들어진 클래스를 사용하자!" 는 주의이긴 합니다.   
 
일단 이번 미션만 놓고 보았을 때 예외처리 개수가 적어   
예외 클래스를 만들어도 괜찮을 것 같다는 생각으로 만들긴 했습니다.

2022-01-25 11:05 UTC, kwj1270 commented on src/main/java/nextstep/subway/exception/line/LineErrorCode.java
> +public enum LineErrorCode implements ErrorCode {
# Enum으로 뽑은 이유 

Advice 클래스를 보시면 아시다시피, 하나의 `@ExceptionHandler`로 예외처리 로직을 하고 있습니다.   
Enum을 사용했을 때, 열거형만 추가하면 Advice의 메서드를 추가적으로 구현하지 않을 수 있을 것 같다는 생각이 들었습니다.

# Enum에서도 메시지를 사용하는 이유 
예외 클래스에서 메시지를 가지고 있는데   
Enum에서도 메시지를 가진 이유는 아래와 같습니다.  
 
일전에 로그인과 관련된 예외처리에 대해서     
보안상의 이유로 `아이디가 틀렸습니다`, `비밀번호가 틀렸습니다`와 같은 메시지 대신   
`사용자 정보가 틀렸습니다`와 같은 추상적인 메시지를 던진다고 들었습니다.   
  
이때 제가 고민했었던 부분은     
개발자가 확인하는 `로깅` 부분에 있어서는 에러를 명확히 아는 것이 좋지않을까? 생각했고  
클라이언에게 보내는 `에러 메시지` 부분에 있어서는 추상적인 메시지를 던지는게 좋지않을까? 라고  생각을 했습니다.   

```java
        log.error("LineBusinessException: {}", lineBusinessException.getMessage());
``` 

그래서 커스텀 Exception에서 message는 로깅용 메시지    
Enum에서의 message 는 ErrorResponse에서 사용할 목적의 메시지로 만들었습니다.

2022-01-25 11:08 UTC, kwj1270 commented on src/main/java/nextstep/subway/exception/station/StationControllerAdvice.java
> +public class StationControllerAdvice {
Advice를 공부를 했을 때, 대부분의 예제에서는 GlobalAdvice로 처리를 하는 구조였습니다.   
하지만, Global로 처리를 했을 때, 도메인이 많으면 GlobalAdvice 크기도 점점 커지게 될 것이고
나중에는 이를 또 분리해야하는 상황이 올것이라는 생각이 들었습니다.    

그래서 코드를 구현할 때, 항상 도메인 단위로 나누어서 진행을 하자는 생각이었고   
이번에도 오버프로그래밍으로 굳이 현재 분리하지 않아도 되는데 분리를 한 것 같습니다.

2022-01-25 11:10 UTC, kwj1270 commented on src/main/java/nextstep/subway/exception/station/StationErrorCode.java
> +public enum StationErrorCode implements ErrorCode {
앞서 리뷰해주셨던 내용처럼 Global하게 Enum을 사용하면 쉽게 비대해질 것이라 생각했습니다.  
그래서 이거를 도메인별로 분리 + 비대해지는 것을 막기위해 각각의 도메인마다 ErrorCode를 만드는 방식으로 진행했습니다.

2022-01-25 11:13 UTC, kwj1270 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        final ExtractableResponse<Response> response = RestAssured.given().log().all()
이번 http 호출의 경우 모든 코드에서 1번 밖에 사용하지 않아서  
지금 당장의 메서드 분리는 필요없을 것 같다는 생각에 따로 분리하지는 않았습니다.   
(이전 PR에서는 질문 드렸던것 처럼 업데이트 검증을 위해 추가로 한번 더 조회해서 분리했는데
이 부분을 피드백 받고 리팩토링하니 1번 밖에 호출하지 않아서 다시 원상복구 시켰습니다.)

2022-01-25 11:40 UTC, kwj1270 commented on src/main/java/nextstep/subway/exception/line/LineBlankColorException.java
> +public class LineBlankColorException extends LineBusinessException {
[테코블 커스텀 예외처리](https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/)   
  
리뷰어님의 말씀을 듣고 무조건적인 Custom Exception이 좋은가 생각이 들었고  
테코코스 블로그에서 조금이나마 해답을 얻은 것 같습니다.   
상황마다 다르긴 하지만, 저 같은 충분히 기존 예외클래스로도 가능하지만, 단순히 무지성으로 작성을 했다고 반성되네요

2022-01-25 13:55 UTC, kwj1270 commented
안녕하세요 리뷰어님. 그리고 정말 죄송합니다....
 
리뷰를 받고나서 제 코딩하는 습관에 대해서 곰곰히 생각을 해보았습니다.      ​  
일어나지 않은 일에 대해서 오버 프로그래밍이 많았고 (도메인 분리, Enum, CQRS) 
그냥 자주 사용하니까 적용한 방식도 몇몇 있었습니다. (Custom Exception)      
결과적으로 관리 포인트만 많아지게하는 안 좋은 습관이라는 것을 깨달았습니다.   

아직 모르는게 많고 많이 부족합니다.   
다만, 이번 과정을 통해 스스로의 개발 모습과 습관에 대해서 의식적으로 생각하고    
앞으로 계속 발전되는 모습을 보여드릴 수 있도록 노력해보겠습니다.     
 
그리고 리뷰해주셔서 정말 감사드립니다.

2022-01-26 08:52 UTC, kang-hyungu approved these changes
우재님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리할게요. 추가로 남긴 코멘트는 다음 미션 진행하면서 적용해주세요.
수고하셨습니다.

2022-01-26 08:52 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/ExceptionAdvice.java
> +        return ResponseEntity.status(HttpStatus.CONFLICT).body(new ErrorResponse(errorMessage));
http status 409로 반환하는게 적절할까요?
409 코드는 어떤 의미를 가지고 있을까요?

2022-01-26 08:52 UTC, merged