Step2
next-step/atdd-subway-map pull request #242
Opened 2022-01-25 14:25 UTC by lehdqlsl

안녕하세요. 리뷰어님! 잘부탁드립니다.

Exception 처리에 대해 정답이 있을까요. 실무에서 적당선을 지키기가 어렵네요. 

CustomException 클래스와 에러코드 및 에러메시지가 담겨있는 Enum 클래스 등을 만들어서
보다 자세하고 구체적인 예외처리 및 응답을 해야하는지,
아니면 라이브러리에서 발생한  runtime 예외만 적당히 핸들링해서 응답해야하는지...

방법은 참 많은데 정답이 어려워서 여럽네요.

리뷰어님 생각이 궁금합니다.

2022-01-26 08:46 UTC, kang-hyungu commented
> 안녕하세요. 리뷰어님! 잘부탁드립니다.
> 
> Exception 처리에 대해 정답이 있을까요. 실무에서 적당선을 지키기가 어렵네요.
> 
> CustomException 클래스와 에러코드 및 에러메시지가 담겨있는 Enum 클래스 등을 만들어서 보다 자세하고 구체적인 예외처리 및 응답을 해야하는지, 아니면 라이브러리에서 발생한 runtime 예외만 적당히 핸들링해서 응답해야하는지...
> 
> 방법은 참 많은데 정답이 어려워서 여럽네요.
> 
> 리뷰어님 생각이 궁금합니다.

클라이언트에게 어떤 정보를 담아줘야할지 상황에 따라 다르겠네요.
회사 내부에서 통신할 때 사용하는 API라면 구체적인 에러 메시지를 반환해도 문제 없겠지만 일반 사용자들에게 예외 메시지가 그대로 노출되는 API라면 정제해서 내려줘야겠죠.

2022-01-26 08:46 UTC, kang-hyungu requested changes
동빈님 몇 가지 피드백 남겼습니다.
수정해보시고 리뷰 재요청주세요.

2022-01-26 08:46 UTC, kang-hyungu commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        } catch (Exception e) {
try catch 대신에 db에서 동일한 이름이 있는지 조회해보는게 어떨까요?
Expcetion으로 받게 되면 DuplicationException이 아닌 에러 상황도 DuplicationException으로 처리하게 됩니다.

2022-01-26 08:46 UTC, kang-hyungu commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +                .orElseThrow(() -> new IllegalArgumentException());
IllegalArgumentException 이 예외가 적절한가요?
argument를 잘못 입력한 경우에만 예외가 발생할까요?
id를 디비에서 찾지 못한 경우에는 IllegalArgumentException가 아닌 다른 예외를 써야 하지 않을까요?

2022-01-26 08:46 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/ControllerAdvisor.java
> +        return new ResponseEntity<>(exceptionResponse, HttpStatus.CONFLICT);
중복된 네이밍인 경우에 http status 409가 적합한가요?
409는 어떤 상태를 의미할까요?

2022-01-26 08:46 UTC, kang-hyungu commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        ExtractableResponse<Response> response2 = 지하철노선_조회(stationId);
클린코드 25p

의미 있게 구분하라
컴파일러나 인터프리터만 통과하려는 생각으로 코드를 구현하는 프로그래머는 스스로 문제를 일으킨다.
예를 들어, 동일한 범위 안에서 다른 두 개념에 같은 이름을 사용하지 못한다.
...

컴파일러를 통과할지라도 연속된 숫자를 덧붙이거나 불용어(noise word)를 추가하는 방식은 적절하지 못하다.
이름이 달라야 한다면 의미도 달라져야 한다.

연속적인 숫자를 덧붙인 이름(a1, a2 ... aN)은 의도적인 이름과 정반대다.
이런 이름은 그릇된 정보를 제공하는 이름도 아니며, 아무런 정보를 제공하지 못하는 이름일 뿐이다.
저자 의도가 전혀 드러나지 않는다.

2022-01-26 13:19 UTC, lehdqlsl commented on src/main/java/nextstep/subway/exception/ControllerAdvisor.java
> +        return new ResponseEntity<>(exceptionResponse, HttpStatus.CONFLICT);
기존 리소스와 충돌한다는 의미로 사용했는데, 400이 더 적절할 것 같습니다.

2022-01-26 13:19 UTC, lehdqlsl commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        ExtractableResponse<Response> response2 = 지하철노선_조회(stationId);
죄송합니다.. 명심할게요!!

2022-01-26 13:21 UTC, lehdqlsl commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +                .orElseThrow(() -> new IllegalArgumentException());
피드백 감사합니다. 별도의 Exception을 작성하여 처리하도록 하겠습니다.

2022-01-27 08:48 UTC, kang-hyungu approved these changes
동빈님 피드백 반영 잘 하셨어요.
추가로 남긴 피드백은 다음 미션 진행하면서 적용해보시기 바랍니다.
pr은 머지 처리하겠습니다. 수고하셨습니다.

2022-01-27 08:48 UTC, kang-hyungu commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        return lineRepository.findByName(name).isPresent();
spring data가 제공하는 method query를 사용하시면 메서드명을 exist를 사용해보시기 바랍니다.

2022-01-27 08:48 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/LogicError.java
> +    public String getErrMsg() {
메서드명에 축약어를 사용하지 않는게 좋습니다.

2022-01-27 08:48 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/ControllerAdvisor.java
> +        return new ResponseEntity<>(exception.getLogicError().getErrMsg(), HttpStatus.BAD_REQUEST);
LogicError를 보니 NOT_EXIST_LINE 라는 enum 값이 있는데 이 경우에는 BAD_REQUEST가 적절할까요?

2022-01-27 08:48 UTC, merged