Step3 리뷰 요청드립니다
next-step/atdd-subway-map pull request #263
Opened 2022-01-27 01:56 UTC by kimuno89

2022-01-27 16:01 UTC, dbeod2 requested changes
안녕하세요! 윤호님 :) 

3단계 미션 잘 진행해주신 것 같아요! 💯💯💯
테스트가 실패하고 있는게 있어서 코멘트 달아두었습니다. 🙏

고민해보시면 좋을 것 같아서 코멘트 달아두었는데 확인 부탁드립니다.
확인해보시고 리뷰 재요청 주세요 🔥🔥🔥

2022-01-28 01:40 UTC, kimuno89 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +    public void createSection(Long id, SectionRequest sectionRequest) {
LineController, StationController 수정했습니다!

2022-01-28 05:22 UTC, kimuno89 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
>          ExtractableResponse<Response> response = RestAssured.given().log().all()
구간이 하나도 없으면 발생하는 에러였습니다.
수정했습니다!

2022-01-28 05:43 UTC, kimuno89 commented on src/main/java/nextstep/subway/ui/LineController.java
> +    public ResponseEntity<Void> saveSection(@PathVariable Long id, @RequestBody SectionRequest sectionRequest) {
Line 도메인의 addSection을 테스트 하는 코드를 작성했습니다.

2022-01-28 13:54 UTC, kimuno89 commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
넵 확인했습니다!

2022-01-28 13:56 UTC, kimuno89 commented on src/test/java/nextstep/subway/domain/LineTest.java
> +        assertThat(allStations.size()).isEqualTo(3);
적용했습니다

2022-01-28 14:10 UTC, kimuno89 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +            line.getAllStations()
LineWithResponse를 삭제하고 LineResponse를 사용하도록 변경했습니다.

2022-01-28 14:11 UTC, kimuno89 commented on src/main/java/nextstep/subway/applicaion/LineService.java
>  import nextstep.subway.applicaion.dto.LineWithStationResponse;
LineWithResponse 제거했습니다!

2022-01-28 14:32 UTC, kimuno89 commented on src/main/java/nextstep/subway/applicaion/LineService.java
>              throw new IllegalArgumentException("이미 존재하는 노선입니다.");
CustomException을 사용하도록 변경했습니다.

잘 작성한지 모르겠습니다.. 저랑 의견이 다르다면 말씀해주세요!

2022-01-29 03:27 UTC, dbeod2 requested changes
안녕하세요! 윤호님 :) 

피드백 반영 빠르게 해주셨네요! 💯 💯 💯
추가로 고민해보면 좋을 것 같은 부분들 코멘트 몇개 남겨두었는데 확인 부탁드려요!🙏
리뷰 재요청 기다리고 있겠습니다 😄

2022-01-29 03:27 UTC, dbeod2 commented on src/main/java/nextstep/subway/domain/Line.java
> +    }
List<StationResponse>로 리턴을 해주시고 계시네요! LineResponse로 넘겨주고있네요! 
지금 처럼 entity에 dto가 종속하게 되는데요.
둘 중 하나가 바뀌어도 서로를 수정해야 합니다.🥲

List<Station>으로 리턴해서 LineResponse내에서 가공을 해주는게 맞을 것 같은데 어떻게 생각하시나요? 🤔

2022-01-30 09:21 UTC, kimuno89 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
>          assertThat(response.statusCode()).isEqualTo(HttpStatus.NO_CONTENT.value());
AcceptanceTest에 메소드를 만들어서 해결했습니다

2022-01-30 10:26 UTC, kimuno89 commented on src/main/java/nextstep/subway/exception/DeleteSectionException.java
> +public class DeleteSectionException extends RuntimeException {
ControllerExceptionHandler 추가했습니다.
해당 부분은 internalServerError 묶어서 처리가 충분히 가능할 것 같아서 묶어놨는데
좀 더 디테일하게 분리가 필요하거나 다른 의견이 있으시다면 알려주시면 감사하겠습니다

2022-01-31 00:36 UTC, dbeod2 approved these changes
안녕하세요! 윤호님

피드백 반영 빠르게 해주셨네요! 
그동안 피드백 반영해 주시느라 정말 고생 많으셨습니다 🙏

이번미션은 여기서 머지하겠습니다

남은 미션들도 잘 해내실거에요💪🏻
화이팅입니다!

2022-01-31 00:36 UTC, dbeod2 commented on src/test/java/nextstep/subway/domain/LineTest.java
> +        Station 강남역 = new Station("강남역");
👍🏻

2022-01-31 00:36 UTC, dbeod2 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        요청_응답을_확인한다(response, HttpStatus.CREATED);
피드백 반영💯💯

2022-01-31 00:37 UTC, merged