1주차 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #275
Opened 2022-01-28 19:08 UTC by zeroooooowest

안녕하세요~
JPA 경험이 부족한 거 같아 따로 추가적으로 학습하면서  조금 늦었습니다😭

지난번 풀리퀘스트에서 [등록된 구간을 통해 역 목록 조회 기능](https://github.com/next-step/atdd-subway-map/pull/227) 리뷰해주신 부분을 반영하여 처음 커밋에서 리팩토링을 진행해보았습니다.

https://github.com/next-step/atdd-subway-map/pull/227#discussion_r790354426
여기서 말씀주신 then도 하나의 step으로 볼수 있지 않을까라고 해주셨는데
then은 약간 검증의 느낌이라 생각해서 Test클래스 내에 존재해야 하지 않을까 싶어서 검증이 여러개면(여러줄이면) 따로 메서드로 분리하는 식으로 해보았습니다.

그리고는 나름대로 3단계 미션을 구현해보았는데 중복 테스트코드를 줄인다고 줄였는데도 더 줄일 수 있지 않나 생각이 들기도 하네요.
main코드에서는 노선을 생성하면서 구간도 같이 생성하다 보니 jpa 양방향 관계에 대해 조금 고민해서 생성했는데 잘 짜여졌는지 궁금하기도 합니다.

리뷰 잘 부탁드립니다🙏

2022-01-29 04:44 UTC, ivvve requested changes
영서님 안녕하세요!
늦게 까지 미션 수행하시느라 고생이 많으십니다 🔥 

기능적인 구현 및 각 시나리오에 대해서 인수테스트 코드를 잘짜주셨습니다 👍 
다만 인수 테스트에서 시나리오에 대한 표현력을 좀 더 높일 수 있지 않을까라는 생각이 듭니다. 🤔 

관련해서 코멘트 남겼는데 보시고 추가적인 컨텍스트나 설명이 필요한 부분,
혹은 의견이 다른 부분이 있으시면 편하게 댓글이나 DM 주세요 :)

2022-01-29 04:44 UTC, ivvve commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        var station1 = StationFixture.신논현역;
테스트는 흠잡을데 없이 잘 짜셨다고 생각합니다 👍 

다만 우리가 하고자하는 것은 `인수테스트`이기 때문에 주석에 적어주신 각 스텝들을 테스트 코드에 최대한 녹여보시는 시도를 하셔도 좋을 것 같아요 :)
(주석이 전혀 필요 없을 정도로)

지금의 시나리오를 기반으로 인수 테스트를 작성한다면 저는 아래와 같이 짤 것 같습니다.

```java
@Test
void 중복_이름으로_지하철_노선_생성() {
    // given
    지하철_노선이_생성되어있다("경춘선"); // 주어진 조건(given)을 표현하기 위해 과거형으로 표현했습니다

    // when
    var 지하철_노선_생성_응답 = 지하철_노선_생성_요청을_한다("경춘선"); // 각 스텝을 문장으로 표현하여 시나리오에 대한 표현력을 높이도록 했습니다

    // then
    지하철_노선_생성이_실패한다(지하철_노선_생성_응답);
}
```

물론 지금도 문제가 있는건 아니고 위에 예시 코드도 절대적인 답은 아닙니다!
다만 인수 테스트는 단순히 API를 테스트함이 아니고 인수 조건에 대한 시나리오를 표현하기 위해 작성되기 때문에
인수테스트 시나리오를 표현하는 구성에 대해서도 충분히 고려하시면 풍부하고 읽기 좋게 시나리오를 표현할 수 있을 것 같습니다 :)

2022-01-29 04:44 UTC, ivvve commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        StationStep.역_생성_요청(station1);
static import를 사용하면 클래스 명이 드러나지 않으니
시나리오를 표현하는 인수 테스트 특성 상 가독성에 조금 더 도움을 줄 것 같습니다 :)

2022-01-29 04:44 UTC, ivvve commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        Line savedLine = lineRepository.save(line);
여기서는 var를 사용하지 않으셨는데
코드의 일관성을 지켜주시면 더 좋을 것 같습니다 :)

2022-01-29 04:44 UTC, ivvve commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        line.getSections().add(section);
Line을 통해서 구간을 추가하신 것이 아니라
Line 내부의 `List<Section>` 값에 직접 접근하여 구간을 추가하셨는데요.
Line을 통해 구간을 추가하도록 변경하시는건 어떨까 싶습니다 :)
(Line 클래스를 보니 addSection이 있긴 하네요 :eyes:)

현재는 기능 상으로는 문제는 없겠으나 유지보수에 있어 큰 문제를 초래할 수 있습니다.

1.
만약 내부 구현을 변경하게되서 Line에서 `List`를 사용하지 않고 다른 방식으로 구간을 저장하게된다면,
그 여파가 Service에도 미치게 됩니다.

2.
Line 도메인 객체에 대한 표현력이 떨어집니다.
Line은 단지 Section에 대한 data를 들고 있는 역할 뿐이고
외부에서 자신의 Section이 추가가 되길 바랄 뿐입니다.

3.
Line의 Section에 대한 정보가 캡슐화가 되어있지 않아 외부에서 쉽게 변경가능합니다.
예를 들어 `line.getSections().clear();`와 같은 치명적인 코드도 외부에서 쉽게 호출이 가능합니다.

2022-01-29 04:44 UTC, ivvve commented on src/main/java/nextstep/subway/domain/Line.java
> +    }
외부에서 내부의 `List<Section>`에 영향을 줄 수 없도록 
Collections.unmodifiablelist 등으로 처리를 해주시면 좋을 것 같아요 :)

2022-01-29 04:44 UTC, ivvve commented on src/main/java/nextstep/subway/domain/Line.java
> +    }
핵심 로직을 도메인 내부에 두셔서 기능에 대한 응집도가 많이 올라갔네요 :+1: 
추가로 각 로직을 메서드로 추상화하셔서 로직에 대한 큰 흐름을 이해하기도 편한 것 같습니다 :100:

2022-01-30 06:34 UTC, zeroooooowest commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        line.getSections().add(section);
처음 구간과 섹션을 동시 생성할 때에는, addSection 메서드를 호출하면 추가할수 있는지 검증하는 부분이 예외가 발생하다보니

이거를 양방향 관계만 어떻게 잘 저장할까 생각하다가 놓쳤습니다😭

init(Section section) 메서드를 추가해서 서비스에서 호출하는 식으로 고쳐보았습니다

2022-01-30 10:36 UTC, ivvve approved these changes
안녕하세요 영서님!

첫번째 미션 수행하시느라 고생 많으셨습니다! 👍 
테스트 뿐만 아니라 내부 구현도 충분히 고민하시고 구현하신것 같아요 😎 

미션 진행하시면서 어떠셨을까요?
첫 미션을 통해 ATDD는 어떤 것이고 인수 테스트를 어떻게 짜야할지에 대해
충분히 감을 잡고 몸으로 익히는 시간이 되셨다면 좋겠습니다 :)

제가 미션을 진행하면서 여러 코멘트를 드렸고 예제로도 설명드리긴 했으나
사실 각자의 생각은 다를 수 밖에 없는 부분입니다 :)
본인이 만족할 수 있는 인수테스트를 작성할 때까지 여러번 시도해보시고,
또한 다른 분들의 미션 코드도 살펴보는걸 추천합니다!

앞으로 남은 과정과 미션도 화이팅입니다 🔥 🔥

2022-01-30 10:36 UTC, ivvve commented on src/test/java/nextstep/subway/acceptance/step/LineStep.java
> +        assertThat(stations.size()).isEqualTo(2);
`노선_조회_완료`라는 step 내부에 암묵적으로 `역이 2개 등록된` 노선이라는 정보가 숨어있는데요.
만약에 역의 수가 2개가 아닌 다른 노선에 대해서도 **노선 조회 완료 스텝**을 표현해야할 경우,
어떻게 변경하면 좋을지도 생각해보시면 좋을 것 같습니다 :)

2022-01-30 10:36 UTC, ivvve commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        section.setLine(line);
`Line#addSection`에서 동일한 기능을 호출하고 있네요 😅

2022-01-30 10:36 UTC, ivvve commented on src/main/java/nextstep/subway/domain/Line.java
> +        section.setLine(this);
서비스 레이어와 같은 도메인 외부에서 양방향으로 매핑하기보다는
이렇게 도메인 내에서 매핑 해주는 방식이 더 깔끔하다고 생각합니다! 👍

2022-01-30 10:36 UTC, ivvve commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +                        .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 지하철 역 id: " + requestUpStationId)),
동일한 message 코드가 반복되는데 custom exception을 만들어서 이 메세지를 한 곳에서 관리하여도 좋을 것 같습니다 :)

2022-01-30 10:36 UTC, ivvve commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<Section> sections = new ArrayList<>();
`노선`의 `구간`은 꽤나 까다로운 요구사항을 갖고있는데요.
`노선의 구간 목록`에 대한 응집성을 한 곳으로 모으기 위해 `List<Section>`을 감싼 일급 컬렉션을 사용해보시는 것도 고려할만 합니다 🤔

2022-01-30 10:36 UTC, ivvve commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        노선_생성_완료(노선_생성_응답);
저는 변경하신 코드가 구체적인 코드 없이 명확하게 시나리오의 각 단계에 대해 잘 드러낸다고 생각하는데요.
영서님은 어떠신가요? 🤓

이전 코멘트에서 지금과 같은 코드를 작성해보는걸 권해드리긴 했으나,
결과적으로 어떤 방식으로 인수테스트를 작성할 것인가는 영서님의 결정이긴 합니다 :)

이번 과정을 통해서 단순히 미션을 해나가기 보다도, 여러 방식을 시도해보시면서 영서님 나름의 인수테스트 방법론을 정립해나가시길 바랍니다 :)

2022-01-30 10:37 UTC, merged