Step3
next-step/atdd-subway-map pull request #278
Opened 2022-01-29 18:36 UTC by gashe-soo

안녕하세요 희선님 
리뷰요청드립니다. 

3단계가 좀 늦었네요. 
평소에는 단위 테스트 TDD를 선호하는데, 
이번 미션에서는 ATDD가 API단에서 진행하다보니 굉장히 변화 범위가 커지니 불안하더군요. 
그래도 다음 미션은 단위테스트를 적용하면서 진행해봐야겠네요.

고민한 부분
- 어떻게 하면 도메인에 로직을 옮길 수 있는지를 고민하면서 작성했습니다. 최대한 getter, setter를 안 쓰고 싶었는데, 일부는 아쉽네요. 
- sections를 일급컬렉션으로 옮기고 싶었는데, 변명 아닌 변명을 해보자면 JPA에 무지하다보니 쉽게 적용이 안되네요. 
이후 공부하면서 차차 적용해보겠습니다.
- 패키지 구조가 눈에 잘 안 들어오네요. 도메인별로 나누는 걸 선호하는데,  그럴 때 조심해야 할 점이 있을까요? (ex. 순환참조)

2022-01-30 11:57 UTC, heesunjeong requested changes
3단계 구현도 깔끔하게 잘 해주셨네요 💯 💯 
단위테스트의 필요성을 벌써 느끼셨군요 👍  2주차 미션부터 인수테스트와 함께 단위테스트를 작성하며 구현하는 경험도 해보실 수 있답니다~! :)
질문해주신 점과 참고해보시면 좋을 것 같은 부분에 대해서 코멘트를 추가했으니 확인 부탁드려요!

2022-01-30 11:57 UTC, heesunjeong commented on src/main/java/nextstep/subway/domain/Line.java
> +    private void verifyConnectable(Section section) {
`새로운 구간의 하행역은 해당 노선에 등록되어있는 역일 수 없다.` 조건도 인수테스트와 함께 구현해보시면 좋을 것 같아요 :)

2022-01-30 11:57 UTC, heesunjeong commented on src/main/java/nextstep/subway/domain/Section.java
> +    }
```suggestion
   public boolean isConnectable(Section section) {
        return section.isEqualToUpStation(downStation);
    }

    private boolean isEqualToUpStation(Station station){
        return this.upStation.equals(station);
    }
```

>어떻게 하면 도메인에 로직을 옮길 수 있는지를 고민하면서 작성했습니다. 최대한 getter, setter를 안 쓰고 싶었는데, 일부는 아쉽네요.

getter와 setter를 전혀 안쓰기는 어려운 일 인 것 같아요 ㅜ_ㅜ section의 값을 getter를 사용하지 않고 section에게 메세지를 보내서 확인할 수 있도록 잘 해주신 것 같아요 👍  이 부분이 맘에 안드셨다면 이렇게도 작성해볼 수 있을 것 같아요~!

2022-01-30 13:55 UTC, gashe-soo commented on src/main/java/nextstep/subway/domain/Line.java
> +
1d4e8de
동의합니다. 수정했습니다.

2022-01-30 13:56 UTC, gashe-soo commented on src/main/java/nextstep/subway/domain/Line.java
> +        if(!lastSection.isEqualToDownStation(station) || sections.size() == 1){
매직넘버를 깜빡했네요! 리뷰 감사합니다. 
6ae95de

2022-01-30 13:57 UTC, gashe-soo commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        Section savedSection = sectionRepository.save(section);
section id를 넘겨주려고 하다보니 사용했네요. flush를 하지 않는 이상 id을 모르지 않나요??

2022-01-30 13:57 UTC, gashe-soo commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<Section> sections = new ArrayList<>();
링크 참고해서 시도해봤습니다. 😅
8dac941

2022-01-30 13:58 UTC, gashe-soo commented on src/main/java/nextstep/subway/domain/Line.java
> +            throw new IllegalArgumentException("잘못된 요청입니다.");
메세지 구체화했습니다. 
7e9846b

2022-01-30 13:59 UTC, gashe-soo commented on src/main/java/nextstep/subway/domain/Line.java
> +    private void verifyConnectable(Section section) {
놓쳤던 케이스네요! 감사합니다. 
a8d497d

질문) 희선님은 인수조건을 어떤 식으로 도출하시나요? 이렇게 중간중간 빠지는 케이스가 있을 수 있을텐데, 리뷰로 커버하시나요?

2022-01-30 13:59 UTC, gashe-soo commented on src/main/java/nextstep/subway/domain/Section.java
> +    }
일관성 때문에 고민했던 부분인데, 이렇게 하니 더 좋네요!
3fe874e

2022-01-31 03:47 UTC, heesunjeong approved these changes
3단계 피드백 반영도 잘 해주셨네요 💯 
이수님이 하신 여러 고민을 통해서 테스트에 진심이심을 알 수 있어서 인상 깊었어요 👍 
남은 미션들을 통해서 관련해서 여러 경험들을 더 해보실 수 있으실 것 같아요~!
이번 미션은 이만 머지하도록 하겠습니다 고생 많으셨어요 👏 남은 미션들도 화이팅입니다 🔥 🔥

2022-01-31 03:47 UTC, merged