Step3: 지하철 구간 관리 코드리뷰 반영
next-step/atdd-subway-map pull request #283
Opened 2022-01-30 05:44 UTC by onestone9900

[요구사항]
지하철 노선 생성 시 필요한 인자 추가하기
지하철 노선에 구간을 등록하는 기능 구현
지하철 노선에 구간을 제거하는 기능 구현
지하철 노선에 등록된 구간을 통해 역 목록을 조회하는 기능 구현
구간 등록 / 제거 시 예외 케이스에 대한 인수 테스트 작성

[질문내용]

1. // given영역 지하철역_생성_API의 경우 테스트와 전혀 무관한 API요청이라 DB에 직접 insert해도 되지 않을까요?

2. 생성 테스트의 경우 이 정도만 확인해도 될까요? DB의 내용을 확인해보지 않아도 될까요? 예) updateAt과 createAt을 반대로 저장하고있다면?
JAVA, JPA를 사용해본적이 없어서 정확한 동작을 파악하기 힘들고, 업데이트, 삭제의 경우는 반환값도 없기 떄문에 오류가 발생하지 않으면, 테스트 코드가 통과할것 같습니다. ㅜ,ㅜ

3. 테스트에서 id 값을 컨트롤 할 필요는 있지 않나 생각이 됩니다. 예를들어) 테스트코드 짤때, 생성요청 순서를 기억하고 있어야함. 결국 1번과 비슷한 내용입니다.

[https://github.com/next-step/atdd-subway-map/pull/264]

2022-01-31 00:42 UTC, catsbi requested changes
안녕하세요 원석님 3단계 구현 잘 해주셨습니다 👍 
이전보다 코드들이 전체적으로 많이 깔끔해졌습니다. 읽는것도 한결 편해졌네요. 
피드백 필요한 부분 코멘트 남겨드렸으니 확인후 리뷰 요청 부탁드립니다 😄

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        List<StationResponse> stationResponses = stationService.createStationResponses(
이 로직이 빌더패턴에 바로 녹아들어갈 수 있을 것 같지 않나요? 
`.stations(line.getAllStations())` 이런식으로요 ㅎㅎ

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        line.removeSection(station);
stationId가 이미 식별자로써의 역할을 하기 때문에 stationService에서 해당 station을 검색할 필요가 없을 것 같은데 어떻게 생각하세요?

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +    private Distance distance;
Bean Validation을 사용하셨네요 💯

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/dto/LineResponse.java
>  public class LineResponse {
`@JsonIgnore` 애노테이션을 활용해서 반환시 null date에 대한 생략을 할 수 있습니다 😄

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +    @Column(unique = true)
JPA는 약간 이번 과정과 동떨어진 주제라, 참고만 해주세요. 
이런 unique constraint 는 필드레벨에서 애노테이션으로 제약을 주기보다는, 
`@Table(uniqueConstraints)` 애노테이션을 추천드려요 😄

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +                .distance(distance.getValue())
구간정보의 Distance는 Primitive 타입이여야 하는 이유가 있을까요?

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +        sections.add(section);
validateAddSection 메서드에서 예기치못한 예외가 발생할 수 있는데, 이 코드만 봐서는 전혀 알 수 없네요 ㅠ

그리고 이 구간 정보를 추가할 수 있는지 없는지에 대한 검사도 노선보다는 구간에서 해주는게 적절한 책임이 아닐까 싶어요 ㅎ 

이런식으로 바꿀 수는 없을까요?
```suggestion
        sections.add(section);
```

구간 추가가 가능한지 여부는 sections 자체가 검사하는거죠 ㅎ

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Line.java
> +    }
위의 addSection과 동일한 코멘트입니다 ㅎ

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/Section.java
> +    private int distance;
Distance 일급 객체가 있는데 Primitive 타입을 쓰는 이유가 있을까요?!

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/object/Distance.java
> +    int value;
일급 객체면 불변성을 확보해보려 할 수 있지 않을까요?

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/object/Sections.java
> +        return duplicatedDownStationYn || duplicatedUpStationYn;
`Stream API`의 `anyMatch()`를 사용하면 좀 더 간결하게 축소가 가능할 것 같은데 어떻게 생각하시나요 ㅎㅎ

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/object/Sections.java
> +        if (values.size() == 0) {
```suggestion
        if (values.isEmpty()) {
```
이렇게 할 수 있을 것 같아요

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/object/Sections.java
> +    public void validateAddSection(Station upStation, Station downStation) {
이렇게 예외만을 던지기위한 메서드는 주의해서 사용하는게 좋습니다 ㅎ

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/object/Sections.java
> +        if (this.values.size() <= 1) { throw new InvalidParameterException(); }
위에서는 `values.size() == 0`으로 검사를 했는데 여기서는 `<=1` 로 검사를 하면서 일관성이 깨지는 것 같아요 😢  동일하게 isEmpty()를 써보는건 어떨까요

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/domain/object/Sections.java
> +        if (!last().getDownStation().equals(station)) {
디미터 법칙을 생각해 볼 필요가 있어요. last()메서드의 결과로 마지막 구간 정보를 반환하지만, 여기서 하행역의 정보까지 조회되면서 이웃의 이웃을 알게되는 문제가 생겨요. 
어떻게 고쳐야 할까요?!

2022-01-31 00:42 UTC, catsbi commented on src/main/java/nextstep/subway/ui/LineController.java
> +            sectionRequest.getDistance().checkDistanceLessThanZero();
Bean Validation을 좀 더 활용하면 컨트롤러에 이렇게 유효성 검증 로직이 없어도 될 것 같지 않나요 ㅎㅎ

2022-01-31 17:15 UTC, onestone9900 commented on src/main/java/nextstep/subway/applicaion/dto/LineResponse.java
>  public class LineResponse {
LineResponse 생성자의 순서와 멥버변수의 순서가 안맞아서 헷갈리신거 같아요 ㅎㅎㅎ
죄송합니다...ㅠ,ㅠ

2022-02-02 03:47 UTC, closed without merging

2022-02-02 13:12 UTC, catsbi commented on src/main/java/nextstep/subway/applicaion/dto/LineResponse.java
>  public class LineResponse {
@onestone9900 
음 무슨말씀이신지 잘 이해가 되지 않습니다 😢 
이 코멘트는 stationsResponse가 null인 경우에 대해서 비어있는 List가 반환되지 않게 하기 위해서 `@JsonIgnore` 애노테이션을 제안드린 것인데, 혹시 다르게 받아들이셨을까요..?

2022-02-02 14:04 UTC, onestone9900 commented on src/main/java/nextstep/subway/applicaion/dto/LineResponse.java
>  public class LineResponse {
@catsbi 

아하.....Date값들의 Response가 필요없다는 의미로 받아들였네요...ㅎㅎㅎ
createdDate, modifiedDate

2022-02-02 14:06 UTC, onestone9900 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        List<StationResponse> stationResponses = stationService.createStationResponses(
감사합니다!