🚀 2단계 - 지하철 노선 기능
next-step/atdd-subway-map pull request #417
Opened 2022-07-10 13:51 UTC by chuvaaa

안녕하세요 리뷰어님!

🚀 2단계 - 지하철 노선 기능

작성하여 PR 요청드립니다!

진행하다보니 중간중간 기능별로 커밋을 했어야 했는데 통으로 진행해버렸네요 ㅠㅠ

2022-07-10 23:33 UTC, testrace requested changes
2단계

안녕하세요 😄 
2단계 미션 잘해 주셨네요 👍 

몇가지 코멘트 남겨두었으니 확인해 주시고 리뷰 요청 부탁드립니다.
궁금한 내용이 있으시면 언제든 편하게 DM 주세요!

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +    @Transactional(readOnly = true)
readOnly 👍

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +    @Transactional(readOnly = true)
메서드와 메서드 사이는 가독성을 위해 개행을 추가해 보시면 어떨까요?

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +                ;
세미콜론이 개행되어 작성되었네요. 민수님의 세미콜론을 찍는 기준이 궁금합니다 🤔

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +    @Transactional
클래스에 동일한 `@Transactional`이 있으니 메서드에서는 생략해 주셔도 괜찮을 것 같아요 😃

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/StationService.java
> +                .map(station -> StationResponse.of(station))
여기서도 method reference로 작성해 주셔도 좋을 것 같아요 😃 
```suggestion
                .map(StationResponse::of)
```

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/domain/Line.java
> +@Setter
entity에 setter를 적용하신 이유가 궁금합니다 🤔

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/domain/Line.java
> +    private Long upStationId;
id 간접 참조 👍

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line() {}
`@Entity` 붙은 클래스에서는 public 보다 protected를 더 권장하는 편입니다 :)

2022-07-10 23:33 UTC, testrace commented on src/main/java/nextstep/subway/ui/LineController.java
> +    private LineService lineService;
초기화 이후 재 할당 되지 않는다면 final 을 붙여주시는 것도 좋을 것 같아요 😃

2022-07-10 23:33 UTC, testrace commented on src/test/java/nextstep/subway/test/acceptance/AcceptanceTest.java
> +public class AcceptanceTest {
테스트 격리와 함께 중복되는 코드를 클래스로 분리해 주셨네요 💯

2022-07-10 23:33 UTC, testrace commented on src/test/java/nextstep/subway/test/acceptance/LineAcceptanceTest.java
> +    public String stationId4;
변수명에 1, 2, 3, 4를 붙이는건 변수의 용도를 알기 어렵게 만드는 원인이라고 생각합니다.
변수명에 의미있는 이름을 부여한다면 가독성을 높일 수 있을 것 같은데 어떻게 생각하시나요?
테스트 코드에서는 읽기 쉬운 테스트를 위해 한글 변수명이나 한글 메서드명도 사용하는 편이니 고려해 보시면 좋을 것 같아요 😃

2022-07-10 23:33 UTC, testrace commented on src/test/java/nextstep/subway/test/acceptance/LineAcceptanceTest.java
> +                지하철노선_생성("파랑선", stationId1, stationId2, "blue", "10");
반복되어 지하철 노선 생성 코드의 중복을 제거하고 재사용성과 가독성을 높이는 TestFixture를 활용해 보시면 좋을 것 같습니다 😃

2022-07-10 23:33 UTC, testrace commented on src/test/java/nextstep/subway/test/acceptance/LineAcceptanceTest.java
> +    ExtractableResponse<Response> 지하철노선_생성(String lineName, String upStationId, String downStationId,
StationTestMethod 처럼 클래스로 분리하면 코드의 통일성을 갖출 수 있을 것 같은데 민수님 생각은 어떠신가요?

2022-07-10 23:43 UTC, chuvaaa commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +                ;
줄을 바꾸면서 습관처럼 개행되어 세미콜론을 작성하는 경우가 종종 생기더라구요 ㅠㅠ 일관성있게 수정하겠습니다!

2022-07-11 00:07 UTC, chuvaaa commented on src/test/java/nextstep/subway/test/acceptance/LineAcceptanceTest.java
> +    ExtractableResponse<Response> 지하철노선_생성(String lineName, String upStationId, String downStationId,
넵 아직은 다른곳에서 사용되지 않아 분리하지 않았었는데, 통일성있게 미리 해두는게 더 깔끔할거 같네요!

2022-07-11 00:13 UTC, chuvaaa commented
수정사항 반영하여 재요청 드렸습니다! 감사합니다

2022-07-11 00:51 UTC, chuvaaa commented on src/main/java/nextstep/subway/domain/Line.java
> +@Setter
Setter 삭제하였습니다

2022-07-11 03:54 UTC, testrace approved these changes
안녕하세요 😄 
피드백 반영 잘해 주셨네요 💯 

바로 다음 단계 진행해 주세요. 
한 가지 코멘트 남겼는데 다음 단계 진행하시면서 참고해 주시고
커밋을 작은 단위로 자주해 보시는 것도 좋을 것 같아요.

2022-07-11 03:54 UTC, testrace commented on src/test/java/nextstep/subway/test/acceptance/LineAcceptanceTest.java
> +                .jsonPath().getLong("id");
비슷한 내용으로 반복되는 코드듣을 TestFixture를 활용해 줄여 보셔도 좋을 것 같아요!

2022-07-11 03:56 UTC, merged