Step2 지하철 노선 기능 추가
next-step/atdd-subway-map pull request #420
Opened 2022-07-10 14:52 UTC by chosundeveloper

지하철 노선 생성을 위한 지하철역 생성 데이터를 init.sql로 넣으려고 시도하였으나 truncate.sql 과 같이 사용할때 초기화 쿼리 이후 insert 쿼리를 사용했음에도 불구하고 첫 실행 테스트에만 초기데이터가 들어가고 이후에는 DB에 잘 들어가지 않아서 현재는 지하철 노선 생성 전 지하철 역 생성 API를 호출하고 있습니다. 좀 더 확인 후 리팩토링 예정입니다. 감사합니다!!

2022-07-11 04:51 UTC, boorownie requested changes
안녕하세요! 2단계 요구사항 잘 구현해주셨습니다 👍 
2단계 요구사항은 구현할 게 많지는 않지만 고민이 많이 필요한 미션이였을텐데요
코멘트를 남겨놓았으니 추가적으로 고민 해주신 다음 리뷰요청 부탁드립니다!

참고로 인수 테스트 격리와 관련해서는 추가되는 테이블을 개발자가 신경쓰지 않아도 되게끔
테이블 이름을 불러와서 직접 트렁케이트 시켜주는 방법을 고민해보시는 것도 좋을 것 같아요!

2022-07-11 04:51 UTC, boorownie commented on src/test/resources/truncate.sql
> +SET FOREIGN_KEY_CHECKS = 1;
초기화 하기 위한 쿼리네요
테이블이 추가될 때마다 해당 코드를 수정해주어야 할 것 같은데
테이블의 추가와 무관하게 데이터를 초기화 할 수 있는 방법은 없을까요?

2022-07-11 04:51 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/StationAcceptanceTest.java
> +        );
독립적인 검증을 위한 assertAll 사용 👍

2022-07-11 04:51 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    }
인수 테스트 클래스에서 공통으로 사용되는 부분은 추상 클래스로 묶어도 좋을 것 같네요 :)

2022-07-11 04:51 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    private final StationAcceptanceTest stationAcceptanceTest;
다른 인수 테스트 클래스의 스텝을 재사용하는 방법으로 클래스에 대한 참조를 선택하셨네요!
만약에 스텝 메서드만 따로 분리된 유틸성 클래슬르 만든다면 어떨까요?

2022-07-11 15:55 UTC, chosundeveloper commented on src/test/resources/truncate.sql
> +SET FOREIGN_KEY_CHECKS = 1;
@sql과 databasecleanup 사이에서 고민하다 쉬워보이는 걸로 선택했는데 단점이 있었네요 ㅎㅎ

2022-07-11 15:55 UTC, chosundeveloper commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    }
추상 클래스로 분리 했습니다.

2022-07-11 15:57 UTC, chosundeveloper commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    private final StationAcceptanceTest stationAcceptanceTest;
step이라는게 lineStep으로 한걸 의미하시는지 긴가민가하네요. 만약 맞다면 대부분의 것들을 step으로 빼고 테스트 클래스에서는 step에 있는 단계들을 골라쓰는 형식으로 컴포넌트처럼 대부분을 step클래스로 빼고 인수테스트에서는 그들의 조합을 작성하는 형식으로 가는게 맞는지 궁금합니다.

2022-07-11 15:59 UTC, chosundeveloper commented on src/test/resources/truncate.sql
> +SET FOREIGN_KEY_CHECKS = 1;
지하철 노선을 생성하려면 지하철 역이 존재해야하는데 query로 쳐서 넣어놓는게 맞는건지 지하철 노선 생성 전 지하철 역 생성 api를 호출하는게 맞는건지 궁금합니다. init.sql에 truncate에 영향을 받아서 일단 api호출 형식으로 해놨지만요

2022-07-11 16:05 UTC, chosundeveloper commented on src/test/resources/truncate.sql
> +SET FOREIGN_KEY_CHECKS = 1;
2. lombok 사용해도 괜찮을지도 질문드려요

2022-07-12 01:41 UTC, boorownie commented on src/test/resources/truncate.sql
> +SET FOREIGN_KEY_CHECKS = 1;
테스트를 수행하기 위한 환경을 테스트 컨텍스트라고 하는데 환경을 구성하기 위한 방법으로 직접 쿼리를 날려서 구성을 하는 방법과 API 호출하는 방법 등이 있을 것 같아요. 쿼리를 날리는 방법은 블랙박스 테스트라고 보기 어렵기도 해서 저는 API 호출하는 방식을 추천하고 있습니다.

2022-07-12 01:41 UTC, boorownie commented on src/test/resources/truncate.sql
> +SET FOREIGN_KEY_CHECKS = 1;
롬복 사용은 괜찮습니다만 무분별한 사용은 지양하고 있습니다.

2022-07-12 01:42 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    private final StationAcceptanceTest stationAcceptanceTest;
네 그런 방향으로 가이드하고 있습니다.
그렇게 리팩터링을 할 경우 인수 테스트에서 인수 조건들을 파악하는데 조금 더 수월해질 것 같고 재사용도 편해질 것 같습니다.

2022-07-12 01:46 UTC, boorownie approved these changes
피드백 반영 확인했습니다!
가독성과 재사용성이 좋아졌네요!

참고로 저는 코멘트로 리팩터링의 방향성을 제시해드리는 것이고
실제로 반영하는것은 본인이 판단하여 좋은 방법을 경험하는게 좋다고 생각합니다!
리뷰어의 코멘트를 반영해보는 경험도 중요하지만 자신의 기준을 찾아가는게 더 중요할 수 있으니까요!ㅎㅎ

이어서 다음 단계 미션 진행해주세요~

2022-07-12 01:46 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/AcceptanceTest.java
> +public class AcceptanceTest {
중복 제거 👍

2022-07-12 01:46 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/station/StationSteps.java
> +public class StationSteps {
재사용하기 좋게 분리를 해주셨네요 👍

2022-07-12 01:46 UTC, merged