Step2: 지하철 노선 기능
next-step/atdd-subway-map pull request #425
Opened 2022-07-10 16:16 UTC by hscom96

리뷰어님 안녕하세요 ~
미션 Step2 구현했습니다 😃

2022-07-11 06:22 UTC, pch8388 requested changes
안녕하세요 🙇 
2단계 구현 잘해주셨지만 수정하고 넘어갔으면 하는 부분이 있어서 코멘트를 남겨두었습니다.
참고하시고 수정 후 리뷰요청 해주세요 🔥

2022-07-11 06:22 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        지하철역_생성_요청("기흥역").jsonPath().getLong("id");
```suggestion
        지하철역_생성_요청("기흥역");
```

`getLong` 을 할 필요가 있을까요?

2022-07-11 06:22 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(lineNames).containsExactlyInAnyOrder("신분당선", "에버라인");
`지하철노선_생성_요청` 처럼 조금 더 읽기 편하게 만들면 어떨까요?

인수테스트를 읽는 사람이 누구인가에 대해 고민해봐야 하는데요.
클린 애자일의 구절을 인용하면
>인수테스트는 업무 분석가와 QA, 개발자가 함께 힘을 모아 작성한다.

이와 같이 인수테스트를 읽는 사람이 모두 개발자는 아닐 수 있다고 생각합니다 😃.

2022-07-11 06:22 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        지하철노선_생성_요청("신분당선", "bg-red-600", upStationId, downStationId, 10);
텍스트를 상수로 교체해보면 어떨까요? 🤔 

> 클린 코드 G25: 매직 숫자는 명명된 상수로 교체하라

2022-07-11 06:22 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/line/LineService.java
> +        List<Station> stations = stationRepository.findAllById(List.of(request.getUpStationId(), request.getDownStationId()));
존재하지 않는 `역의 id`가 들어오면 어떻게 될까요? 🤔

2022-07-11 06:22 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/line/LineService.java
> +                                  .orElseThrow(() -> new IllegalArgumentException(LINE_NOT_FOUND));
중복이 발생한 거 같아요 😿

2022-07-11 06:22 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/line/Line.java
> +    public Line(final String name, final String color, final Long upStationId, final Long downStationId, final Integer distance) {
> 이펙티브 자바 : 아이템2. 생성자에 매개변수가 많다면 빌더를 고려하라

2022-07-11 06:22 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/line/Line.java
> +    private Long upStationId;
사용하신 방법은 `간접참조`라고 할 수 있는 데, `직접참조` 를 통한 방법도 있습니다. [직접참조 참고](https://velog.io/@ljinsk3/JPA-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%EB%A7%A4%ED%95%91-%EA%B8%B0%EC%B4%88)

2022-07-11 06:22 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/StationAcceptanceTest.java
> +        assertThat(stationNames).containsExactlyInAnyOrder("기흥역", "신갈역");
💯

2022-07-11 06:41 UTC, hscom96 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    void updateLine() {
앗.. 제 로컬에서는 개별, 통합으로 실행해도 모두 테스트 성공입니다 🤔 
혹시 에러로그를 알수있을까요?

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/46397442/178203817-ffd42713-3b19-483b-ac5e-47f6a9f36f70.png">

2022-07-11 06:57 UTC, hscom96 commented on src/main/java/nextstep/subway/domain/line/LineService.java
> +                                  .orElseThrow(() -> new IllegalArgumentException(LINE_NOT_FOUND));
피드백을 이해못했는데 혹시 어떤 중복을 말씀하신건가요??

2022-07-11 08:57 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/line/LineService.java
> +                                  .orElseThrow(() -> new IllegalArgumentException(LINE_NOT_FOUND));
`findLineById`와 `updateLine`에 해당 구문이 동일하게 들어가는 것 같아요 😅

2022-07-11 13:15 UTC, hscom96 commented on src/main/java/nextstep/subway/domain/line/LineService.java
> +package nextstep.subway.domain.line;
관리하기 편하게 같은 부류를 모았습니다.  🤔

2022-07-11 13:17 UTC, hscom96 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        지하철역_생성_요청("기흥역").jsonPath().getLong("id");
앗 그러네요 수정했습니다 ~

2022-07-11 13:45 UTC, hscom96 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        지하철노선_생성_요청("신분당선", "bg-red-600", upStationId, downStationId, 10);
네 수정했습니다 ~ 
70d8fb7c

2022-07-11 14:32 UTC, hscom96 commented on src/main/java/nextstep/subway/domain/line/LineService.java
> +                                  .orElseThrow(() -> new IllegalArgumentException(LINE_NOT_FOUND));
아하! ㅎㅎ 감사합니다. 다른 동일한 부분도 수정했습니다. 
d5158c2f

2022-07-11 14:39 UTC, hscom96 commented on src/main/java/nextstep/subway/domain/line/Line.java
> +    public Line(final String name, final String color, final Long upStationId, final Long downStationId, final Integer distance) {
직접 구현하면 코드가 상당히 복잡해지는데 혹시 이번 과정에서 롬복 활용이 가능한가요?

2022-07-11 15:03 UTC, hscom96 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +    void updateLine() {
아 위와같은 문제였군요 ㅎㅎ 수정했습니다 ~
83031f79

2022-07-11 15:08 UTC, hscom96 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(lineNames).containsExactlyInAnyOrder("신분당선", "에버라인");
`지하철노선_생성_요청`처럼 해당 메서드에서도 `지하철노선_목록_조회`로 별도 분리해서 
읽기 편하게 만들었는데 더 개선할 부분이 있나요?!

2022-07-12 07:03 UTC, hscom96 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(lineNames).containsExactlyInAnyOrder("신분당선", "에버라인");
제가 이해를 잘못했었던거 같은데 말씀 주신 방식이 아래와 같은것 맞을까요!? 

```java
void findAllLine() {
        // given
        지하철노선_생성_요청("신분당선", "bg-red-600", upStationId, downStationId, LINE_DISTANCE);
        지하철노선_생성_요청("에버라인", "bg-red-600", upStationId, downStationId, LINE_DISTANCE);

        // when
        final ExtractableResponse<Response> response = 지하철노선_목록조회_요청();

        // then
        지하철_노선목록에서_노선포함확인(response, List.of("신분당선", "에버라인"))
    }
```

2022-07-12 11:39 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        지하철역_생성_요청("기흥역");
👍

2022-07-12 11:39 UTC, pch8388 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(lineNames).containsExactlyInAnyOrder("신분당선", "에버라인");
인수테스트의 작성 방법은 ~ 이렇게 해야합니다. 라고 말할 수는 없을 것 같아요 😅 
모든 게 방법론일 뿐이고, 밥아저씨가 주장하는 바를 인용하여 하나의 방법을 제시하는 것일 뿐입니다.
사실 저는 꽤나 동의하지만 현실적으로 힘든 목표라고 생각하고 있고, 그럼에도 불구하고 인수 테스트는 개발자가 아닌 사람이 읽을 수 있도록 
 해야 한다고 생각하고 있습니다.
(심지어 밥아저씨는 인수 테스트를 개발자가 아닌 사업부서와 QA가 작성 하라고 합니다..)

> 사실 인수 테스트 실천 방법은 꽤 단순하다. 사업 부서에서 각 사용자 스토리의 동작을 설명하는 테스트를 형식에 맞게 작성하고, 개발자는 이를 자동화한다.

조금 더 마음의 평화를 드리기 위해 클린코드를 인용하겠습니다.
> 함수 당 추상화 수준은 하나로!
> 함수가 확실히 '한 가지' 작업만 하려면 함수 내 모든 문장의 추상화 수준이 동일해야한다...(중략)... 한 함수내에 추상화 수준을 섞으면 코드를 읽는 사람이 헷갈린다. 특정 표현이 근본 개념인지 아니면 세부사항인지 구분하기 어려운 탓이다. 하지만 문제는 이정도로 그치지 않는다. 근본 개념과 세부사항을 뒤섞기 시작하면, 깨어진 창문처럼 사람들이 함수에 세부사항을 점점 더 추가한다.

2022-07-12 11:39 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/line/Line.java
> +    public Line(final String name, final String color, final Long upStationId, final Long downStationId, final Integer distance) {
사용하셔도 됩니다 😄

2022-07-12 11:41 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/line/Line.java
> +    private Long upStationId;
사실 항상 그렇지는 않습니다.
DDD 의 사상을 받아 들여 개발하는 분들은 간접참조를 사용 하라고 가이드 하기도 합니다 😃

2022-07-12 11:41 UTC, pch8388 approved these changes
리팩토링 하시느라 고생 많으셨습니다 💯 
다음 단계 미션 진행해주세요 🔥

2022-07-12 11:41 UTC, merged

2022-07-12 14:32 UTC, hscom96 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        assertThat(lineNames).containsExactlyInAnyOrder("신분당선", "에버라인");
추가적인 자료까지 알려주셔서 감사합니다 ! 😃 인수테스트, 클린코드 까지 알아갑니다 😆