Step3 : 지하철 구간 관리
next-step/atdd-subway-map pull request #437
Opened 2022-07-12 09:18 UTC by ryuhistory

안녕하세요.
3단계 지하철 구간관리 입니다.

2단계에서 조언주셨던 부분을 3단계 진행전 적용해보았습니다.
가독성 및 테스트 격리 편의성이 확실히 좋아진거 같습니다.
또한 StationLine, StationSelection으로 도메인을 최초에 구성했다가
Staion에 중복되어, 네이밍을 다시 하여 적용했습니다.

3단계 지하철 구간부터는 요구사항 분석에 다소 시간이 걸렸습니다.
지하철 노선에 도메인의 설게 사상을 처음에 이해하고 각 단계를 시작했다면
요구사항 분석이 수월하지 않았을까라는 아쉬움이 좀 생기네요ㅠ

## 추가 기능
1. 구간등록, 삭제기능을 검증하기 위해선
 구간 목록 및 구간 조회 api가 추가로 필요할것으로 판단하여 추가했습니다.

2. ControllerAdvice를 이용한 예외처리

## 질문

1. ATDD시 등록 api 후, 전체 필드에 대한 값 검증을 해주는것이 좋을까요? 최초 구현시에는 각 필드의 값을 비교하게 테스트 메소드를 작성하였지만 가독성이 떨어져서 단순 Id만 비교 하도록 변경하였습니다.

2. ATDD에서도 실패 케이스 테스트를 추가 해야 할까요?? 등록/삭제 기능에서 불가능한 조건이 있어 해당 도메인에 벨리데이션을 추가 하였지만 
   테스트 코드에서 각각의 실패케이스를 테스트를 해야 할까요?

2022-07-12 09:25 UTC, ryuhistory commented on src/main/java/nextstep/subway/common/response/CommonControllerAdvice.java
> +		return ResponseEntity.badRequest().build();
예외처리는 우선 조회 결과가 없는경우와, 상태체크를 
위 2가지로 정의하여 처리 하였습니다.

2022-07-12 17:01 UTC, ivvve commented
@ryuhistory 

> 1. ATDD시 등록 api 후, 전체 필드에 대한 값 검증을 해주는것이 좋을까요? 
최초 구현시에는 각 필드의 값을 비교하게 테스트 메소드를 작성하였지만 
가독성이 떨어져서 단순 Id만 비교 하도록 변경하였습니다.

정해진 답은 없기에 딱히 이렇게 하세요~라고 답변 드리긴 힘들 것 같아요!
대신 그 값이 얼마나 중요하냐에 따라 중요도가 달라질 것 같습니다.
예를 들어 계산이 포함된 로직을 통해 생성되는 객체라면 필드에 대한 검증이 매우 중요하겠죠...!

만약 값이 제대로 저장되었는지 확인하고 싶다면 필드를 검증하는 것도 좋다고 봅니다만
말씀하신대로 검증 외에도 코딩을 하면서 챙겨줘야하는 부분이 있기 때문에 테스트를 건너뛰어도 괜찮을 것 같다고 하면 건너뛰어도 될 것 같습니다 :)

> 2. ATDD에서도 실패 케이스 테스트를 추가 해야 할까요?? 
등록/삭제 기능에서 불가능한 조건이 있어 해당 도메인에 벨리데이션을 추가 하였지만
테스트 코드에서 각각의 실패케이스를 테스트를 해야 할까요?

명확하게 인수 조건이기 때문에 지금과 같은 경우는 테스트를 해주는 것이 좋을 것 같습니다.

다만 생성하고 삭제하고 할 때 중복되는 API 요청이 계속 생길 수 있는데요.
이는 `인수테스트 리팩터링` 시간에서 다뤄질 예정입니다 :)

추가로 개인적으로 인수테스트에서는 API validation에 대한 테스트는 하지 않는 편입니다.
(번거롭기도하고 필드가 많아지면 많아질수록 테스트 코드가 번잡해져서 선호하진 않습니다)

> 3. 수정 api를 추가 하려 했지만, 
예외조건을 삭제기능과 동일하게 가도 되는지 여부가 판단되지 않아서 우선 보류 하였습니다.

수정은 미션 내용이 아니니 굳이 안해주셔도 될 것 같아요 :)

2022-07-12 17:01 UTC, ivvve requested changes
제형님 안녕하세요~
인수 테스트를 보니 인수 조건에 대한 표현력이 높아진 것이 보이네요 👍 👍 

다만 노선에 `구간`이라는 개념이 추가되었기 때문에 노선과 구간의 엔티티 모델링에 대해서 한번 더 확인 부탁드릴게요 🙏

2022-07-12 23:23 UTC, ryuhistory commented on src/main/java/nextstep/subway/common/response/CommonControllerAdvice.java
> +	}
@ivvve 맘에 걸리긴 했지만 귀찮아서 대충 처리했는데 부끄러워지네요ㅠㅠ

2022-07-12 23:23 UTC, ryuhistory commented on src/main/java/nextstep/subway/domain/Selection.java
> +public class Selection {
@ivvve 아....

2022-07-13 10:45 UTC, ryuhistory commented on src/main/java/nextstep/subway/common/response/CommonControllerAdvice.java
> +		return ResponseEntity.ok().body(responseBody);
스스로 좀 아쉬운점은 응답데이터를 공통의 CommonResponse로 wrapping 해서 처리하고 싶은데..
다음 단계 넘어가면 한번 작업 해보려 합니다

2022-07-13 10:45 UTC, ryuhistory commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +	}
Section 테스트 하기 위해선 노선이 선행되어 등록이 되어 있어야 해서
beforeEach로 분리 했습니다.

2022-07-13 10:45 UTC, ryuhistory commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +		지하철_구간_생성(lineId, UP_STATION_ID_1, DOWN_STATION_ID_1, DISTANCE_1, HttpStatus.CREATED, "sectionId");
지하철_구간_생성 부분을 추상화 하면서 각각의 경우를 다 처리하려다보니
메소드 파라미터가 좀 많아졌는데
인수테스트에서는 이처럼 메소드 파라미터가 많아져도 괜찮은지 궁금하네요ㅠ

2022-07-13 12:34 UTC, ivvve commented on src/main/java/nextstep/subway/common/response/CommonControllerAdvice.java
> +		return ResponseEntity.ok().body(responseBody);
물론 해주면 좋지만 이번 과정에 있어 꼭 필요한 부분은 아니니 부담되시면 넘기셔도 좋을 것 같습니다 ㅎㅎ

2022-07-13 12:44 UTC, ivvve commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +		지하철_구간_생성(lineId, UP_STATION_ID_1, DOWN_STATION_ID_1, DISTANCE_1, HttpStatus.CREATED, "sectionId");
네 사실 테스트 가독성을 무시할 순 없죠!
그래서 파라미터가 너무 많아서 오히려 인수 조건에 대해 표현력이 떨어지는 경우라면 
(약간 극단적이긴 한데...) 조금 중요성이 떨어지는 메서드 파라미터로 받지 않기도 합니다.

물론 다 장단이 있어서 무엇이 정답이다라고 할 순 없구요...!
여러가지로 한 번 시도해보시면서 제형님 나름의 노하우를 쌓아가시면 좋을 것 같습니다 :)

2022-07-13 12:46 UTC, ivvve commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +
지금과 같이 `@BeforeEach`로 빼놓는 경우엔 생략 가능할 것 같습니다 :)
대신 `@BeforeEach`로 있으면 선행 조건이 명확하게 드러나지 않는 단점도 있으니 적절하게 선택하시면 좋을 것 같아요!

2022-07-13 13:30 UTC, ivvve approved these changes
제형님 안녕하세요!

잘 마무리 해주셨습니다!
인수 조건에 대해 표현력있는 인수 테스트를 작성하는데에 대해서 어느정도 감을 잡으셨다고 생각이 듭니다! 😎 

나중에 시간이 되신다면 인수 테스트에 있는 인수 조건에 대한 주석을 다 지워보시고
인수 테스트 코드를 읽었을 때 도메인이 쉽게 파악되는지도 살펴보시면 좋을 것 같습니다 :)
또 한 달 뒤에 인수 테스트 코드를 읽었을 때 도메인을 쉽게 다시 떠올릴 수 있을까도 생각해보시면 좋을 것 같아요 :)

첫번째 미션 고생 너무 많으셨구요!
남은 미션도 화이팅입니다!! 🔥 🔥 
고생 많으셨습니다 :)

2022-07-13 13:30 UTC, merged