Step3
next-step/atdd-subway-map pull request #455
Opened 2022-07-13 11:24 UTC by tndyd5390

안녕하세요. 리뷰어님!!
3단계 지하철 구간관리 미션 진행하였습니다.
리뷰 부탁드리겠습니다.

감사합니다!

2022-07-13 12:01 UTC, junwoochoi requested changes
안녕하세요! 3단계 미션 수행해주신 것 확인했습니다!
전반적으로 응집도가 높은 코드를 신경써서 짜주신 것 같아서 인상깊었어요.
몇가지 코멘트 드렸으니 확인 부탁드립니다!! 😃

2022-07-14 02:48 UTC, tndyd5390 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +		Line line = lineRequest.toEntity(new Section(upStation, downStation, lineRequest.getDistance()));
리팩토링 과정에서 미처 신경쓰지 못한 부분이네요 수정하였습니다!.

2022-07-14 02:49 UTC, tndyd5390 commented on src/main/java/nextstep/subway/domain/SectionRepository.java
> +}
맞네요 사실상 사용하지 않는 클래스인데 습관적으로 Repository를 만들다 보니 생성된거 같습니다 ㅠㅠ

2022-07-14 04:56 UTC, tndyd5390 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +		assertThat(response.jsonPath().getString("errorMessage")).contains("하행 종점이 추가하려는 구간의 상행역과 일치하지 않습니다");
의미를 파악하기 힘든 검증로직은 따로 함수로 추출하여 static 클래스로 위치를 옮겼습니다.
옮기고 보니 다른 검증로직들도 함수로 추출하여 옮기는 것이 바람직해보이는데 static 클래스의 크기가 너무 커지는 것이 걱정입니다. 
리뷰어님은 이런경우 어떻게 하시나요??

2022-07-14 05:05 UTC, tndyd5390 commented on src/main/java/nextstep/subway/domain/Sections.java
> +		return sections.get(sections.size() - 1);
말씀해주신대로 LastSection을 찾는 다른 방법을 생각해보았지만 UpStation과 DownStation id 로 새로운 정렬을 하기보단 구간의 추가와 삭제가 하행종점에서만 일어나니 orderby id asc로 설정하였습니다.

2022-07-14 11:20 UTC, junwoochoi approved these changes
3단계 미션 진행하시느라 수고 많으셨습니다!!

다음주차 미션도 화이팅해주세요! :)

2022-07-14 11:20 UTC, junwoochoi commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +	public LineService(LineRepository lineRepository, StationRepository stationRepository) {
피드백 적용 👍

2022-07-14 11:20 UTC, junwoochoi commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +		assertThat(response.jsonPath().getString("errorMessage")).contains("하행 종점이 추가하려는 구간의 상행역과 일치하지 않습니다");
@tndyd5390 저는 지금 정도 길이도 괜찮다고 보고 사용하고 있습니다. ㅎㅎ....

2022-07-14 11:21 UTC, merged