Step3 - 지하철 구간 관리
next-step/atdd-subway-map pull request #471
Opened 2022-07-15 07:10 UTC by lsj8367

도메인 로직을 많이 변경해서 구조를 개선해보았습니다.

그렇지만 오히려 많은 생각이 들어가서 그런지 꼬인부분도 당장엔 생각이 나지 않아서

일단 구현 되는대로 리뷰 요청 드립니다!

이번 리뷰도 잘 부탁드립니다!!🙏

2022-07-16 04:14 UTC, starkim06 requested changes
안녕하세요 승재님, 

요구사항에 맞게 구현 잘 해주셨네요!!
리뷰 남겼으니 확인부탁드려요.

> 상행, 하행역을 만들어주는 구간을 생성할 시에, 상행과 하행 사이에 중간역을 넣어주는 것은 고려를 안해줘도 될까요?
현재의 요구사항은 "새로운 구간의 상행역은 해당 노선에 등록되어있는 하행 종점역이어야 한다." 라서 고려를 안해주셔도 되지만, 요구사항은 언제든지 변경될 수 있다는점도 기억해주시면 좋을것 같아요.

2022-07-17 04:29 UTC, lsj8367 commented on src/main/java/nextstep/subway/domain/Station.java
> +    public Station(Long id, String name) {
이런방법을 생각해보지 못하고 있었는데 좋은것 같습니다!

2022-07-17 04:49 UTC, lsj8367 commented on src/main/java/nextstep/subway/domain/Section.java
> +    public void removeLine() {
엮어주는것만 생각하고 뒤에서 제거할때를 고려하는걸 빼먹었었네요!

2022-07-17 05:27 UTC, starkim06 approved these changes
안녕하세요 승재님!
리뷰 반영 잘 해주셨네요!!!
1주차 미션 진행하시느라 정말 수고 많으셨습니다!

간단한 코멘트 하나 남겨두었습니다! 참고 부탁드려요 =) 
남은 주차 미션들도 잘 진행하시길 바라겠습니다! 👊

2022-07-17 05:27 UTC, starkim06 commented on src/main/java/nextstep/subway/domain/Section.java
> +    public void isEqualTo(final long stationId) {
is~로 시작하니 return 값이 boolean 일 것 같다는 생각이 드네요!

2022-07-17 05:27 UTC, merged