3단계 - 지하철 지하철 구간 관리 미션
next-step/atdd-subway-map pull request #474
Opened 2022-07-16 07:35 UTC by gzgzg2

안녕하세요 현성님 ! 아직 미션을 완료하진 못했지만 궁금한 점이 있어서 리뷰 요청드렸습니다 ! 

<img width="568" alt="스크린샷 2022-07-16 오후 12 51 47" src="https://user-images.githubusercontent.com/56028408/179344715-0cc2d552-59e3-4f68-bb33-041921c17097.png">
3단계 등록 미션 API 규약과 다른 응답이긴 하지만 해당 응답과 관련해서 궁금한 점이 있습니다!

1. `Sections(OneToMany)`와  `Section의 Line(ManyToOne)` 관계에서 1은 Sections이 되는 것인가요? 아직 해당 내용이 잘 이해가 되지 않습니다. Section과 Line의 관계에선 라인이 1 이라고 생각이 드는데요 .. @OneToMany가 명시된 객체가 1의 역할을 한다는 부분이 이해가 되질 않습니다 ㅠㅠ
2. Section 엔티티는 Line 엔티티의 Line_id와 관계가 맺어진 상태인데 응답값이 Line 값이 null인 이유가 궁금합니다 ! 스스로 해결해보려고 했지만 키워드가 떠오르지 않네요.. !! 
----

남은 요구사항도 전부 완성하면 리뷰요청을 한번 더 드리게 될 것 같아요 🙏🏻
JPA 너무 어렵네요 !! 🥺

2022-07-16 07:38 UTC, gzgzg2 commented on src/main/java/nextstep/subway/domain/Section.java
> +    private Line line;
원래는 Line 위에 
`@Joincolumn(name = "line_id")` 를 명시해뒀었는데 원하는 결과`(응답 시 line 필드가 null이 아닌 것)`를 얻지 못해서 
삭제해버렸습니다 ! @Joincolumn의 역할을 모르고 사용하는 느낌이 들어서요 ..

2022-07-17 08:55 UTC, HyunSung-Na requested changes
안녕하세요 ramram 님!

미션 잘 수행해 주시고 있으시네요! ☺️

해당하는 부분은 JPA 연관관계와 관련된 부분인 것 같네요

먼저 line 과 section 의 관계는 OneToMany 가 맞습니다.

말씀하신대로 라인이 1이 맞는 경우이죠. 하지만 해당 미션에서는 Sections 에 관련된 메서드나 기능을 구현할 일이 많다보니

도메인 로직을 line 에 놓기엔 sections 와 관련된 기능을 line 도메인내에 놓기엔 부담스럽다고 생각합니다.

그래서 sections 라는 Embeddable 이라는 것을 통해 구현하였는데요

JPA 에서는 Entity 안의 값을 조금 더 의미 있는 값으로 표현하기 위해 응집된 하나의 객체로 데이터를 표현하기도 합니다.

이를 통해 가독성과 기능별로 분리된 도메인을 구현할 수 있다는 장점이 있는 것 같아요

`@Embedded 와 `Embeddable 키워드로 찾아보시면 좋을 것 같습니다.

그리고 두번째 질문에 대해서는 해당 코드를 확인해 보았는데요. 말씀하신 문제가 findAllStationLines 메서드를 호출할때

응답값에 대한 문제가 맞을까요?

해당 부분은 StationLineResponse 로 map 으로 변환하는 과정에서 from 메서드를 사용할 때 sections 부분은 세팅하지 

않는 것으로 보입니다. 밑에 구현하신 of 메서드로 구현해 보시면 어떨까요? ☺️

더 궁금하신 점이나 어려운 점이 있으시면 언제든지 질문 주셔도 좋습니다! PR 로 주시지 않으셔도 슬랙을 통해서 질문 언제든지 환영합니다 👍

해당 내용 확인해 보시고 미션 구현해주시면 좋을 것 같습니다!

2022-07-17 09:02 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Section.java
> +    private Line line;
해당 부분은 외래키를 매핑할 때 사용하는 애너테이션인데요 실제로 다른 엔티티와 연관관계를 가질 때 외래키 설정을 할때 쓰입니다.
보통 실제 데이터베이스에 설정된 pk 이름을 정확히 명시해주려고 사용하는데요. 객체로 선언된 변수명과 데이터베이스에 있는 필드 네임이 다를 경우 매핑을 해주기 위해서 사용하는 경우가 많습니다. 해당 부분은 line 이 null 로 반환되서 고민 중 이신건가요?

2022-07-18 04:14 UTC, gzgzg2 commented on src/main/java/nextstep/subway/domain/Section.java
> +    private Line line;
넵 line이 null로 반환되는 이유를 찾지 못해서 고민이었습니다. 
현재는 JPA 관계에 대해서 조금 학습한 상태인데 @ManyToOne을 명시한 엔티티가 관계의 주인이라는 것을 알게 되었어요. 
아직은 조금 헷갈리지만 배운대로 다시 수정해보려 합니다 !

2022-07-19 11:53 UTC, HyunSung-Na approved these changes
안녕하세요 ramram 님!

3단계 미션 잘해주셨네요! 💯

미션 잘 마무리 해주셨습니다! 

몇 가지 코멘트를 남겨두었습니다. 다음 미션 할 때 확인해보시면 좋을 것 같습니다 
3단계 요구사항에 충족하는 부분이라 머지하도록 하겠습니다!
미션 진행하는 동안 고생하셨습니다! 🙇

2022-07-19 11:53 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Line.java
> +        return ObjectUtils.isEmpty(getSections());
Sections 가 비어있는지는 Sections 에서 판단하게 해도 좋지 않을까요? ☺️

2022-07-19 11:53 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private boolean isDownTerminus(Long stationId) {
Method 분리를 잘 해주셨네요! 👍

2022-07-19 11:53 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/exception/ExceptionController.java
>  public class ExceptionController {
에러 처리를 잘 해주셨네요! 4XX 에러를 잘 정의해주셨는데요.
5XX 에러 부분도 정의해주시면 어떨까요? 또한 로깅을 해주면 에러를 관리하는데 더 효율적일 것 같습니다

2022-07-19 11:53 UTC, HyunSung-Na commented on src/main/java/nextstep/subway/exception/SubwayException.java
> +public class SubwayException extends RuntimeException {
Custom 예외 👍

2022-07-19 11:53 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +     * Given 2개의 지하철역을 등록한다.
해당 부분은 메서드를 통해 충분히 설명하고 있다고 생각하는데요 주석을 줄여보는 건 어떨까요?

2022-07-19 11:53 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    void 지하철_구간_실패_등록된_하행역() {
실패테스트 👍

2022-07-19 11:53 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +        assertAll(
예외 테스트의 경우 assertThatThrownBy 도 고려해보시면 좋을 것 같습니다 ☺️

2022-07-19 11:53 UTC, HyunSung-Na commented on src/test/java/nextstep/subway/acceptance/util/DataBaseCleaner.java
> +    private EntityManager entityManager;
EntityManager 를 사용하셨군요 👍

2022-07-19 11:53 UTC, merged