Step3 리뷰 부탁드립니다.
next-step/atdd-subway-map pull request #480
Opened 2022-07-17 10:11 UTC by chosundeveloper

2022-07-17 16:04 UTC, boorownie requested changes
안녕하세요! 3단계 요구사항 잘 구현해주셨습니다 👍 
인수 테스트 메서드의 중복 제거를 통해 가독성과 재사용성이 좋아진것으로 보이네요!
인수 테스트의 검증 부분을 포함하여 프로덕션 코드에 대한 코멘트를 남겼는데요~
한번 더 고민해보시면 좋을 것 같습니다 :)

2022-07-17 16:04 UTC, boorownie commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +    }
무언가 LineService의 save 메서드와 유사한 부분이 있지는 않나요?
아마 LineService나 SectionService 중 하나만 이 로직을 가져야한다면 어디가 더 좋을까요?

2022-07-17 16:04 UTC, boorownie commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +    }
도메인 검증 로직으로 보이는데 도메인 검증은 해당 도메인에서 진행하도록 하면 어떨까요?

2022-07-18 14:21 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +    }
해당 도메인에서 하는게 좋을 것 같습니다.

2022-07-19 14:04 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +    }
하나만 이 로직을 가져야한다면 lineService가 좋을 것 같습니다. 그런데 line쪽에 section add한다는 부분에서 의존성에 대한 고민이 있어서 이 부분은 고민을 더 해보고 수정하려 합니다.

2022-07-19 14:05 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        stationRepository.findById(lineRequest.getUpStationId()).orElseThrow(() -> new EntityNotFoundException("station.not.found"));
도메인 변경 후 기존 로직에 남아있던 더미 코드입니다.

2022-07-19 14:06 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +        line.addSection(section);
line내부로 line외부보다 관계가 좀 더 명확해지는 것 같습니다.

2022-07-19 14:14 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +    }
Response 관련하여 매칭이 잘 안된 부분이 있어서 쓸데 없는 메서드가 생성되었습니다. 미션 수행하면서 좀 더 다듬어가겠습니다. objectMapper 매핑 관련해서 말입니다.

2022-07-19 15:21 UTC, boorownie requested changes
피드백 잘 반영해주셨습니다!
제가 의도한 방향과 조금 다른 부분이 발견되어 한번 더 수정 요청 드립니다.
진행하시는데 어려움이 있으시거나 코멘트의 의도가 파악이 어려우시다면 언제든 DM 남겨주세요~

2022-07-19 15:21 UTC, boorownie commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +    public void delete(Long lineId, Long sectionDownStationId) {
요구사항으로는 노선의 마지막 구간만 제거가 가능하다고 했습니다.
그렇다면 downStation을 조회해 올 필요 없이 Line 객체만 조회해 온 다음 마지막 구간의 downStation의 id가 요청한 id가 맞는지만 판단한 후 제거해주면 어떨까요?

2022-07-19 15:21 UTC, boorownie commented on src/main/java/nextstep/subway/applicaion/StationService.java
>      }
구간으로 등록되어있는 역을 제거할 경우 어떻게 처리가 될까요?
이 케이스에 대한 인수 테스트가 추가되면 조금 더 명확해질 것 같네요 :)

2022-07-19 15:21 UTC, boorownie commented on src/main/java/nextstep/subway/applicaion/dto/SectionResponse.java
> +
불필요한 개행 발견!

2022-07-19 16:39 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/dto/SectionResponse.java
> +
불필요 개행 삭제합니다.

2022-07-19 16:43 UTC, chosundeveloper commented on src/main/java/nextstep/subway/domain/Line/Line.java
> +        this.sections.addSection(line, upStation, downStation, distance);
네 변경 가능합니다.

2022-07-21 16:31 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +    }
좋은 방법인것 같네요

2022-07-21 16:32 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/dto/LineResponse.java
>      private StationResponse downStation;
objectmapper로 사용하려고 했는데 같은 type일 경우 잘 매핑이 되지 않아서 일단 사용안하는 방법으로 수정했습니다.

2022-07-21 16:32 UTC, chosundeveloper commented on src/main/java/nextstep/subway/utils/ObjectMapUtils.java
> +public class ObjectMapUtils {
일단 보류로 수정합니다.

2022-07-21 17:05 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/StationService.java
>      }
구간 등록 역일 경우 삭제 할 수 없도록 해야할 것 같습니다 인수테스트 추가했습니다.

2022-07-21 17:23 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +        deleteSection(line, downStation);
좋을 것 같습니다

2022-07-21 17:23 UTC, chosundeveloper commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +        return sectionResponse;
일단 mapping이 잘 안되서 수정합니다

2022-07-22 02:09 UTC, boorownie approved these changes
피드백 반영 고생 많으셨습니다!
전반적으로 프로덕션 코드도 깔끔해지고 인수 테스트 코드도 가독성이 많이 좋아졌네요!
2주차 미션도 이어서 화이팅입니다!
이만 머지하겠습니다~

2022-07-22 02:09 UTC, boorownie commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +        line.deleteSection(downStation);
비즈니스 로직이 도메인으로이동 👍 
도메인 레이어로 이동하면서 테스트 하기 조금 더 수월해질 것 같네요 :)

2022-07-22 02:09 UTC, boorownie commented on src/main/java/nextstep/subway/applicaion/SectionService.java
> +        line.addSection(upStation, downStation, sectionRequest.getDistance());
피드백 반영 👍

2022-07-22 02:09 UTC, boorownie commented on src/test/java/nextstep/subway/acceptance/station/StationAcceptanceTest.java
> +    void 구간으로_등록된_지하철역_삭제시_실패_테스트() {
실패를 검증하는 인수 테스트 작성 👍 
메서드 내에서 각 스텝들을 현재 주석으로 표현하셨는데
메서드만으로도 표현이 가능하다면 주석은 제거해주셔도 좋을 것 같습니다!

2022-07-22 02:09 UTC, merged