2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #603
Opened 2023-01-27 11:14 UTC by nooose

2023-01-27 11:22 UTC, nooose commented on src/main/java/subway/domain/Line.java
> +    private Station downStation;
연관관계를 지금 상황에서는 이렇게 매핑하는 것이 맞을까요..?
OneToMany는 아닌 것 같아서요

응답 DTO에서 역 2개를 리스트로 내보내고있습니다.

2023-01-27 11:27 UTC, nooose commented on src/main/java/subway/service/LineService.java
> +    }
해당 노선을 찾거나 수정하거나 삭제할 때 해당 리소스가 있는지 검사하고 싶은데요.
값이 없다면 RestControllerAdvice 를 사용해서 NOT FOUND 응답을 내보내도 괜찮을까요?

2023-01-27 11:31 UTC, nooose commented on src/test/java/subway/LineAcceptanceTest.java
> +@Sql("/setup-station.sql")
노선 테스트를 쉽게하기 위해서 지하철 역을 미리 넣어두고 시작했습니다.

힌트를 보기 전 까지는 이런 방법이 있는지 몰라서 다른 클래스의 메서드를 호출해서 생성하거나 
fixture 를 통해 만들고 그랬습니다.

테스트 시 Sql 어노테이션의 장점이 더 있는지 궁금하네요.

2023-01-27 11:33 UTC, nooose commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
모든 노선 테스트 케이스에서 사용하는 것 같아 상수로 만들었는데요
FIXTURE 를 상수로 관리하기도 하나요?

2023-01-27 11:36 UTC, nooose commented on src/test/java/subway/LineAcceptanceTest.java
> +@Sql("/setup-station.sql")
노선 테스트를 쉽게하기 위해서 지하철 역을 미리 넣어두고 시작했습니다.
힌트를 보기 전 까지는 이런 방법이 있는지 몰라서 다른 클래스의 메서드를 호출해서 생성하거나 
fixture 를 통해 만들고 그랬습니다.

테스트 시 `Sql` 어노테이션의 장점이 더 있는지 궁금하네요.

그리고 저는 DB 초기화를 위해 `DirtiesContext` 어노테이션을 사용했습니다.
`DirtiesContext`를 사용하지 않고 sql 코드 앞 부분에 truncate 를 써두는 방법도 괜찮을 것 같은데
장단점이 있는 건가요..?

2023-01-27 11:38 UTC, nooose commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
테스트 검증 시 간단하게 이름만 체크하고 있는데
보통 모든 필드값을 다 체크를 하나요? 

모든 필드값을 체크한다면 검증하는 부분이 길어질 것 같은데 좋은 방법이 있는지 궁금합니다!

2023-01-28 11:35 UTC, testrace requested changes
안녕하세요 준혁님 😄 
2단계 미션도 빠르게 구현해 주셨네요 👍 
커밋 메시지와 질문을 읽으면서 많은 고민을 하신 게 느껴졌습니다 🔥 

질문 주셨던 부분과 몇 가지 코멘트를 남겼는데요
확인해 주시고 다시 리뷰 요청 부탁드립니다
궁금하신 점이나 의견 있으시면 편하게 DM 주세요!

2023-01-28 11:35 UTC, testrace commented on src/test/java/subway/LineAcceptanceTest.java
> +@Sql("/setup-station.sql")
[공식문서](https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#spring-testing-annotation-dirtiescontext)와 힌트에서도 알 수 있는 부분인데요
테스트간의 격리를 위해 어떤 조치가 필요하냐에 따라 필요한 애너테이션을 적용해 주시면 될 것 같습니다!
`setup-station.sql` 에 insert 대신 truncate 으로 DB를 초기화하는 방법으로도 테스트를 실행해 보시고
DirtiesContext와 Sql에 따라 로그도 같이 참고하시면 좋을 것 같습니다 😄

2023-01-28 11:35 UTC, testrace commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
자주 사용된다면 상수로 관리하는 것도 좋다고 생각합니다!
저도 상수로 선언하는걸 선호하는 편입니다 😄 
다만 FIXTURE는 의도에 맞게 조금 더 구체적인 이름을 부여하면 더 좋을 것 같아요.
```java
private static final Map<String, String> 신분당선;
private static final Map<String, String> 분당선;
```

2023-01-28 11:35 UTC, testrace commented on src/test/java/subway/LineAcceptanceTest.java
> +        params.put("distance", "10");
분당선도 fixture로 만들 수 있지 않을까요?

2023-01-28 11:35 UTC, testrace commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
인수 테스트와 단위 테스트를 분리하면 어떨까요?
단위 테스트에서는 모든 필드의 변화를 검증하고,
인수 테스트에서는 이름만 검증하면 준혁님의 고민이 해결 될 것 같은데 어떻게 생각하세요?

2023-01-28 11:35 UTC, testrace commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(response.jsonPath().getList("name")).doesNotContain(LINE_FIXTURE.get("name"));
매번 `LINE_FIXTURE.get("name")` 같은 코드를 작성하면 
테스트의 의도를 빠르게 파악하기 쉽지 않을 것 같아요.
반복되는 코드를 분리해서 아래와 같이 변경해도 좋을 것 같아요 😄 
```java
assertThat(조회된_노선_목록).doesNotContain(신분당선);
```

2023-01-28 11:35 UTC, testrace commented on src/test/java/subway/LineAcceptanceTest.java
> +    private final static Map<String, String> LINE_FIXTURE;
```suggestion
    private static final Map<String, String> LINE_FIXTURE;
```

2023-01-28 19:12 UTC, nooose commented on src/main/java/subway/repository/StationRepository.java
> +public interface StationRepository extends JpaRepository<Station, Long> {
<img width="281" alt="image" src="https://user-images.githubusercontent.com/36617783/215286586-cd944174-4d50-4660-9b52-d46104cb3231.png">

뭔가 꼬여서 그렇게 보이는 것 같네요..

2023-01-28 19:26 UTC, nooose commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
한글 변수명을 써본적이 없어서 어색한데 너무 괜찮아보이네요. 감사합니다!

2023-01-28 20:06 UTC, nooose commented on src/test/java/subway/LineAcceptanceTest.java
> +@Sql("/setup-station.sql")
감사합니다!

2023-01-28 20:16 UTC, nooose commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
단위 테스트에서 검증이 되었다면 인수테스트에서는 이름만 확인해도 되겠네요.
감사합니다!

2023-01-28 22:27 UTC, testrace commented on src/main/java/subway/repository/StationRepository.java
> +public interface StationRepository extends JpaRepository<Station, Long> {
앗.. 이 피드백은 패스해 주세요!

2023-01-29 07:54 UTC, nooose commented
어떻게 꼬였는지.. push 마다 충돌이 발생해서 rebase 해서 강제 push 했습니다 😅

2023-01-30 03:58 UTC, testrace approved these changes
안녕하세요 준혁님 😄 
커밋 메시지가 인상적입니다 👍 
피드백 반영도 굉장히 잘해주셨네요 💯 
소소하게 코멘트 남겼는데 다음 단계 진행하시면서 확인 부탁드립니다!
진행하시면서 궁금한 점이나 의견 있으시면 편하게 DM 주세요!

2023-01-30 03:58 UTC, testrace commented on src/main/java/subway/exception/GlobalControllerAdvice.java
> +@RestControllerAdvice
`@RestControllerAdvice` 를 활용해 예외를 처리해 주셨네요 👍

2023-01-30 03:58 UTC, testrace commented on src/main/java/subway/exception/SubwayException.java
> +public class SubwayException extends RuntimeException {
커스텀 예외 👍 👍

2023-01-30 03:58 UTC, testrace commented on src/test/java/subway/StationAcceptanceTest.java
> +@Sql("/sql/truncate-tables.sql")
지하철역 인수테스트에도 `@Sql`을 활용해 테스트간의 격리를 해주셨네요 👍 
노선 인수테스트와 중복되는 부분으로 볼 수도 있는데요,
이 부분도 리팩토링 할 수 있을 것 같아요 😄

2023-01-30 03:58 UTC, testrace commented on src/test/java/subway/StationAcceptanceTest.java
> +        var createResponse = 역_생성("강남역").extract();
노선관리 인수테스트처럼 역 명을 fixture로 관리해도 좋을 것 같아요!
지역 변수에 var를 적극적으로 활용하시는 점이 좋네요 💯

2023-01-30 03:58 UTC, testrace commented on src/test/java/subway/domain/LineTest.java
> +        assertAll(() -> {
assertAll 👍

2023-01-30 03:58 UTC, testrace commented on src/test/resources/sql/truncate-tables.sql
> +SET REFERENTIAL_INTEGRITY TRUE;
truncate 를 활용한 테스트 격리 👍

2023-01-30 03:58 UTC, merged