🚀 2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #617
Opened 2023-01-28 10:09 UTC by boradol

안녕하세요. 리뷰어님 🙏🏻
리뷰 잘 부탁드립니다.

- [x] 지하철 노선 생성
- [x] 지하철 노선 목록 조회
- [x] 지하철 노선 조회
- [x] 지하철 노선 수정
- [x] 지하철 노선 삭제

2023-01-29 01:51 UTC, kang-hyungu requested changes
보라님 미션 잘 수행해주셨네요.
몇 가지 챙겨보면 좋을 부분에 코멘트 남겼습니다.
수정해보시고 리뷰 재요청주시기 바랍니다~!

2023-01-29 01:51 UTC, kang-hyungu commented on src/main/java/subway/line/LineResponse.java
> +    public static LineResponse createLineResponse(Line line) {
리턴 타입이 있으니 메서드명은 간결하게 작성해도 좋을 것 같네요

```suggestion
    public static LineResponse create(Line line) {
```

2023-01-29 01:51 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +        Station upStation = stationRepository.findById(request.getUpStationId()).orElseThrow();
1. stationRepository.findById(...) 메서드가 반복적으로 사용되고 있네요. 중복을 줄이기 위해 StationService에서 관리하도록 만들면 어떨까요?
2. orElseThrow 메서드가 예외에 대한 아무 처리를 안 하고 있네요. 실제 문제가 발생했을 때 파악이 어려울 수 있으니 적절한 예외를 처리하도록 만드는게 어떨까요?

2023-01-29 01:51 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +    public LineResponse findOneLine(Long id) {
클래스명에 Line이 들어가 있으니 메서드명에 반복해서 적어줄 필요는 없어보여요. 간결하게 findOne으로 해도 충분하지 않을까요?

2023-01-29 01:51 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +    public List<LineResponse> findAllLines() {
find 계열의 메서드도 트랜잭션의 readonly 기능을 적용하면 어떨까요?

2023-01-29 01:51 UTC, kang-hyungu commented on src/test/java/subway/LineAcceptanceTest.java
> +        createLineExtractableResponse(new LineRequest("신분당선", "bg-red-600", (long) 1, (long) 2, 10));
매번 타입 캐스팅을 하기 불편하니 L을 붙여주면 어떨까요
```suggestion
        createLineExtractableResponse(new LineRequest("신분당선", "bg-red-600", 1L, 2L, 10));
```

2023-01-29 01:51 UTC, kang-hyungu commented on src/test/java/subway/LineAcceptanceTest.java
> +                new LineRequest("신분당선", "bg-red-600", (long) 1, (long) 2, 10)
LineRequest 객체 생성이 테스트 케이스마다 반복적으로 나오네요. 팩터리 메서드를 추가해서 중복을 제거해보면 어떨까요?

2023-01-29 01:51 UTC, kang-hyungu commented on src/test/java/subway/LineAcceptanceTest.java
> +        ExtractableResponse<Response> response = RestAssured.given().log().all()
RestAssured를 사용한 http 호출이 반복해서 나타나고 있네요.
http method 기준으로 메서드를 만들고 제네릭을 활용해서 반복되는 호출을 줄여보면 Line 인수 테스트 뿐만 아니라 Station 인수 테스트에서도 활용하기 좋을거에요.

2023-01-29 15:24 UTC, boradol commented on src/test/java/subway/LineAcceptanceTest.java
> +        ExtractableResponse<Response> response = RestAssured.given().log().all()
이부분은 고민해 보았지만 제네릭을 활용해서는 반영이 제대로 된것같지 않습니다. 혹시 좋은 방향이 있을까요 ?

2023-01-29 15:26 UTC, boradol commented
전반적으로 리뷰주신 내용 반영해보았습니다.
빠르게 리뷰 해주셔서 감사합니다.
하지만 RestRessured 부분에서 반영을 제대로 못한 것 같아서 조언 부탁드립니다.
제가 실력이 많이 부족하여 많은 도움 부탁드립니다. 🙏🏻

2023-01-30 03:16 UTC, kang-hyungu approved these changes
보라님 피드백 반영 잘 해주셨습니다.
코드가 정말 깔끔해졌네요.
질문 주신 내용은 코멘트 남겼습니다. 추가 피드백과 같이 다음 미션에 반영해보시기 바랍니다.
pr은 머지 처리할게요. 수고하셨습니다.

2023-01-30 03:16 UTC, kang-hyungu commented on src/main/java/subway/line/Line.java
> +    public Line() {
JPA를 사용하다보니 기본 생성자를 만들 수 밖에 없겠네요. 제거하기 어렵다면 접근을 최대한 막아주는건 어떨까요?
public 대신 protected를 쓰는 걸 추천합니다.

2023-01-30 03:16 UTC, kang-hyungu commented on src/main/java/subway/line/Line.java
> +    public Line updateLine(LineRequest lineRequest) {
도메인 클래스는 dto를 의존하면 안 됩니다.
계층형 레이어의 의존 단계를 위반하게 됩니다.
LineRequest는 프레젠테이션과 서비스 레이어 사이에서만 사용되고 있는데 도메인 레이어까지 침범하면 변경사항이 생겼을 때 영향을 받게 됩니다.
필요한 값만 전달하도록 바꾸시는걸 추천합니다.

2023-01-30 03:16 UTC, kang-hyungu commented on src/test/java/subway/LineAcceptanceTest.java
> +    private static ExtractableResponse<Response> get(String url) {
대략 이런 구조로 만들 수 있겠네요.

```java
    public static <T, R> R get(final String url, final T requestBody, final Class<R> responseType) {
        return RestAssured
                .post("...")
                .then()
                .extract()
                .as(responseType);
    }
```

2023-01-30 03:17 UTC, merged