Step3
next-step/atdd-subway-map pull request #654
Opened 2023-01-29 18:57 UTC by Sanghou

## 요약
 1. 지하철 노선 기능 추가하기 
 2. 지하철 역 전체 테스트 실패하던 것에 테스트 격리 부여하기
 3. Station 테스트 관련 유틸은 다른 파일로 분리, Lane 테스트 관련 유틸은 Test 내부에 넣기 
 (어떤 테스트 코드가 더 읽고 파악하기 쉬운지 아직 결정하지 못해서 두 가지 모두 만들어보았습니다)

## 질문
- 노선 수정 기능을 추가하다보니 Lane 엔티티에 setter가 3개나 추가되어버렸는데 이 부분은 혹시 다른 방법이 있을까요? 
같은 엔티티로 취급하려면 id가 같아야 할 것 같아 setter를 추가하게 되었습니다.

- inboundStation과 outboundStation을 Station 정보를 저장하는데 Mocks.MockStation 을 이용하다보니 실제 노선이 DB에 저장될 때, Station Table에 관련 엔티티가 없어서 에러가 떴습니다. 
이를 해결하기 위해서 (cascade = CascadeType.ALL)를 설정했는데 다시 생각해보니 보니 테스트코드가 실제 메인 코드에 영향을 주는 것 같아서 다른 방법이 없을까 질문드립니다.
 당장 떠오르는 방법은 실제 "Mocks.Stations.서울역" 같은 변수도 Test 코드 시작할 때 DB에 save해주는 것인데, 이렇게 된다면 비즈니스로직이 복잡해지고 참조하는 객체가 많아지면 모든 객체를 생성하느라 코스트가 더 사용될 것 같아서 좋은 방법 같지 않습니다.
 (혹은 Station 대신 String으로 역 이름만 저장하는 것도 있는데 JPA가 지향하는 바랑은 먼 것 같아서 제외했습니다.)
 혹시 다른 방법이 있을까요 👀 

이번에 스프링과 JPA를 처음 공부해서 쓰다보니 어색한 부분도 많아서 질문을 너무 많이 드리는 것 같네요 🥲 🥲

2023-01-29 19:02 UTC, Sanghou commented on src/test/java/subway/StationAcceptanceTest.java
>              .extract();
질문 3. 
 StationTestUtils로 생성 부분을 빼려다가 궁금증이 생겼습니다. 
 실제 검증하려는 부분의 코드를 다른 utils 함수를 이용해서 검증하는게 맞는가 하는 의구심이 들었습니다.
 같은 클래스의 작은 함수라면 같은 테스트 코드 내에 있어서 변경 가능성이 더 적다고 생각해서 lane관련 테스트는 "노선_조회()"같은 유틸리티 함수를 그대로 사용했습니다. 
 그러나 지금처럼 StationTestUtils와 같은 다른 클래스를 이용하면 중복 코드는 줄어들지만 실제 검증하려는 부분을 확인하려면 외부 파일을 열어봐야해서 과연 가독성이 좋을까? 하는 생각이 들어서 멘토님의 의견을 여쭤봅니다.

2023-01-30 00:39 UTC, catsbi requested changes
상호님 2단계 노선 관리 미션 잘 구현해주셨어요. 미션 제출을 Step3로 해주셨는데, 실습은 사실상 0Step으로 보고 있어서 Step2가 좀 더 적절할 것 같네요. 리퀘스트 타이틀은 제가 Step2로 변경했습니다. 

API 만드시고 테스트 케이스를 구현한 것도 확인해봤는데, 피드백을 참고해서 리팩토링을 한 번 해보면 더 좋아질 것 같아서 코멘트 남겨드렸으니 확인 후 다시 리뷰요청 부탁드립니다 👍 

질문에 대해서는 코멘트로 남겨놨습니다 ㅎㅎ

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/Lane.java
> +  @Column(name = "id", nullable = false)
불필요한 애노테이션입니다 @Id 애노테이션이 붙으면 자동으로 not null이 되고, id도 별도로 커스텀한 필드명을 지정해줄 게 아니라면, 필드명을 따라가기에 지우셔도 될 것 같네요!

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/Lane.java
> +public class Lane {
지하철 노선이면 Lane보다는 Line이 좀 더 적절하지 않을까 생각해봅니다 🙄

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/Lane.java
> +import javax.persistence.*;
import 구문에 `*` 사용은 지양해주세요. 코드에서 사용하는 모듈들이 무엇이 있는지 파악하기 힘들어서 가독성이 낮아지기도 하고, 실제로 모든 모듈을 불러오는게 아닌데, 다 불러오는 문제도 있습니다.

IDE 옵션에서 끌 수 있을 꺼에요 ㅎ

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/Lane.java
> +  private String name; // 노선 번호
불필요한 주석은 제거해주는게 좋습니다!

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/Lane.java
> +  @Column(name = "name")
`(name = "name")` 속성은 없어도 될 것 같네요 ㅎ

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/Lane.java
> +  }
수정 기능을 위해 setter를 만드셨다고 했는데, 우선 수정이라면 기존에 존재하는 노선을 수정하는 것이겠죠? 그렇기 때문에 DB에 저장된 노선정보를 가져와서 수정하는 것이기에 ID를 set하는 메서드가 필요하지 않을 것 같네요. 오히려 setter를 통해 아이디가 변경되어 isNew 분기에서 true가 반환되어 새로운 엔티티로 등록될 확률이 높아지겠죠.

그리고 그 밖에 수정이 필요한 필드들에 대해서도set이라는 이름보다는 좀 더 의미있는 이름으로, 수정의 폭을 제약하는게 좋습니다.

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/LaneController.java
> +  private LaneService laneService;
final을 붙히면 생성자 주입을 강제하게되서 좀 더 확실하게 주입받을 수 있습니다.

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/LaneController.java
> +  // 노선 생성
주석을 작성하려면 차라리 javadoc 규격을 맞춰주시면 좋습니다.

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/LaneController.java
> +  @PostMapping("/lane")
Rest API 설계시 Resource 이름은 단수보다는 복수로 짓는게 좋습니다. (Line -> Lines)

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/LaneController.java
> +    if (response == null) {
반환값으로 null이 올 수 있다는 것은 항상 NPE를 경계하고 Null Check를 해야한다는 것이죠. 
어떻게 개선할 수 있을까요?

2023-01-30 00:39 UTC, catsbi commented on src/main/java/subway/lane/LaneResponse.java
> +public class LaneResponse {
해당 응답 결과가 노선이 어떤 지하철역을 포함하는지에 대한 정보는 없어도 될까요?

2023-01-30 00:39 UTC, catsbi commented on src/test/java/subway/LaneAcceptanceTest.java
> +  }
이런 유틸리티 API들은 별도의 클래스로 분리하면 어떨까요? 
테스트 클래스에서 테스트에만 좀 더 집중할 수 있어지지 않을까요?

2023-01-30 00:39 UTC, catsbi commented on src/test/java/subway/StationAcceptanceTest.java
>              .extract();
우선 같은 패키지내에 존재한다는 것과, 해당 유틸리티 클래스의 메서드의 접근제한이 해당 클래스에서(StationAcceptanceTest) 접근이 가능하다는 것은, 이용을 해도 된다는 의미이고 해당 유틸리티 클래스에서는 나한테 접근가능한 범위의 클래스들은 나를 신뢰하고 써도 된다는 의미이기도 합니다. 

또한 가독성은 다른 클래스에 존재하는 메서드의 로직을 뜯어 볼 때 낮아지는게 아니라, 메서드의 시그니처가  불분명할 때 낮아지는 것입니다. 반대로 가독성이 높다는 것은 해당 메서드를 사용하는 테스트 메서드 내에서 작성된 메서드만 보고 이게 무슨 기능을 하는구나 라는것을 알 수 있을때죠. 

```java
ExtractableResponse<Response> response = StationTestUtils.지하철역_생성(MockStation.강남역)
```

이런식으로 사용을 하고 있다고 할 때 우리는 저 메서드가 내부적으로 어떻게 돌아가는진 모르고 알 필요도 없고, 
강남역 지하철역을 생성하고 그 응답결과를 반환한다. 에만 집중하면 되는 것입니다. 😀

2023-01-30 00:39 UTC, catsbi commented on src/test/java/subway/StationTestUtils.java
> +  public static List<String> 지하철역_조회() {
메서드명을 한글,영어 무엇을 사용해도 되는데 이왕이면 통일시켜주는게 좋습니다!

2023-01-30 00:39 UTC, catsbi commented on src/test/java/subway/StationTestUtils.java
> +public class StationTestUtils {
유틸성 클래스라면 별도의 인스턴스를 생성할 필요가 없기 때문에 생성자 제한을 통해 인스턴스 생성을 막아주는게 어떨까요?

2023-01-30 00:39 UTC, catsbi commented
Q. inboundStation과 outboundStation을 Station 정보를 저장하는데 Mocks.MockStation 을 이용하다보니 실제 노선이 DB에 저장될 때, Station Table에 관련 엔티티가 없어서 에러가 떴습니다.이를 해결하기 위해서 (cascade = CascadeType.ALL)를 설정했는데 다시 생각해보니 보니 테스트코드가 실제 메인 코드에 영향을 주는 것 같아서 다른 방법이 없을까 질문드립니다.당장 떠오르는 방법은 실제 "Mocks.Stations.서울역" 같은 변수도 Test 코드 시작할 때 DB에 save해주는 것인데, 이렇게 된다면 비즈니스로직이 복잡해지고 참조하는 객체가 많아지면 모든 객체를 생성하느라 코스트가 더 사용될 것 같아서 좋은 방법 같지 않습니다.(혹은 Station 대신 String으로 역 이름만 저장하는 것도 있는데 JPA가 지향하는 바랑은 먼 것 같아서 제외했습니다.)혹시 다른 방법이 있을까요 👀우

---

A. 최우선 명제는 테스트때문에 프로덕션 코드가 수정되거나 기능이 추가되서는 안된다입니다.   그리고 노선 정보를 저장하면서 Station을 세팅해주려면 당연히 사전에 전철역 정보는 등록되어 있어야겠죠 ㅎㅎ 비즈니스 적으로 볼 때 전철역들이 이미 존재할 때 전철역들을 연결해서 노선을 만드는 것이니까요.오히려 노선정보를 저장할 때 존재하지 않던 지하철역들이 같이 저장되는게 더 이상하지 않을까요!  그래서 테스트 코드에서는 이런 픽스쳐 준비를 위해서 @BeforeEach 등의 애노테이션을 제공하고 있습니다. 그렇다면 이 부분을 MockStation과 어떻게 연계시키느냐인데, MockStation에서는 말 그대로 매직리터럴 같이 매번 직접 타이핑하면 휴먼에러가 발생되기 쉬운 정보들을 변수 혹은 상수로 관리하는 정도만 해주면 됩니다. 테스트 클래스에서는 이렇게 정의되어있는 Mock 정보들을 이용해서 테스트 시작 전 DB에 저장하는 작업들을 해놓고, 실제 테스트에서는 해당 기능을 이용하기 위한 사전준비가 된 상태에서 핵심 비즈니스에만 집중하면 됩니다.  이 부분에 대해서 방식이 궁금하다면, 고민을 최대한 해본 뒤 그 다음 다른 수강생분들이 어떻게 만들었나 참고를 하는 것도 많은 도움이 될 것입니다 ㅎㅎ

2023-01-30 17:00 UTC, Sanghou commented on src/test/java/subway/StationAcceptanceTest.java
>              .extract();
같은 패키지 내에 존재하는 클래스들에 대한 신뢰성은 전혀 생각해보지 못했네요!

유틸리티 클래스에 대한 신뢰성을 왜 가지지 못했을까 생각을해보니 회사에서 사용하던 코드의 유틸리티 함수들이 더 큰 범위의 패키지에서 제공되다보니 여러 테스트 메소드들에서 사용하고, 사용할 때 변형이 필요하면 변형된 함수들이 하나씩 생성되다보니 필요한 유틸리티를 찾을 때 해당 유틸리티를 열어봐야했던 것에 영향이 조금 있는 것 같습니다.

 제가 오히려 코드를 신뢰하지 못하고 있어서 그렇게 느꼈을 수 있겠네요! 감사합니다 😀 😀

2023-01-30 17:03 UTC, Sanghou commented on src/main/java/subway/lane/Lane.java
> +public class Lane {
앗 그렇네요. lane은 정해진 코스라 생각해서 지하철 노선도 정해진 코스라 그럴 것 같았는데 다시 찾아보니 line이 맞았네요 😅

2023-01-30 17:22 UTC, Sanghou commented on src/main/java/subway/lane/Lane.java
> +  @Column(name = "name")
이것도 id에서 말씀해주신 중복되는 이름이 아니니 지우는게 맞겠네요! 👍

2023-01-30 18:18 UTC, Sanghou commented on src/main/java/subway/lane/Lane.java
> +  }
이건 setter를 이용하기보다는 다른 updateLine같은 함수를 선언하는게 더 좋았을 것 같네요!
감사합니다 :)

2023-01-30 18:32 UTC, Sanghou commented on src/main/java/subway/lane/LaneController.java
> +    if (response == null) {
Null이 없는게 베스트라고 생각하는데 show 결과에 null이 없을 순 없을 것 같네요.
 그렇다면 showLane에 @Nullable 어노테이션을 이용하거나 반환값에 조금 더 명시적으로 표현되는 Optional이 조금 더 좋은 선택지일 것 같습니다!
 Optional로 하려고 하는데 튜터님의 의견은 어떠신가요?

2023-01-30 18:54 UTC, Sanghou commented on src/main/java/subway/lane/LaneResponse.java
> +public class LaneResponse {
당장 검증할 때 안 써서 빼뒀는데, 실제로 유저가 쓴다고 하면 결과값에 다 포함이 되었어야했네요 🤔 
관련해서 추가하고 테스트에도 추가해두었습니다.

2023-01-30 19:01 UTC, Sanghou commented on src/test/java/subway/StationTestUtils.java
> +  public static List<String> 지하철역_조회() {
한글 써보니 구현에 더 집중이 되는 것 같네요! 테스트에 집중할 수 있게 테스트랑 테스트 유틸은 한글로 작성하도록 통일하려합니다! 👍

2023-01-30 19:58 UTC, Sanghou commented
> Q. inboundStation과 outboundStation을 Station 정보를 저장하는데 Mocks.MockStation 을 이용하다보니 실제 노선이 DB에 저장될 때, Station Table에 관련 엔티티가 없어서 에러가 떴습니다.이를 해결하기 위해서 (cascade = CascadeType.ALL)를 설정했는데 다시 생각해보니 보니 테스트코드가 실제 메인 코드에 영향을 주는 것 같아서 다른 방법이 없을까 질문드립니다.당장 떠오르는 방법은 실제 "Mocks.Stations.서울역" 같은 변수도 Test 코드 시작할 때 DB에 save해주는 것인데, 이렇게 된다면 비즈니스로직이 복잡해지고 참조하는 객체가 많아지면 모든 객체를 생성하느라 코스트가 더 사용될 것 같아서 좋은 방법 같지 않습니다.(혹은 Station 대신 String으로 역 이름만 저장하는 것도 있는데 JPA가 지향하는 바랑은 먼 것 같아서 제외했습니다.)혹시 다른 방법이 있을까요 👀우
> 
> A. 최우선 명제는 테스트때문에 프로덕션 코드가 수정되거나 기능이 추가되서는 안된다입니다. 그리고 노선 정보를 저장하면서 Station을 세팅해주려면 당연히 사전에 전철역 정보는 등록되어 있어야겠죠 ㅎㅎ 비즈니스 적으로 볼 때 전철역들이 이미 존재할 때 전철역들을 연결해서 노선을 만드는 것이니까요.오히려 노선정보를 저장할 때 존재하지 않던 지하철역들이 같이 저장되는게 더 이상하지 않을까요! 그래서 테스트 코드에서는 이런 픽스쳐 준비를 위해서 @beforeeach 등의 애노테이션을 제공하고 있습니다. 그렇다면 이 부분을 MockStation과 어떻게 연계시키느냐인데, MockStation에서는 말 그대로 매직리터럴 같이 매번 직접 타이핑하면 휴먼에러가 발생되기 쉬운 정보들을 변수 혹은 상수로 관리하는 정도만 해주면 됩니다. 테스트 클래스에서는 이렇게 정의되어있는 Mock 정보들을 이용해서 테스트 시작 전 DB에 저장하는 작업들을 해놓고, 실제 테스트에서는 해당 기능을 이용하기 위한 사전준비가 된 상태에서 핵심 비즈니스에만 집중하면 됩니다. 이 부분에 대해서 방식이 궁금하다면, 고민을 최대한 해본 뒤 그 다음 다른 수강생분들이 어떻게 만들었나 참고를 하는 것도 많은 도움이 될 것입니다 ㅎㅎ

---

 시도 내역

1. BeforeAll을 이용해서 미리 MockStation들을 미리 등록하기 
Port를 지정할 수 없어서 not connect 에러가 발생하여 조금 더 찾아보았는데 작년에 다른 분도 같은 고생을 하셨군요 😅😅 
https://github.com/quarkusio/quarkus/issues/7690
=> 사용 불가능

2. BeforeEach로 관리하기.
생성까지는 성공했지만, 실제 사용할 때 **MockStation.서울대입구역**과 같은 형식으로 호출을 할 수 없어서 매번 조회가 필요함
=> 역 조회 관련해서 id가 아닌 역 이름이나 다른 정보를 기반으로 조회하는 방법이 필요함

3. Line Request에는 역 이름 정보를 requestDTO로 받고 (Station -> String) 실제 LineService나 LineController에서 이름을 기반으로 해당하는 역을 조회해서 Line을 저장한다.
=> Service나 Controller 내부에서 Station이 실제 존재하는지 검증 가능함. 생성만 미리 해두면 조회가 가능하다
(2번 방법의 발전된 방법으로 보이네요)
정도가 있을 것 같네요!

3번 방법으로 코드를 변경해서 해보겠습니다 🙇 🙇

2023-01-30 20:35 UTC, Sanghou commented
생각보다 작은 코드라고 생각했는데도 고민해야할 포인트들이 무척이나 많네요 👍 

- Mock 객체가 DB에 저장되어있어야한다면 어떻게 관리해줄까? 이 때 MockStation과 실제 DB에 저장되어버린 값은 다른 값인데 어떻게 처리해줄지에 대한 고민
- 코드 가독성에 대한 고민 (패키지 구조와 신뢰성. 좋은 패키지를 유지하려면 믿을 수 있는 범위를 기반으로?)
- Null처리에 대한 고민 (Lane에서 Station 조회 시 없는 Station인 경우 처리도 고민해볼 필요가 있겠네요)
- 변화가 적게 코드를 수정하는 방법 (Setter보다는 다른 update 메소드를, utils는 private한 생성자를 이용해서 생성이 불가능하게 하기)

2023-01-30 20:39 UTC, Sanghou commented
다시보니.. 명세를 잘못 봤군요
생성
{
 name,
 color,
 upStationId,
 downStationId,
 distance
}

형식으로 받아야했네요 😓 😓

2023-01-31 04:55 UTC, catsbi commented on src/main/java/subway/lane/LaneController.java
> +    if (response == null) {
어느 방향이던 상호님이 생각하신대로 하셔도 문제 없습니다. 방법은 다양하니까요 ㅎㅎ 저는 놓치거나 더 나은 방향이 있을때 권유하는 정도로만 하려고 하고 있습니다. 

논외로 제가 코멘트를 남기며 염두했던 부분도 Optional이긴 했습니다 👍

2023-01-31 09:10 UTC, catsbi commented on src/main/java/subway/line/LineController.java
> +    return ResponseEntity.ok().body(lineService.saveLine(
메서드 파라미터를 2개 이상 작성하는것은 지양하는게 좋습니다. 파라미터 갯수가 늘 수록 코드에 대한 가독성이 낮아지고 잘못된 파라미터를 전달할 확률이 높아지죠. 

객체지향 생활체조원칙에서는 2개를 초과하는 매개변수를 전달하는 것을 금지하고있기도 하죠 ㅎㅎ

2023-01-31 09:12 UTC, catsbi commented on src/main/java/subway/line/LineController.java
> +   * @return 모든 지하철 모든의 정보를 반환한다.
모든의 정보는 잘못 기입된 것 같네요 ㅎㅎ

2023-01-31 09:16 UTC, catsbi commented on src/main/java/subway/line/LineService.java
> +    Optional<Station> outbound = stationRepository.findById(downStationId);
전철역 조회를 LineService와 StationService중 어디서 하는게 더 적절할까요?

2023-01-31 09:17 UTC, catsbi commented on src/main/java/subway/line/LineService.java
> +        .map(this::createServiceResponse);
map을 두 번 호출해야 하는 이유가 있을까요?

2023-01-31 09:17 UTC, catsbi commented on src/main/java/subway/line/LineService.java
> +    return new LineResponse(line.getId(), line.getName(), line.getColor(), line.getUpStation(), line.getDownStation(), line.getDistance());
응답 객체를 만드는 책임은 서비스에 있을까요 LineResponse에 있을까요?

2023-01-31 09:20 UTC, catsbi commented on src/test/java/subway/LineTestUtils.java
> +  public static Line 지하철_노선_생성(String name, String color, Long inbound, Long outbound, Long distance) {
Request DTO를 test fixture로 준비해둔다면, 매개변수를 하나하나 받지 않아도 되지 않을까요 ㅎㅎ

2023-01-31 09:20 UTC, catsbi commented on src/test/java/subway/LineTestUtils.java
> +  public static Line 지하철_역_노선_모두_생성(String name, String color, String upStation, String downStation, Long distance) {
이름만 봐서는 여러 개의 노선을 생성하는 API로 보이는데 실제로는 하나의 지하철 노선만 만들고 있네요 🤔

2023-01-31 09:22 UTC, merged

2023-02-01 17:20 UTC, Sanghou commented on src/main/java/subway/line/LineService.java
> +    return new LineResponse(line.getId(), line.getName(), line.getColor(), line.getUpStation(), line.getDownStation(), line.getDistance());
LineResponse에서 생성할 수 있도록 하는게 더 좋겠네요
LineService가 할 일은 아닌 것 같습니다

2023-02-01 17:35 UTC, Sanghou commented on src/main/java/subway/line/Line.java
> +  @ManyToOne(cascade = CascadeType.ALL)
앗 이 부분을 빼려고 LineService에서 repository를 부르며 생성까지 확인해보려했는데 😅 
이 부분을 지우는 것을 빼먹었네요

2023-02-01 17:46 UTC, Sanghou commented on src/main/java/subway/line/LineService.java
> +    Optional<Station> outbound = stationRepository.findById(downStationId);
Service Layer에서는 ResponseDTO만 반환해주는게 좋을 것 같아서, 실제 entity인 Station을 얻기 위해서 repository를 바로 읽으려 했습니다.
 어떤 엔티티인지 알려면 id를 반드시 포함되어야할텐데, Response가 다른 service에서도 쓰일 수 있기 때문에 
모든 Serviece 레이어에서 반환되는 Response에 id를 첨부하는 것도 조금 이상한 것 같아서, Service Layer에서 DTO를 만들어서 같은 Service Layer끼리 소통할 때 entity로 올바르게 변환해서 사용할 수 있는 방법이 있을까요?

2023-02-01 17:47 UTC, Sanghou commented on src/test/java/subway/LineTestUtils.java
> +  public static Line 지하철_역_노선_모두_생성(String name, String color, String upStation, String downStation, Long distance) {
요청된 지하철역과 노선 정보 모두 생성한다는 의미였는데, 별로 좋지 않은 네이밍이었네요! 🥇