1단계 지하철역 인수 테스트 작성
next-step/atdd-subway-map pull request #655
Opened 2023-01-30 02:00 UTC by yjkim81

1단계 지하철역 인수 테스트 피드백 부탁 드립니다.

2023-01-30 13:09 UTC, heesunjeong requested changes
1단계 미션도 잘 구현해주셨네요 👍 
다음 단계 진행하시기 전에 몇가지 참고해보시면 좋을 것 같은 부분에 코멘트를 추가했는데 확인 부탁드려요! 
궁금하신 점이나 나누고 싶은 이야기가 있으시다면 언제든지 편하게 코멘트나 메세지 남겨주세요 :)

2023-01-30 13:09 UTC, heesunjeong commented on src/test/java/subway/StationAcceptanceTest.java
> +    JsonPath getAllStations() {
접근제어자는 최소한으로 해주시면 어떨까요?

2023-01-30 13:09 UTC, heesunjeong commented on src/test/java/subway/StationAcceptanceTest.java
> +    void deleteStation(Long id) {
인수 테스트의 가독성을 위해 메소드로 추출해주셨군요 👍

2023-02-01 00:06 UTC, heesunjeong approved these changes
피드백 반영 잘 해주셨습니다 💯 💯  
가독성이 많이 좋아진 것 같아요 👍 
이번 단계는 이만 머지하도록 하겠습니다! 이어서 다음단계 진행해주시면 됩니다! 🔥 🔥

2023-02-01 00:06 UTC, heesunjeong commented on src/test/java/subway/StationAcceptanceTest.java
> +        //Given 2개의 지하철역을 생성하고, (createStation() test 에서 하나 이미 생성)
이 테스트 하나만 실행할때는 테스트가 실패하고 있네요 🥲
이 부분에 대해서는 다음단계에 함께 고려해보시면 좋을 것 같습니다 :)

2023-02-01 00:06 UTC, merged

2023-02-01 02:02 UTC, yjkim81 commented on src/test/java/subway/StationAcceptanceTest.java
> +        //Given 2개의 지하철역을 생성하고, (createStation() test 에서 하나 이미 생성)
이 부분을 인지는 하고 있었습니다. 전체 테스트 실행 시 에는 CreateStation 에서 이미 하나가 생성이 되어서 에러가 나지 않게 되어있고, 개별적인 테스트 실행 시 에는 개수가 맞지 않아 에러가 나게 되어있습니다. 

1) 데이터 무결성을 위해 이전에 생성된 지하철 역을 삭제하는 코드를 추가한다. 

2) 지하철 역을 2개 생성 하고, 이전에 생성된 지하철 역의 개수 + 2 로 테스트 코드를 작성한다. 

3) 피드백을 주고 받다 보니, 생성한 2개의 지하철 역 만 조회하는 방법도 있긴 하네요. 
 * Given 2개의 지하철 역을 생성하고
 * When 지하철 역 목록을 조회하면   >> 생성한 지하철 역 목록을 조회하면 으로 수정하면  명확하고. 
 * Then 2개의 지하철 역을 응답 받는다

혹시 제가 인지한 문제가 아닌 다른 문제인지? 좋은 의견 있으시면 피드백 부탁 드립니다. 
감사합니다^^

2023-02-01 02:03 UTC, yjkim81 commented on src/test/java/subway/StationAcceptanceTest.java
> +        //Given 2개의 지하철역을 생성하고, (createStation() test 에서 하나 이미 생성)
> 이 테스트 하나만 실행할때는 테스트가 실패하고 있네요 🥲 이 부분에 대해서는 다음단계에 함께 고려해보시면 좋을 것 같습니다 :)

이 부분을 인지는 하고 있었습니다. 전체 테스트 실행 시 에는 CreateStation 에서 이미 하나가 생성이 되어서 에러가 나지 않게 되어있고, 개별적인 테스트 실행 시 에는 개수가 맞지 않아 에러가 나게 되어있습니다.

데이터 무결성을 위해 이전에 생성된 지하철 역을 삭제하는 코드를 추가한다.

지하철 역을 2개 생성 하고, 이전에 생성된 지하철 역의 개수 + 2 로 테스트 코드를 작성한다.

피드백을 주고 받다 보니, 생성한 2개의 지하철 역 만 조회하는 방법도 있긴 하네요.

Given 2개의 지하철 역을 생성하고
When 지하철 역 목록을 조회하면 >> 생성한 지하철 역 목록을 조회하면 으로 수정하면 명확하고.
Then 2개의 지하철 역을 응답 받는다
혹시 제가 인지한 문제가 아닌 다른 문제인지? 좋은 의견 있으시면 피드백 부탁 드립니다.
감사합니다^^

2023-02-01 10:39 UTC, heesunjeong commented on src/test/java/subway/StationAcceptanceTest.java
> +        //Given 2개의 지하철역을 생성하고, (createStation() test 에서 하나 이미 생성)
관련해서 이미 인지하시고 고민해보셨군요! 👍 

- `데이터 무결성을 위해 이전에 생성된 지하철 역을 삭제하는 코드를 추가한다.` 이 방법을 사용하면 테스트의 순서에 상관없이, DB 데이터에 영향없이 항상 성공하는 테스트를 작성해볼 수 있겠네요!
- `지하철 역을 2개 생성 하고, 이전에 생성된 지하철 역의 개수 + 2 로 테스트 코드를 작성한다.` 이 방법은 기존 데이터가 있다는 가정하에 이렇게 작성해볼 수 있을 것 같은데요. 그렇다면 테스트 코드 작성이 조금 더 복잡해질 수 있을 것 같아요.
- `생성한 2개의 지하철 역 만 조회하는 방법도 있긴 하네요.` 이 방법은 이 테스트가 전체 목록 조회 API가 원하는 결과대로 동작하는지를 확인하는 테스트인데요, 전체를 조회했는지 검증하는게 아니게 될 것 같아요..!

테스트가 다른 테스트에 영향을 받는다면 금방 깨지기 쉬워지는데요, 
이를 방지하기위한 방법 중 하나로 인수테스트에서는 테스트 실행 전에 디비를 초기화 해줄 수 있을 것 같아요 :) 
 
다음 단계 미션 요구사항으로 '테스트 격리'와 관련된 내용을 함께 실습해보실 수 있으니 다음 단계에 적용해보시면 좋을 것 같습니다!