🚀 2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #659
Opened 2023-01-30 13:24 UTC by hyungkiShin

코드리뷰 부탁드립니다 🙏

2023-01-31 11:38 UTC, parkeeseul requested changes
2단계 미션 잘 진행해 주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다 😄 
즐거운 저녁 되시고 화이팅 입니다 🔥

2023-01-31 11:38 UTC, parkeeseul commented on src/test/java/subway/LineAcceptanceTest.java
> +@Sql("/insert-station.sql")
`@DirtiesContext` 를 통해 테스트 격리를 해 주셨네요! 👍 
`@DirtiesContext`는 컨택스트를 다시 로드하기 때문에 테스트 실행 시간이 오래 걸린다는 단점이 있는데요,
이 부분에 대해서는 한번 고민해 보면 좋을 것 같아요 😄

2023-01-31 11:38 UTC, parkeeseul commented on src/test/java/subway/LineAcceptanceTest.java
> +    private static final String NAME2 = "이호선";
NAME, NAME2 보다는 신분당선, 이호선을 구분할 수 있는 의미있는 네이밍을 해주면 어떨까요?

2023-01-31 11:38 UTC, parkeeseul commented on src/test/java/subway/LineAcceptanceTest.java
> +        LineResponse createdLine = 지하철노선_생성(신분당선);
지하철 노선 생성에 대한 테스트이니
해당 부분은 when절이 되어야 하지 않을까요? 😄

2023-01-31 11:38 UTC, parkeeseul commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(selectedLine.getId()).isEqualTo(createdLine.getId());
지하철 노선 정보(상행종점역과 하행종점역)가 잘 응답되는지 검증할 필요는 없을까요? 😄 
```
Given 지하철 노선을 생성하고
When 생성한 지하철 노선을 조회하면
Then 생성한 지하철 노선의 정보를 응답받을 수 있다.
```

2023-01-31 11:38 UTC, parkeeseul commented on src/test/java/subway/LineAcceptanceTest.java
> +                .put("/lines/{id}", 1)
정의해둔 LINE_PATH를 사용해도 좋을 것 같아요 😄

2023-01-31 12:14 UTC, hyungkiShin commented on build.gradle
> +    testAnnotationProcessor 'org.projectlombok:lombok:1.18.12' // 테스트 의존성 추가
test 픽스쳐에서 lombok 이 필요할까 했는데 생각해보니 필요가 없는것 같습니다 :)

2023-01-31 12:15 UTC, hyungkiShin commented on src/main/java/subway/common/Comment.java
> +public @interface Comment {
domain 필드의 설명을 위해 주석을 달까 하였는데, 개인의 취향이였던것 같습니다 :)

2023-01-31 12:15 UTC, hyungkiShin commented on src/main/java/subway/controller/LineController.java
> +    }
아 그렇군요 !!!!! 감사합니다

2023-01-31 12:17 UTC, hyungkiShin commented on src/test/java/subway/LineAcceptanceTest.java
> +    private static final String NAME2 = "이호선";
의미있는 네이밍으로 pr 올리겠습니다 :)

2023-01-31 12:18 UTC, hyungkiShin commented on src/test/java/subway/LineAcceptanceTest.java
> +                .put("/lines/{id}", 1)
크 ... 저부분을 누락시켰습니다

2023-01-31 13:00 UTC, hyungkiShin commented on src/main/java/subway/repository/entity/Line.java
> +public class Line {
![image](https://user-images.githubusercontent.com/55230332/215766689-f2999d38-ea13-4796-8668-77b764517d64.png)

![image](https://user-images.githubusercontent.com/55230332/215766720-1c9d6153-6ef7-48f5-89c5-878496ee48c6.png)

!!! 감사합니다

2023-01-31 13:21 UTC, hyungkiShin commented on src/main/java/subway/exception/message/SubwayErrorCode.java
> +    String message;
GlobalException 을 만드는 도중에 미션이 급급하여 ^^;;... 이부분은 미쳐 검증하지 못하고 넘어갔네요 ㅠㅠ
다음 pr 에 완성본과 함께 올리겠습니다 :)

2023-01-31 13:46 UTC, hyungkiShin commented on src/test/java/subway/LineAcceptanceTest.java
> +@Sql("/insert-station.sql")
모든 단위테스트를 한번에 돌릴 때는 실패하는 케이스에서 
새로운 context를 생성하는게 아니라 기존의 context를 재활용하기 때문에 발생하는 문제 때문이라고 인지하고 있습니다.

(앞선 테스트에서 특정 Bean의 속성값을 바꾸거나, 제거하거나, 추가하게 되면 다음에 오는 테스트를 실패하게 만들 수도 있는 것) - 구글신

이렇게 보니, 그럼 테스트끼리 꼬이지 않게 쳐리해줄 수 있는 @DirtiesContext(classMode = BEFORE_EACH_TEST_METHOD) 를 추가해주면 되겠구로 !!! 했지만 ... 테스트 실행 시간이 오래 걸린다는 단점을 보완하기 위해 어떻게 방향을 잡아야 할까 고뇌중

BEFORE_EACH_TEST_METHOD : 클래스의 모든 테스트 케이스마다 시작하기 이전에 context 재생성
AFTER_EACH_TEST_METHOD : 클래스의 모든 테스트 케이스가 끝날 때 마다 context 재생성

뭔가 조삼모사의 느낌인데... 테스트 케이스 마다 시작하기전에 context 를 생성을 하나, 끝날때마다 생성을 하나... 

![image](https://user-images.githubusercontent.com/55230332/215777183-2923e1c9-f982-44da-a81a-dbb655c02d40.png)

![image](https://user-images.githubusercontent.com/55230332/215777371-612293b0-7d35-4879-b080-9d60de7a0848.png)

비교를 해보니, AFTER_EACH_TEST_METHOD 가 좀더 빠른이 있네요 ... 혹시 이걸 의도 하신건....아니겠죠 ??

2023-01-31 14:09 UTC, hyungkiShin commented on src/test/java/subway/LineAcceptanceTest.java
> +        LineResponse createdLine = 지하철노선_생성(신분당선);
아 맞네요.. 감사합니다 :)

2023-01-31 14:47 UTC, hyungkiShin commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(selectedLine.getId()).isEqualTo(createdLine.getId());
후... 편의성으로 만들어둔 메서드에서 타입으로 받아버리니 status 를 검증 (생략) 해버렸습니다 :)
받아서 id 만 꺼내는 방향으로 refactoring 가겠습니다 !

2023-01-31 14:50 UTC, hyungkiShin commented
:fire:

2023-02-01 13:46 UTC, parkeeseul commented on src/test/java/subway/LineAcceptanceTest.java
> +@Sql("/insert-station.sql")
정답이 있다는 것을 말씀드리려고 했던건 아니였습니다.
코멘트 그대로 한번 고민해 보시면 좋겠다는 의도로 말씀드렸어요 😄 

현재 @DirtiesContext 를 사용하지 않았을 때의 문제는 테스트 데이터들이 디비에 남아있다는 것인데요,
힌트에서도 있듯이 부분은 `@Sql` , Table Truncate 으로도 해결 가능합니다.
이렇게 테이블을 초기화 시켜주는 방법들은 쿼리를 지속적으로 관리해 줘야 한다는 관리 포인트가 생기게 되는데요,
어느 것이 정답이라기 보다는 각각의 방법들의 장단점을 고민해 보시고 선택해 주시면 좋을 것 같습니다 😄

2023-02-01 14:05 UTC, parkeeseul commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(selectedLine.getId()).isEqualTo(createdLine.getId());
제가 말씀드리고 싶었던 부분은 응답시 상행선, 하행선 정보를 검증할 필요는 없을까? 에 대한 고민이였습니다.

현재 단건 조회에서는 `생성한 지하철 노선의 정보를 응답받을 수 있다.` 라는 then(검증) 부분이 있는데요,
조회 기능에서는 생성된 노선의 정보가 잘 반환되는지에 대한 검증이 필요하다고 생각합니다.
API 명세를 보시면 노선의 정보에는 상행선 역과 하행선 역의 정보도 포함되게 되는데요,
이 정보에 대한 검증도 필요하지는 않을까에 대한 질문이였습니다 😄 
(제가 설명이 부족했었던 것 같습니다. )

2023-02-01 14:07 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요! 👍 
질문 주신 사항에 대한 저의 의견과 추가 코멘트 남겨두었으니
확인 부탁드리고 추가적인 수정사항은 다음 단계에서 함께 반영 부탁드립니다
화이팅 입니다 🔥

2023-02-01 14:07 UTC, merged