Step2: 지하철 노선 관리
next-step/atdd-subway-map pull request #675
Opened 2023-01-31 08:04 UTC by choi1204

- [x] 기능 목록
  - [x] 지하철 노선 생성
  - [x] 지하철 노선 목록 조회
  - [x] 지하철 노선 조회
  - [x] 지하철 노선 수정
  - [x] 지하철 노선 삭제

2023-01-31 16:46 UTC, boorownie requested changes
2단계 요구사항 구현 잘 해주셨습니다!
3단계를 바로 진행하게 하려다가 조금은 더 고민해보면 좋을 부분들이 조금 있어서
수정 요청드립니다! 고민해보시고 리뷰요청 주세요~

2023-01-31 16:46 UTC, boorownie commented on src/main/java/subway/subway/Station.java
> +package subway.subway;
line과 같은 계층을 이룬다면 station이 더 잘 어울리지 않을까요?
```suggestion
package subway.station;
```

2023-01-31 16:46 UTC, boorownie commented on src/main/java/subway/DtoConverter.java
> +public class DtoConverter {
해당 클래스는 패키지를 넘어 station과 line 두 도메인 모두에 대해 영향을 끼치고 있는데요,
각각의 컨버터를 만들지 않고 하나로 만든 이유가 있을까요?

2023-01-31 16:46 UTC, boorownie commented on src/main/java/subway/ResponseConverter.java
> +public class ResponseConverter {
언제 사용될 클래스인가요?

2023-01-31 16:46 UTC, boorownie commented on src/main/java/subway/line/Line.java
> +    private String color;
`@Column`을 지정해주지 않아도 컬럼으로 생성되지만
nullable같이 컬럼의 구체적인 설정은 명시해주는 것도 좋을 것 같아요!

2023-01-31 16:46 UTC, boorownie commented on src/main/java/subway/line/Line.java
> +    private List<StationLineGroup> stationLineGroupList = new ArrayList<>();
해당 데이터는 List 자료형이지만 훗날 상황에 따라 Set이 어울릴 수 있고 다른 자료형으로 변경이 가능할 수 있는데요
이 때 테이블 컬럼명도 변경해야하고 여기저기 영향을 많이 줄 수 도 있을 것 같습니다.
변수명에 자료형에 의존하지 않는 방향으로 네이밍을 해보면 어떨까요?

2023-01-31 16:46 UTC, boorownie commented on src/main/java/subway/line/StationLineGroup.java
> +public class StationLineGroup {
사실 반드시 지키실 필요는 없지만 미션의 주요 도메인 설명을 드릴 때 역과 노선의 정보는 구간이라는 이름의 도메인으로 구성한다고 소개드린적이 있습니다 :)

2023-01-31 16:46 UTC, boorownie commented on src/test/java/subway/AcceptanceTest.java
> +public class AcceptanceTest {
인수 테스트 설정을 클래스로 분리 👍

2023-01-31 16:46 UTC, boorownie commented on src/test/java/subway/AcceptanceTest.java
> +    }
테이블 초기화 쿼리 좋습니다!
인수 테스트 클래스에서 해당 역할을 분리해주면 어떨까요?
인수 테스트에서 별도의 클래스로 위임 해 주어도 좋을 것 같습니다.

2023-01-31 16:46 UTC, boorownie commented on src/test/java/subway/LineAcceptanceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
`AcceptanceTest` 에서도 설정되어있는 부분 같습니다!

2023-01-31 16:46 UTC, boorownie commented on src/test/java/subway/LineAcceptanceTest.java
> +    private LineRepository lineRepository;
어제 사용되는 의존 주입인가요?

2023-01-31 16:46 UTC, boorownie commented on src/test/java/subway/LineAcceptanceTest.java
> +        thirdStationId = stationAcceptanceTest.createStation("지하철역3");
클래스 객체를 인스턴스로 만들어 호출하는 방법도 있군요! 👍

2023-01-31 16:46 UTC, boorownie commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
```java
지하철_노선_목록_조회_시_노선_조회_가능(lineCreateRequest.getName(), secondLineCreateRequest.getName())
```
이렇게 검증 자체를 메서드로 분리해보면
시나리오 요구사항의 가독성은 높아지지만 테스트의 구체적인 행동은 감춰지네요.
어떤 것을 더 중점적으로 생각하는게 좋을지 고민해보시면 좋을 것 같아요 :)

2023-01-31 16:46 UTC, boorownie commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
스텝 메서드를 인수 테스트 밖으로 분리하는 방법은 없을까요?

2023-02-01 01:09 UTC, choi1204 commented on src/main/java/subway/subway/Station.java
> +package subway.subway;
앗 이부분 원래 목적이 station이었는데 잘못 지정해주었네요 변경하겠습니다!

2023-02-01 01:11 UTC, choi1204 commented on src/main/java/subway/DtoConverter.java
> +public class DtoConverter {
두 부분을 분리할지 하나로 할지 고민을 하였는데 Line을 생성할때 station의 의존성을 갖게 되어서 분리하기보다는 하나의 클래스내에서 변환하는게 적합하다고 판단되었습니다.

2023-02-01 01:12 UTC, choi1204 commented on src/main/java/subway/ResponseConverter.java
> +public class ResponseConverter {
초기에는 request요청을 converter하는 클래스와 response요청을 converter하는 클래스를 분리할 계획으로 설계하였는데 아직 request와 response의 가지수가 적어서 하나의 클래스(DtoConverter)에서 관리하면서 삭제하지 못한 클래스입니다
제거처리하겠습니다

2023-02-01 01:14 UTC, choi1204 commented on src/main/java/subway/line/Line.java
> +    private String color;
넵 감사합니다! Column 어노테이션으로 명시하겠습니다!

2023-02-01 01:16 UTC, choi1204 commented on src/main/java/subway/line/Line.java
> +    private List<StationLineGroup> stationLineGroupList = new ArrayList<>();
어떤 컬렉션을 사용하는지 구체적으로 명시하고싶어 List를 선호하였는데 확장 및 유지보수를 생각하면 자료형에 의존하지 않는게 더 좋은 방법인것 같네요! 복수형 네이밍으로 변경하겠습니다

2023-02-01 01:18 UTC, choi1204 commented on src/test/java/subway/LineAcceptanceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
앗 테스트 격리 리펙토링하면서 수정하지 못한부분인것같습니다 
감사합니다!

2023-02-01 01:18 UTC, choi1204 commented on src/test/java/subway/LineAcceptanceTest.java
> +    private LineRepository lineRepository;
앗 테스트 격리 리펙토링하면서 수정하지 못한부분인것같습니다
감사합니다!

2023-02-02 00:10 UTC, boorownie approved these changes
피드백 반영 잘 되었네요 👍 
이어서 3단계 진행해주세요~

2023-02-02 00:10 UTC, boorownie commented on src/test/java/subway/LineRestAssuredTest.java
> +    }
XXXRestAssuredTest 클래스 자체적으로 상태를 가지지 않아도 된다면 static 메서드로 구성하는 방법도 있을 것 같습니다 :)

2023-02-02 00:10 UTC, merged