2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #676
Opened 2023-01-31 10:33 UTC by hyun6ik

리뷰 부탁드립니다.

2023-02-02 14:42 UTC, hjhello423 requested changes
안녕하세요 현식님 :)
제가 코멘트를 다 달아놨었는데 실수로 마지막에 확인을 못해서 재때 전달이 안 된 것 같네요. 죄송합니다.🙇‍♂️
몇 가지 코멘트를 달아두었는데 확인 부탁드립니다.

2023-02-06 08:44 UTC, hyun6ik commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        );
생각을 해봤는데도 잘 떠오르지가 않아서 어떻게 바꿔야할지 잘 모르겠습니다 ㅜㅜ

2023-02-06 08:47 UTC, hyun6ik commented on src/main/java/subway/domain/station/Station.java
> +    private Line line;
저 코드가 있어야 연관관계 매핑도 가능한 걸로 알고있습니다. 
해당 부분을 지우고 돌려보니 컴파일 시점에 에러가 발생합니다

2023-02-06 08:48 UTC, hyun6ik commented on src/main/java/subway/domain/line/Line.java
> +    }
public List<Station> getStations() {
        return stations.getStations();
 }
 
 이렇게 변경을 하였는데 리턴 타입도 Collection<Station> 처럼 변화에 유연하게 대응하는게 더 좋은 방법인가요?

2023-02-06 14:21 UTC, hjhello423 commented on src/main/java/subway/domain/line/Line.java
> +import javax.persistence.*;
import의 경우 *를 사용하기보단 개별로 선언해 주시는 게 좋습니다.
코드 가독성, 유지 보수의 이점 뿐만 아니라 빌드 성능에도 영향을 미칠 수 있어요.

2023-02-06 14:21 UTC, hjhello423 commented on src/main/java/subway/domain/line/Line.java
> +    }
메서드 이름 변경으로 충분하네요 :)

2023-02-07 05:56 UTC, hjhello423 requested changes
안녕하세요 현식님 :)
추가로 코멘트를 드렸는데요.
확인 후 다시 한번 리뷰 요청 주세요!

2023-02-07 05:56 UTC, hjhello423 commented on src/test/java/subway/line/LineAcceptanceFactory.java
> +                .extract();
https://github.com/next-step/atdd-subway-map/pull/676#discussion_r1092060534

createFixtureLine()와 중복되는 부분을을 정리해 보시죠!

2023-02-07 05:56 UTC, hjhello423 commented on src/test/java/subway/line/LineAcceptanceFactory.java
> +                LineNameConstraints.Line2,
이 메서드는 LineNameConstraints.Line2를 고정으로 사용하고 있어 재활용하기 어려워 보이네요. 🤔
인자로 전달 받으면 어떨까요?

2023-02-07 05:57 UTC, hjhello423 commented on src/test/java/subway/line/LineNameConstraints.java
> +}
junit test와 fixture에 대해 참고하면 좋을 것 같습니다.

2023-02-07 05:57 UTC, hjhello423 commented on src/main/java/subway/domain/line/Line.java
> +    }
메서드 이름 변경으로 충분해요 :)

2023-02-08 05:08 UTC, hjhello423 approved these changes
안녕하세요:)
step2 머지하도록 하겠습니다!
다음 step 진행해 주세요. 파이팅 🔥

2023-02-08 05:08 UTC, merged