Step2
next-step/atdd-subway-map pull request #683
Opened 2023-01-31 16:39 UTC by seokjin0404

안녕하세요 리뷰어님! 늦었지만 step2 PR보냅니다.
질문을 하나 드리고 싶습니다.

step1에 기존에 구현된 StationService를 참고해서 LineService를 작성했는데요

StationService의 saveStation 메서드에서 레퍼지터리에 Station을 저장할 때, stationRequest에서 값을 꺼내서 Station을 만드는 방식으로 구현된 것을 확인할 수 있었습니다. new Station(stationRequest.getName())

그래서 저도 LineService를 구현할 때, lineRequest의 값을 꺼내서 line을 만드는 방식으로
new Line(lineRequest.getName(), lineRequest.getColor() .... ) 구현했습니다.

제가 생각하기에는 생성자에 LineRequest를 그대로 넘겨주는 것이 코드도 간결해질 것 같고
추후에 entity가 변했을 때, 구현 로직을 바꾸지 않고 entity만 변경할 수 있어서 변경에도 용이할 것 같은데,
어떤 방식으로 구현하는 것이 좋을지 궁금합니다.

2023-02-01 09:23 UTC, hjhello423 requested changes
안녕하세요 진혁님 :)
step2도 잘 진행해 주셨네요!
몇 가지 코멘트를 남겨두었는데 반영 후 다시 한번 리뷰 요청 주세요!

2023-02-01 16:41 UTC, seokjin0404 commented on src/main/java/subway/dto/LineResponse.java
> +    private List<Station> stations;
> Station이 domain 패키지로 이동하였는데요. API의 응답에서 domain을 직접 응답하면 어떤 문제점이 생길 수 있을까요?

@hjhello423 
API응답에서 domain을 직접 응답하면, 도메인에 외부에 공개되면 안되는 정보가 노출될 수 있어서, dto를 사용해서 필요한 데이터를 선별하는 것이 좋을 것 같습니다! 그래서 List<Station> stations를 List<StationResponse>로 수정했는데, 제가 옳은 방향으로 수정한 것인지 궁금합니다.

2023-02-01 16:43 UTC, seokjin0404 commented on src/main/java/subway/service/LineService.java
> +                lineRequest.getDistance()));
@hjhello423 답변해주셔서 정말 감사합니다! 앞으로 학습하는데 큰 도움이 될 것 같습니다

2023-02-01 16:55 UTC, seokjin0404 commented on src/test/java/subway/line/LineAcceptanceTest.java
> +                .extract();
생각해보니 굳이 그럴 필요가 없었네요 감사합니다.

2023-02-01 17:02 UTC, seokjin0404 commented on src/main/java/subway/service/LineService.java
> +                lineRequest.getDistance()));
감사합니다! Line 생성자에 검증로직을 추가해봤습니다.

2023-02-01 17:03 UTC, seokjin0404 commented on src/main/java/subway/dto/LineRequest.java
> +    }
리뷰해주신대로 import문과 접근제어자를 변경했습니다

2023-02-01 17:13 UTC, seokjin0404 commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        assertThat(lineColors).hasSize(1);
노선 조회에 사용한 메서드를 재사용해서 수정했습니다

2023-02-01 17:15 UTC, seokjin0404 commented on src/main/java/subway/service/LineService.java
> +    }
어떻게 로직을 수정할지 빠르게 파악할 수 있을 것 같습니다

2023-02-01 17:16 UTC, seokjin0404 commented on src/main/java/subway/service/LineService.java
> +        lineRepository.save(line);
감사합니다 :)

2023-02-02 14:33 UTC, hjhello423 requested changes
안녕하세요 진혁님!
몇 가지 코멘트를 남겨두었는데요.
한 번 더 고민해 보고 해결하면 좋을 것 같습니다! 파이팅🔥

2023-02-02 14:33 UTC, hjhello423 commented on src/test/java/subway/line/LineAcceptanceTest.java
> +    }
노선 수정 후, 수정된 노선의 정보를 검증하기 위해
readLine()이 2번 일어나고 있는데요. 1번만 조회하도록 수정해 보면 좋을 것 같습니다.  😃

2023-02-02 14:33 UTC, hjhello423 commented on src/main/java/subway/dto/LineResponse.java
> +@AllArgsConstructor
`@AllArgsConstructor` 사용 시 주의할 점을 찾아보고 수정해 주세요 😀

2023-02-03 02:42 UTC, seokjin0404 commented on src/main/java/subway/dto/LineResponse.java
> +@AllArgsConstructor
필드 순서가 바뀌면, 생성자 파라미터 순서도 함께 바뀌어서 만약 같은 타입의 필드가 순서가 바뀌면 기존 프로덕션 코드에서 아무 에러도 주지 않고 그대로 실행되므로 지양해야한다로 이해하면 될까요?

2023-02-04 00:03 UTC, hjhello423 commented on src/main/java/subway/dto/LineResponse.java
> +@AllArgsConstructor
네 맞습니다. 👍
아마 찾아보면서 다른 어노테이션들에 대한 내용도 같이 확인하셨을 것 같은데요.
록복의 어노테이션들을 사용할 때 주의해서 사용하면 좋습니다!

2023-02-04 00:05 UTC, hjhello423 approved these changes
안녕하세요 진혁님 :)
코멘트 내용들 잘 반영해 주셨네요 👍
머지하도록 하겠습니다. 다음 step 진행해 주세요.🔥

2023-02-04 00:05 UTC, merged