🚀 2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #693
Opened 2023-02-01 16:53 UTC by kjy11

안녕하세요~ 리뷰 부탁드립니다!🙏

2023-02-02 11:32 UTC, pch8388 commented
커밋 단위 잘 나누어 주셨네요 💯 
[참고](https://gist.github.com/stephenparish/9941e89d80e2bc58a153) 보시고 이런 방법도 있다는 것도 학습하시면 좋을 것 같아요 😄

2023-02-02 11:32 UTC, pch8388 requested changes
2단계 수행하느라 고생하셨습니다 👏 
참고하실만한 코멘트를 남겨드렸습니다.
이번 단계에서 테스트 리팩터링은 조금 더 했으면 합니다. 
수정하시고 리뷰요청주세요 🔥

2023-02-02 11:32 UTC, pch8388 commented on src/main/java/subway/services/LineService.java
> +            .orElseThrow(EntityNotFoundException::new);
중복제거를 해보는건 어떨까요? 😄 

`StationRepository` 를 직접사용하시는 데, `StationService` 를 주입받아서 사용했을때와는 어떤 장단점이 있을까요?

2023-02-02 11:32 UTC, pch8388 commented on src/main/java/subway/models/Section.java
> +    @Setter
[객체지향생활체조](https://edu.nextstep.camp/s/ZlcCZQ2Y/ls/USFEu0qR)
> 규칙 9: 게터/세터/프로퍼티를 쓰지 않는다.

2023-02-02 11:32 UTC, pch8388 commented on src/main/java/subway/services/LineService.java
> +        lineRequest.apply(line);
어떤 의도로 이렇게 하신걸까요? 🤔

2023-02-02 11:32 UTC, pch8388 commented on src/main/java/subway/dto/request/LineRequest.java
> +        }
DTO 클래스의 역할에 대해 고민이 필요해보여요 😢

2023-02-02 11:32 UTC, pch8388 commented on src/main/java/subway/dto/request/LineRequest.java
> +                .sequence(1)
항상 첫번째의 구간으로 생성된다는 의미일까요? 🤔 
상수로 변경하여 의미를 조금 더 담아보면 어떨까요? 

> 클린 코드 G25: 매직 숫자는 명명된 상수로 교체하라

2023-02-02 11:32 UTC, pch8388 commented on src/main/java/subway/dto/request/LineRequest.java
> +            line.addSection(section);
현재 요구사항으로는 구간 없는 노선이 생길 수 없을 거 같은데 따로 넣어주시는 이유가 있을까요?
가능하다면 엔티티 생성시에 객체가 완결성을 지닐 수 있도록 하는게 좋습니다 😄

2023-02-02 11:32 UTC, pch8388 commented on src/main/java/subway/controllers/LineController.java
> +    @PutMapping(value = "/lines/{id}")
`PUT` 과 `PATCH` 의 차이에 대해 알고 계신가요? 🤔 
여기서는 어떤게 더 어울릴까요?

2023-02-06 13:31 UTC, kjy11 commented on src/test/java/subway/StationAcceptanceTest.java
> +        지하철역_생성(강남역);
저도 훨씬 가독성이 좋아졌다고 느꼈습니다! 👌

2023-02-06 15:37 UTC, kjy11 commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(response.jsonPath().getList("name").size()).isEqualTo(params.size());
이전의 테스트 코드(지하철 노선을 생성한다)에서 파라미터에 맞게 노선이 생기는 것을 검증했는데 생성된 노선의 데이터를 또 확인하는 것은 중복되는 검증은 아닌가요?🤔

2023-02-06 15:44 UTC, kjy11 commented on src/main/java/subway/services/LineService.java
> +        lineRequest.apply(line);
DTO <-> Entity 간 변환을 DTO가 전담하도록 하고 싶은데 update의 경우에는 기존 엔터티를 가져와서 수정해줘야하다보니 이렇게 구현하게 되었습니다.

update의 경우에는 getter로 dto의 필드를 가져와서 entity에 적용하는 게 더 맞을까요?

2023-02-06 15:57 UTC, kjy11 commented on src/main/java/subway/services/LineService.java
> +            .orElseThrow(EntityNotFoundException::new);
기본적으로 순환참조 방지를 위해 repository -> service -> controller의 주입순서를 지키려고 하는 편입니다. 간단한 로직은 repository를 주입받아쓰고, service에서 service 주입이 필요할 때는 가급적 주입용 service를 따로 두는 편인데 늘 고민되는 부분이긴합니다.🤔

2023-02-09 14:01 UTC, kjy11 commented on src/main/java/subway/services/LineService.java
> +            .orElseThrow(EntityNotFoundException::new);
서비스를 다른 서비스에서 사용 하려면 response의 entity -> dto 변환을 controller에서 하는 게 좋지 않을까요?

2023-02-09 14:49 UTC, kjy11 commented on src/main/java/subway/controllers/LineController.java
> +    @PutMapping(value = "/lines/{id}")
put은 리소스 전체 교체(모든 요소에 대한 값을 요청에 포함)를, patch는 일부 교체를 의미하는 것으로 알고 있습니다. line의 모델링에 따라 name과 color가 line 리소스의 전체 요소이냐는 부분에 있어서는 이견이 있을 수 있겠으나 현재 api는 name과 color 모두를 포함한 요청을 보내야하고 둘 중 하나만 보내서 수정할 수 없으므로 put이 더 어울린다고 생각합니다!

2023-02-10 01:50 UTC, pch8388 commented on src/main/java/subway/controllers/LineController.java
> +    @PutMapping(value = "/lines/{id}")
사실 이 부분은 name, color 를 따로따로 수정할 수 있다라는 생각으로 말씀드린 부분이긴 합니다 😅 
[참고](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) 에 따르면, PUT 은 리소스가 없을 경우 새로운 리소스를 생성하고 201을 반환하는 형태로 쓰인다고 하네요

2023-02-10 09:00 UTC, pch8388 commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(response.jsonPath().getList("name").size()).isEqualTo(params.size());
검증이 중복되면 안된다고 생각하시는 이유가 있을까요? 💭 
말씀하신대로 간단한 검증만 하고 넘어갈 수도 있고, 조금 더 자세히 해볼 수도 있다고 생각해요 😄 
지하철 노선 목록이 제대로 나오는지에 대해 궁금한 것이니, 지하철 노선에 어떤 목록들이 나오는 지 체크해보는 것이 노선이 잘 생성되었음을 체크하는 것과 차이가 있다고 생각합니다. (차이가 없다고 생각하시면 제가 제안하는 것을 꼭 하시지 않아도 됩니다 😅 )

2023-02-10 09:10 UTC, pch8388 commented on src/main/java/subway/services/LineService.java
> +            .orElseThrow(EntityNotFoundException::new);
[참고](https://github.com/HomoEfficio/dev-tips/blob/master/DTO-DomainObject-Converter.md) 의 글을 보시면 좋을 것 같아요
의견이 갈릴수도 있는 부분인데, 개인적으로는 entity 가 controller 에 노출되지 않는 편이 좋다고 생각합니다. 😄

2023-02-10 11:49 UTC, pch8388 approved these changes
리팩터링 잘수행해주셨습니다 👏 
남겨드린 코멘트들을 보고 다음 단계 진행시에 참고해주세요 😄

2023-02-10 11:49 UTC, pch8388 commented on src/main/java/subway/services/LineService.java
> +        line.addSection(section);
다른 코멘트에서 질문 주셨던 내용에 답변 드리자면, 연관관계가 어떤 식으로 맺어져 있는지와는 관계 없이 `Line`이 생성될때 `Section`을 넣어주면 되지 않을까요? 🤔 
생성자를 이용하면 될 것 같아요 😅

2023-02-10 11:49 UTC, pch8388 commented on src/main/java/subway/models/Line.java
> +    private List<Section> sections = new ArrayList<>();
[객체지향생활체조](https://edu.nextstep.camp/s/ZlcCZQ2Y/ls/USFEu0qR)

> 규칙 8: 일급 콜렉션을 쓴다.

[일급컬렉션 참고](https://jojoldu.tistory.com/412)

2023-02-10 11:49 UTC, pch8388 commented on src/main/java/subway/models/Line.java
> +    }
```suggestion
    private Line(String name, String color, Station upStation, Station downStation) {
        this.name = name;
        this.color = color;
        this.sections = List.of(new Section(....);
    }
```

이런형태로 하면 구간없는 노선이 생성될 위험을 줄일 수 있을 것 같아요 😄

2023-02-10 11:49 UTC, pch8388 commented on src/test/java/subway/LineAcceptanceTest.java
> +            .isEqualTo(방배역_ID);
`StationAcceptanceTest` 처럼 조금 더 자연스럽게 읽히도록 만들 수 없을까요? 🤔

2023-02-10 11:49 UTC, pch8388 commented on src/test/java/subway/StationAcceptanceTest.java
> +        목록_개수_및_이름_확인(지하철역_목록_조회_응답, new String[]{강남역});
좀 더 깔끔해진것 같아요 👍 
조금 더 비즈니스 친화적인 메서드 명이면 좋을 것 같아요 
메서드 위에 when/then 주석 내용처럼 자연스럽게 읽힐 수 있는 이름은 어떨까요? 😄

2023-02-10 11:50 UTC, merged

2023-02-14 15:19 UTC, kjy11 commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(response.jsonPath().getList("name").size()).isEqualTo(params.size());
중복이 되기 시작하면 어디까지 중복 검증을 할 것인지 기준을 잡기 어려워져서 고민을 했던 것인데요~ 말씀하신대로 상황에 따라 유연하게 검증하면 좋을 것 같습니다!