🚀 2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #697
Opened 2023-02-01 18:57 UTC by ji-one

- [x] 지하철 노선 생성
- [x] 지하철 노선 목록 조회
- [x] 지하철 노선 조회
- [x] 지하철 노선 수정
- [x] 지하철 노선 삭제

2023-02-02 09:40 UTC, kang-hyungu requested changes
지원님 미션 잘 진행해주셨습니다.
몇 가지 코멘트 남겼는데 확인해보시고 리뷰 재요청주세요.

2023-02-02 09:40 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +        Line line = lineRepository.save(
LineRequest  클래스에 만들어둔 toEntity 메서드를 활용하면 어떨까요?

2023-02-02 09:40 UTC, kang-hyungu commented on src/main/java/subway/line/Line.java
> +@NoArgsConstructor
jpa 때문에 기본 생성자가 필요한 상황이네요.
public 접근제어자로 열린 기본 생성자보다 protected로 접근을 최대한 제한하는게 어떨까요?

2023-02-02 09:40 UTC, kang-hyungu commented on src/main/java/subway/line/Line.java
> +    private Long upStationId;
Station 클래스와 연관관계를 매핑하는게 어떨까요?
id 기반으로 연결하게 되면 객체를 잘 활용하기 어렵습니다.

2023-02-02 09:40 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +            List<Station> stations = List.of(getStationById(line.getUpStationId()), getStationById(line.getDownStationId()));
Line과 Station 사이에 연관관계를 매핑하면 직접 repository로 Station 객체를 호출하지 않아도 되겠네요

2023-02-02 09:40 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +    public Station getStationById(Long id) {
Line 서비스에서 Station에 대한 처리를 하는 것보다 StationService에서 처리하는게 중복을 줄이기 좋지 않을까요?

2023-02-02 09:40 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(IllegalArgumentException::new);
lineRepository.findById(...)가 다른 메서드에서 중복해서 나오고 있네요. 메서드로 추출하면 중복을 줄일 수 있지 않을까요

2023-02-02 09:40 UTC, kang-hyungu commented on src/test/java/subway/line/LineAcceptanceTest.java
> +    private LineRequest givenLineRequest2() {
테스트 코드도 제품 코드처럼유지관리가 필요합니다.
불용어를 사용한 메서드명 보다 어떤 의도의 객체인지 의미있는 메서드명을 써보는게 좋겠네요

2023-02-02 09:40 UTC, kang-hyungu commented on src/test/java/subway/line/LineAcceptanceTest.java
> +                .upStationId(1L)
1L 은 무슨 역일까요?

2023-02-02 09:40 UTC, kang-hyungu commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        createLine(request);
given에서 사용하는 메서드에 assertThat 처리를 하는 것보다 생성과 검증을 분리하는게 어떨까요?
given 처리하는데 assert 예외가 나오면 어떤 것을 검증하는 인수 테스트인지 집중하기 어려울 것 같네요

2023-02-02 09:40 UTC, kang-hyungu commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        assertThat(response.jsonPath()
jsonPath를 파싱하는 부분을 따로 추출해주는게 코드 파악하기에 용이하지 않을까요?

2023-02-04 08:00 UTC, ji-one commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        return given().log().all()
http 호출 중복 제거에 대해 고민해보았는데, 우선은 CommonRestAssured 클래스를 생성해서 테스트에서 공통으로 쓰이는 메소드를 모아 두는 방식으로 구현하였습니다. 
혹시 이 방법이 리뷰어님이 말씀해주신 `http method를 기준으로 제네릭을 활용` 의도에 맞을까요?

2023-02-04 08:00 UTC, ji-one commented on src/main/java/subway/line/Line.java
> +@NoArgsConstructor
반영했습니다. 감사합니다!

2023-02-04 08:01 UTC, ji-one commented on src/main/java/subway/line/Line.java
> +    private Long upStationId;
반영했습니다. 감사합니다!

2023-02-04 08:04 UTC, ji-one commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        createLine(request);
아 그렇군요!! 리뷰 감사합니다. 반영했습니다! 🙂

2023-02-04 08:10 UTC, ji-one commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        assertThat(response.jsonPath()
jsonPath를 파싱하는 부분을 `CommonResponseBodyExtraction` 클래스로 추출해보았는데, 해당 방식이 리뷰어님이 의도하신 방향과 일치할까요? 다시 의견 남겨주시면 감사하겠습니다. 🙇‍♀️

2023-02-04 08:11 UTC, ji-one commented on src/main/java/subway/line/LineService.java
> +    public Station getStationById(Long id) {
반영했습니다. 감사합니다! 🙏

2023-02-04 08:12 UTC, ji-one commented on src/test/java/subway/line/LineAcceptanceTest.java
> +    private LineRequest givenLineRequest2() {
넵! 반영했습니다. 감사합니다.

2023-02-04 08:20 UTC, ji-one commented on src/test/java/subway/line/LineAcceptanceTest.java
> +                .upStationId(1L)
```java
private LineRequest 신분당선_생성_요청_dto() {
        StationResponse 강남역 = StationAcceptanceTest.createStation("강남역");
        StationResponse 미금역 = StationAcceptanceTest.createStation("미금역");

        return new LineRequest(신분당선, RED, 강남역.getId(), 미금역.getId(), 10L);
    }
```
위 코드로 수정하였는데, 제가 리뷰어님의 의도를 제대로 파악한게 맞을까요?

2023-02-05 03:48 UTC, kang-hyungu approved these changes
지원님 피드백 반영 잘 하셨습니다.
RestAssured 호출의 중복도 잘 제거해주셨네요.
pr은 머지 처리하겠습니다. 수고하셨습니다.

2023-02-05 03:48 UTC, merged