🚀 2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #708
Opened 2023-02-04 13:34 UTC by paso0129

2023-02-04 17:03 UTC, Flamme1004K requested changes
안녕하세요! 🙇🏻

2단계 미션 잘 구현해 주셨습니다! 💯

몇 가지 코멘트를 남겼으니, 확인 부탁드리겠습니다!

2023-02-04 17:03 UTC, Flamme1004K commented on src/test/java/subway/StationAcceptanceTest.java
> +        assertThat(stationNames).doesNotContain("사상역");
```suggestion
        //when
        ExtractableResponse<Response> response = RestAssured.given().log().all()
            .contentType(MediaType.APPLICATION_JSON_VALUE)
            .basePath("/stations")
            .pathParam("id", stationId)
            .when().delete("{id}")
            .then().log().all()
            .extract();
        

        //then
        List<String> stationNames = getStationNames();
        assertThat(response.statusCode()).isEqualTo(HttpStatus.NO_CONTENT.value());
        assertThat(stationNames).doesNotContain("사상역");
```

given / when / then에 대한 플로우를 본다면 위와 같은 순서로 되어야한다고 생각해요.

또한 delete도 create나 getStationNames 같이 메서드로 만들어볼까요?

2023-02-04 17:03 UTC, Flamme1004K commented on src/test/java/subway/SubwayFixture.java
> +public class SubwayFixture {
fixture 사용 👍👍

2023-02-04 17:03 UTC, Flamme1004K commented on src/test/java/subway/SubwayLineAcceptanceTest.java
> +        assertThat(response.jsonPath().getString("name")).contains("신분당선");
`지하철 노선 목록 조회 시 생성한 노선을 찾을 수 있다` 에 대한 부분이 빠졌네요. 🥲

2023-02-04 17:03 UTC, Flamme1004K commented on src/test/java/subway/SubwayLineAcceptanceTest.java
> +        assertThat(getResponse.statusCode()).isEqualTo(HttpStatus.OK.value());
매번 HttpStatus에 대한 비교를 하는데요~ 이 부분을 getSubwayLine 메서드에 같이 넣는게 어떨까요?

인수테스트 목록에 대해서 딱 가르키는 부분만 남도록 말이죠! 🤩

2023-02-04 17:04 UTC, Flamme1004K commented on src/test/java/subway/SubwayLineAcceptanceTest.java
> +//            .jsonPath().getList(".", SubwayLineResponse.class);
사용하지 않는 부분은 주석처리가 아닌 제거해주는게 좋다고 생각해요 : )

2023-02-05 01:09 UTC, paso0129 commented on src/main/java/subway/Station.java
> +@Getter
넵!!

2023-02-05 01:35 UTC, paso0129 commented on src/test/java/subway/SubwayLineAcceptanceTest.java
> +        assertThat(response.jsonPath().getString("name")).contains("신분당선");
혹시 
`assertThat(response.jsonPath().getString("name")).contains("신분당선")`
요 부분은 말씀해주신 요청사항이랑 다른건가요?!

2023-02-05 01:41 UTC, Flamme1004K commented on src/test/java/subway/SubwayLineAcceptanceTest.java
> +        assertThat(response.jsonPath().getString("name")).contains("신분당선");
넵! 

* When 지하철 노선을 생성하면
* Then 지하철 노선 목록 조회 시 생성한 노선을 찾을 수 있다

when은 지하철 노선 생성에 대한 액션, Then은 지하철 노선 목록을 조회를 하여 노선 목록에 생성 된 노선이 있는지에 대해 검증이 필요하죠.

2023-02-05 01:49 UTC, paso0129 commented on src/main/java/subway/StationRepository.java
> +//    public Station findById(long id);
따로 없습니다.. 주석 날리는걸 깜빡했네요 🥲

2023-02-05 11:54 UTC, Flamme1004K approved these changes
안녕하세요! 🙇🏻

피드백 반영 잘 해주셨습니다!💯 이만 머지 하도록 하겠습니다!

추가로, 몇 가지 코멘트를 남겼으니, 확인 부탁드리겠습니다!

다음 미션도 화이팅입니다!

2023-02-05 11:54 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(lineNames).containsAnyOf(LINE_SHIN_BUN_DANG_REQUEST.getName());
```suggestion
        //when
        createSubwayLine(LINE_SHIN_BUN_DANG_REQUEST);

        //then
        List<String> lineNames = getSubwayLines();
        assertThat(lineNames).containsAnyOf(LINE_SHIN_BUN_DANG_REQUEST.getName());
```

한번 더 리팩토링을 하자면, 이렇게도 표현이 가능할 것 같아요! 

더 명확하게 보여주기 위해서라고 생각해주시면 되겠습니다! 🤩

2023-02-05 11:54 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +            LINE_SHIN_BUN_DANG_REQUEST);
```suggestion
        Long createdResponse = createSubwayLine(
            LINE_SHIN_BUN_DANG_REQUEST);
```

Response가 아닌, Id를 반환하면 더 간결해지지 않을까요~?

2023-02-05 11:54 UTC, merged

2023-02-06 02:02 UTC, paso0129 commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(lineNames).containsAnyOf(LINE_SHIN_BUN_DANG_REQUEST.getName());
👍