Step3 지하철 구간관리
next-step/atdd-subway-map pull request #711
Opened 2023-02-04 14:56 UTC by ess234

JPA가 익숙하지 않아서 구간 추가, 삭제 기능 구현에 애를 먹었네요 ㅜㅜ
연관관계 설정이나 테이블 구조를 맞게 작성했는지 확인 부탁드립니다.

개선해야 될 포인트가 많겠지만 더 늦어지면 안될 것 같아.. PR 요청드렸습니당 양해부탁드려용 😭

2023-02-05 02:18 UTC, dbeod2 requested changes
안녕하세요 :-) 3단계 지하철 구간 미션 잘 수행해주신 것 같아요~ 

고민해보면 좋을 것 같아서 코멘트 달아두었는데 확인 부탁드리겠습니다.🙏🏻
힘내서 미션 이어서 진행해주시면 될 것 같습니다!

혹시 추가적인 도움이 필요하시면 언제든지 DM 남겨주세요~

2023-02-05 02:18 UTC, dbeod2 commented on src/test/java/subway/common/StationApiTest.java
> +package subway.common;
인수테스트들을 domain 패키지로 이동하셨는데요.
관련된 restAssured도 같이 이동되면 좋을 것 같아요 :-)

2023-02-05 02:18 UTC, dbeod2 commented on src/test/java/subway/domain/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest {
예외 처리에 대한 인수테스트까지 꼼꼼하게 해주셨습니다. 
다만 RestAssured 부분이 중복 코드인데 리팩토링해보시면 좋을 것 같아요 ~ ☺️

2023-02-05 02:18 UTC, dbeod2 commented on src/test/java/subway/domain/section/SectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR.value());
요청 응답에 대한 부분도 메서드로 분리 할 수 있을 것 같은데 고민해보시면 좋을 것 같네요~

2023-02-05 04:31 UTC, ess234 commented on src/main/java/subway/service/LineService.java
> +        }
말씀하신대로 line addSection 메소드 안으로 이동했습니당 !

2023-02-05 04:32 UTC, ess234 commented on src/main/java/subway/service/LineService.java
> +    private static String ERROR_LINE_DELETE_SECTION_NO_LAST_SECTION = "[SYS_ERROR] section's not last section";
errorMsgEnum 별도로 빼서 분리했습니당

2023-02-05 04:33 UTC, ess234 commented on src/main/java/subway/repository/SectionRepository.java
> +public interface SectionRepository extends JpaRepository<Section, Long> {
구간 삭제 기능 구현때 여러 구간 추가 후 마지막 구간인지 아닌지 판단하기 위해 section 저장이 필요해서 넣었습니당 ㅜㅜ

2023-02-05 04:34 UTC, ess234 commented on src/main/java/subway/domain/Line.java
>      @NotBlank(message = "name is not blank")
넵 ! 수정했습니당

2023-02-05 04:34 UTC, ess234 commented on src/main/java/subway/controller/SectionController.java
> +public class SectionController {
넵 말씀하신대로 line 컨트롤러로 이동했습니당

2023-02-05 06:49 UTC, dbeod2 commented on src/main/java/subway/repository/SectionRepository.java
> +public interface SectionRepository extends JpaRepository<Section, Long> {
영속성 전이 관계에서 노선 정보만 조회해도 구간정보는 같이 가져올 수 있기에 구간 정보 리포지토리는 없어도 충분히 가능할 것 같습니다.

2023-02-05 07:13 UTC, ess234 commented on src/test/java/subway/common/StationApiTest.java
> +package subway.common;
패키지 위치 변경했습니다

2023-02-05 07:14 UTC, ess234 commented on src/main/java/subway/service/LineService.java
> +        sectionRepository.save(section);
주신 개념 블로그 확인 후 로직 삭제했습니당 
감사합니다!

2023-02-05 08:12 UTC, dbeod2 requested changes
피드백 반영 빠르게 해주셨네요 👍 

몇 가지 좀 더 고민해보면 좋을 부분에 코멘트 남겨두었습니다. 
수정해보시고 리뷰 재요청주세요🙏🏻

2023-02-05 08:12 UTC, dbeod2 commented on src/main/java/subway/controller/LineController.java
> +        return ResponseEntity.ok().body(line);
post 요청에 대한 응답은 200 보다 201을 사용하면 어떨까요?

2023-02-05 09:04 UTC, ess234 commented on src/main/java/subway/controller/LineController.java
> +        return ResponseEntity.ok().body(line);
수정했습니당

2023-02-05 09:05 UTC, ess234 commented on src/main/java/subway/domain/Line.java
> +
sections 클래스 추가해서 수정했는데 
<img width="339" alt="image" src="https://user-images.githubusercontent.com/25348139/216810541-38614d96-5cf2-4398-9116-7f9db8554750.png">

응답에 Sections > Sections로 표기되는데 ... 하위는 Section으로 표기하려면 어떻게 해야 되나요 ?? 😭

2023-02-05 09:06 UTC, ess234 commented on src/test/java/subway/domain/section/SectionAcceptanceTest.java
> +    public static class StationApiTest {
클래스 이동을 한다는데 .. 잘못 복사되었네요 수정했습니당

2023-02-05 09:06 UTC, ess234 commented on src/main/java/subway/domain/Line.java
> +    }
조건문 간결하게 수정했습니다 ~! 
잡아주셔서 감사합니당

2023-02-05 09:07 UTC, ess234 commented on src/main/java/subway/service/LineService.java
> +            throw new Exception("["+ERROR_DELETE_SECTION_NO_LAST_SECTION_LINE.getCode()+"]"+ERROR_DELETE_SECTION_NO_LAST_SECTION_LINE.getMsg());
Subway 에러 클래스 커스텀하게 생성해서 적용했습니당 
피드백 주신 의도에 맞게 적용한게 맞는지 확인 부탁드려용 ㅠㅠ

2023-02-05 11:47 UTC, dbeod2 commented on src/main/java/subway/domain/Section.java
> +    private Long downStationId;
구간정보 안에는 역 정보가 들어가야하지 않을까요?~

2023-02-05 11:47 UTC, dbeod2 commented on src/main/java/subway/domain/Line.java
> +
노선 - 구간 - 지하철역의 연관관계를 생각해보면 
Section 안에 정보는 Station의 정보를 가지고 있어야 하지 않을까요~ ?

현재는 Section안에 상행역Id 하행역 Id두 개의 정보만 가지고 있네요 🥲.. 
https://github.com/next-step/atdd-subway-map/pull/711/files#r1096608503 피드백 드린 부분 있는데 힌트가 되기에는 정보가 부족했던 것 같습니다 🥲 

Sections안에 Stations정보가 나오면 될 것 같아요~

2023-02-05 14:33 UTC, dbeod2 requested changes
전체적으로 코드 개선도 되고 있는 것 같아요. 👍
몇 가지 코멘트 조금 더 남겨두었는데 확인 부탁드릴께요
수정해보시고 리뷰 재요청주세요. 🙏

2023-02-05 14:33 UTC, dbeod2 commented on src/test/java/subway/common/AcceptanceTest.java
> +        databaseCleanup.execute();
의존성을 제거를 위해 테스트 코드 초기화 👍

2023-02-05 14:33 UTC, dbeod2 commented on src/test/java/subway/domain/section/SectionAcceptanceTest.java
LineResponse내에 일급 컬렉션을 그대로 정보를 주고 있어서 아래와 같이 response가 나오고 있어요 🥲
Section은 결국 지하철역 정보이기때문에 List<StationResponse>로도 response를 전달해도  될 것 같은데 어떻게 생각하세요~?
<img width="439" alt="스크린샷 2023-02-05 오후 11 24 24" src="https://user-images.githubusercontent.com/70149382/216825199-f1695836-fcda-4f1b-a599-afbe34b1f579.png">

2023-02-06 23:15 UTC, dbeod2 approved these changes
진윤님 ! 마지막 지하철 구간관리 피드백 반영 너무 잘해주셨습니다. 👍 

많은 피드백을 드렸는데 이해하신만큼 적용 잘 해주신 것 같아요 ~
그동안 피드백 드린게 도움이 되었으면 좋겠습니다. 
다음미션이 있기에 저는 여기서 머지하겠습니다. 

다음 미션도 지금처럼 잘 해내실거라 믿습니다.
수고하셨습니다!

2023-02-06 23:15 UTC, dbeod2 commented on src/test/java/subway/domain/line/LineAcceptanceTest.java
> +        assertAll("지하철 노선 생성 테스트 (독립적)",
피드백 반영 👍

2023-02-06 23:16 UTC, merged