[step2] 지하철 노선 관리 PR 요청
next-step/atdd-subway-map pull request #727
Opened 2023-02-07 09:24 UTC by jisoo27

안녕하세요 리뷰어님! 
2단계 지하철 노선 인수테스트 작성 리뷰 요청 드립니다.
이번에도 많은 가르침 부탁드립니다. 🙇🏻‍♀️🙇🏻‍♀️

2023-02-07 14:25 UTC, Flamme1004K requested changes
안녕하세요! 🙇🏻

2단계 미션 잘 구현해 주셨습니다! 💯

몇 가지 코멘트를 남겼으니, 확인 부탁드리겠습니다!

2023-02-07 14:25 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +class LineAcceptanceTest {
테스트에 대한 격리 부분이 제외되었네요~

2023-02-07 14:25 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +        createLine("신분당선", "bg-red-600", 1, 2, 10);
upstation, downstation 중에 무엇이 강남역이고, 양재역이고, 서현역인가요?

2023-02-07 14:25 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(line).containsAnyOf("강남역");
- when 생성한 지하철 노선을 조회하면
- then 생성한 지하철 노선의 정보를 응답받을 수 있다.

강남역만 검증하면 위의 인수테스트에 대해서 검증된 걸까요?

2023-02-07 14:25 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +        String lineName = getLine("/lines/1").getString("name");
여기서 1이란 무엇일까요~? 🤔

2023-02-07 14:25 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +        String color = getLine("/lines/1").getString("color");
API가 두번 호출되고 있군요. 하나로 만들어보시겠어요~?

2023-02-07 14:25 UTC, Flamme1004K commented on src/main/java/subway/service/LineService.java
> +        return lineRepository.findById(id).orElseThrow(IllegalAccessError::new);
`IllegalAccessError` 만 주면 될까요~? 예외 메시지도 같이 있었으면 좋겠어요!

2023-02-07 15:52 UTC, jisoo27 commented on src/main/java/subway/controller/LineController.java
> +        return ResponseEntity.ok().body(lineService.createLineResponse(line));
혹시 findLineById가 lineResponse도 만들경우 findLineById가 id로 Line을 찾는 일과 LineResponse를 만드는 일 2가지를 하는거 같은데 괜찮은가요?! 
createLineResponse는 Line에 대한 정보를 받는 역할보다는 station 을 mapping 해주는 역할을 하고 있는 것 같습니다!!.. 수정하겠습니당!

2023-02-07 16:30 UTC, jisoo27 commented on src/main/java/subway/service/LineService.java
> +        list.add(downStationResponse);
혹시 lineResponse.getStations()로 List를 가져오라는 말씀이실까요?! line에서 station을 list로 가지고 있지않는거 같은데 list를 가져오는 방법을 잘 모르겠습니다 🥹 제가 잘못이해하고 있는 부분이 있다면 말씀해주시면 감사하겠습니다!!

2023-02-09 11:40 UTC, Flamme1004K commented on src/main/java/subway/controller/LineController.java
> +        return ResponseEntity.ok().body(lineService.createLineResponse(line));
findLineById에 대해서는 계층 간의 경계 구간에서 생각하자면 service 단에서 controller 단을 넘어올 때 request로 감싸서 보내줄 수 있을 것 같습니다. 해당 내용에 대해서는 지난주 수업 내용을 다시 들어보시는 것도 좋아보입니다! 🙇🏻

2023-02-09 11:42 UTC, Flamme1004K commented on src/main/java/subway/service/LineService.java
> +        list.add(downStationResponse);
https://velog.io/@eddy_song/alan-kay-OOP

해당 내용을 보고 객체 간의 메시지에 대해 생각해보시겠어요~? 🤩

2023-02-09 13:04 UTC, jisoo27 commented on src/main/java/subway/controller/LineController.java
> +        return ResponseEntity.ok().body(lineService.createLineResponse(line));
감사합니다!

2023-02-15 10:05 UTC, Flamme1004K approved these changes
안녕하세요! 🙇🏻

피드백 반영 잘 해주셨습니다! 이만 머지하도록 하겠습니다.

피드백 전과 다르게 전체적으로 인수 테스트가 깔끔해지는 부분이 인상깊었습니다.

다음 미션 제출이 기대되네요 🤩

몇 가지 코멘트를 남겼으니, 확인 부탁드리겠습니다!

화이팅입니다👍👍

2023-02-15 10:05 UTC, Flamme1004K commented on src/main/java/subway/dto/StationRequest.java
> +package subway.dto;
dto 패키지를 service 패키지에다가 넣는다면 어떠한 장점이 있을까요~?

2023-02-15 10:05 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +    private DatabaseCleanup databaseCleanup;
DatabaseCleanup을 사용한 격리 👍

2023-02-15 10:05 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +        StationAcceptanceTest.createStation("강남역");
```suggestion
        GANG_NAM_STATION = StationAcceptanceTest.createStation("강남역");
```

바로 초기화 해준다면 테스트가 더 정밀해지지 않을까합니다 😊

2023-02-15 10:05 UTC, Flamme1004K commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
크! 인수 테스트가 엄청 깔끔해졌군요 👍👍 마음에 듭니다!

2023-02-15 10:05 UTC, merged

2023-02-15 10:22 UTC, Flamme1004K commented on src/main/java/subway/service/LineService.java
> +        list.add(downStationResponse);
```
public LineResponse createLineResponse(Line line) {
        return new LineResponse(
                line.getId(),
                line.getName(),
                line.getColor(),
                line.getStations().stream().map(stationService::createStationResponse).collect(Collectors.toList())
        );
    }
```

이렇게도 가능해보이네요~

2023-02-16 19:13 UTC, jisoo27 commented on src/main/java/subway/service/LineService.java
> +        list.add(downStationResponse);
<img width="614" alt="스크린샷 2023-02-17 오전 4 10 54" src="https://user-images.githubusercontent.com/94853413/219463980-786b73a3-e538-4a8d-a08e-25a9376a47c6.png">
Line 엔티티 가 상행역과 하행역을 따로 가지고 있어서 getStations() 로 가져 올 수 없을 경우에는  station 을 List 로 갖도록 수정해야 할까요...?!