🚀 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #730
Opened 2023-02-08 01:46 UTC by cyPark95

안녕하세요!
3단계 지하철 구간 관리입니다.

- 구간 등록 기능
- 구간 제거 기능

리뷰요청 드립니다.

2023-02-08 12:18 UTC, boorownie requested changes
3단계 요구사항 잘 구현해주셨습니다!
테스트 부분은 이미 가독성 고려해서 잘 구현해주셔서 특별한 코멘트는 없고요
대신 프로덕션 코드에서 JPA 활용하는 부분에 대한 코멘트를 조금 남겨보았습니다.
관련해서 이해가 잘 안되거나 궁금한 내용이 있으면 편하게 DM 주세요!

2023-02-08 12:18 UTC, boorownie commented on src/test/java/subway/utils/SectionUtil.java
> +package subway.utils;
테스트 코드의 패키지 구조의 기준이 궁금합니다!
subway 하위에 section이라는 패키지가 있지만 SectionUtils는 section이 아닌 utils에 있어서요
사실 정해지거나 베스트 프랙틱스 구조가 있는건 아니지만 기준이 있을 것 같은데 코멘트로 질문 드려요~

2023-02-08 12:18 UTC, boorownie commented on src/test/java/subway/common/AcceptanceTest.java
> +public abstract class AcceptanceTest {
인수 테스트 환경 설정 중복 제거 👍

2023-02-08 12:18 UTC, boorownie commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest extends AcceptanceTest {
구체적인 요구사항에 대한 인수 테스트 👍 

비즈니스 로직에 대한 요구사항을 인수 테스트로 검증하는 것과 해당 도메인의 단위 테스트로 검증하는 것 중 어떤 방법이 좋다고 생각하시나요? 생각해보면 좋을 것 같아서 코멘트로 남겼어요~

2023-02-08 12:18 UTC, boorownie commented on src/main/java/subway/line/service/LineService.java
>      }
현재 코드상으로는 Section을 영속화 한 다음 Line 생성 시 주입해서 생성해주고 있는데요~
그냥 Line 생성 시 비영속상태인 Section 객체를 주입해서 Line을 생성하거나
Line을 생성한 다음 Section 객체를 add 하는 방법도 있을 것 같아요!
한번 고민해주세요~

2023-02-08 12:18 UTC, boorownie commented on src/main/java/subway/section/repository/SectionRepository.java
> +public interface SectionRepository extends JpaRepository<Section, Long> {
Line에서 Section에 대한 객체 참조를 하고 있는데 SectionRepository 없이 LineRepository를 통해 영속화된 Line 객체를 조회해오면 Section도 함께 조회할 수 있을 것 같은데 SectionRepository가 반드시 필요한지 고민해주세요~

2023-02-09 01:24 UTC, cyPark95 commented on src/test/java/subway/utils/SectionUtil.java
> +package subway.utils;
도메인별로 관련 테스트들을 해당 도메인 패키지에 관리하고, 각각 테스트에서 사용하는 로직을 도메인 Util로 만들어서 Utils 패키지에서 관리하려고 했습니다.
생각해 보니까 Utils 패키지로 따로 관리하기보단 관련 요구사항별로 패키지로 관리하는 게 좋을 거 같단 생각이 드네요!

2023-02-09 01:24 UTC, cyPark95 commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest extends AcceptanceTest {
비즈니스 로직에 대한 요구사항을 인수 테스트로 검증하는 방법이 더 좋은 거 같아요!
시나리오를 생각하는 과정에서 비즈니스 로직에 대한 이해도도 높아지고, 로직에 대해 다시 한번 정리할 수 있는 기회를 얻을 수 있는 거 같아요.

인수 테스트가 처음이다 보니 어색해서인지 자꾸 도메인 기준으로 진행하게 되는데 이번 과정 동안 좀 더 신경 써서 비즈니스 로직에 대한 요구사항을 기준으로 진행할 수 있도록 노력해 보겠습니다.🧐

2023-02-09 01:24 UTC, cyPark95 commented on src/main/java/subway/line/service/LineService.java
>      }
Section 객체가 Line을 제외한 다른 곳에서도 종속될 수 있을 거라는 생각에 영속성 전이를 전혀 염두에 두지 않았던 거 같습니다.
지금 보니 Line 객체를 애그리거트 루트로 보고 Line 엔티티를 통해 Section 엔티티의 생명주기를 함께 관리하면 좋을 거 같아요!

2023-02-09 01:25 UTC, cyPark95 commented on src/main/java/subway/section/repository/SectionRepository.java
> +public interface SectionRepository extends JpaRepository<Section, Long> {
Line 엔티티에서 Section의 생명주기까지 관리하니 SectionService와 SectionRepository가 없어도 될꺼 같아요!😀

2023-02-09 12:31 UTC, boorownie approved these changes
피드백 반영하신 부분 확인했습니다!
질문 드린 부분에 대해서 답변을 고민하시면서 다양한 인사이트를 얻으셨기를 바라봅니다 🙏
1주차 미션 고생 많으셨습니다! 이만 머지할게요~

2023-02-09 12:31 UTC, boorownie commented on src/main/java/subway/line/service/LineService.java
> +        );
Section을 LineService에서 생성한 후 Line에 넘겨주는 방법도 좋지만
Line 내부에서 생성하는 방법도 있습니다!
이렇게 할 경우 LineService는 Section에 대한 의존을 없앨 수 있어요!

2023-02-09 12:31 UTC, merged

2023-02-09 12:49 UTC, cyPark95 commented on src/main/java/subway/line/service/LineService.java
> +        );
1주차 미션 기간동안 꼼꼼한 피드백 정말 감사드립니다.
다음 강의에서 뵙겠습니다🤗