Step3
next-step/atdd-subway-map pull request #741
Opened 2023-02-12 04:00 UTC by changgunyee

2023-02-12 11:40 UTC, dbeod2 requested changes
2단계 미션 진행 잘해주셨습니다 👍 

몇 가지 코멘트 남긴 부분이 있는데 확인 부탁드립니다.
확인 후 리뷰 재요청 주세요~ 💪🏻

2023-02-12 11:40 UTC, dbeod2 commented on src/main/java/subway/LineRepository.java
> +    Line save(Line line);
LineRepository save를 따로 만들어주신 이유가 있을까요? 🤔

2023-02-12 11:40 UTC, dbeod2 commented on src/test/java/subway/StationAcceptanceTest.java
전체 테스트시 지하철 역 관련 인수테스트가 실패하고있습니다. 
확인 부탁드립니다.

2023-02-12 11:40 UTC, dbeod2 commented on src/main/java/subway/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(() -> new NoSuchElementException("no line for id"));
`lineRepository.findById(id).orElseThrow(() -> new NoSuchElementException("no line for id")` 노선 조회 부분이 중복 코드로 보여지는데요. 리팩토링을 통해 중복을 제거 할 수 있지않을까요? 🤔

2023-02-12 11:40 UTC, dbeod2 commented on src/main/java/subway/Station.java
> +
미사용 코드는 제거해주세요 🙏🏻

2023-02-12 11:40 UTC, dbeod2 commented on src/test/java/subway/LineAcceptanceTest.java
> +                .extract();
메서드로 분리해주신 getLines()를 활용하면 좋을 것 같아요 ~

2023-02-12 11:40 UTC, dbeod2 commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
노선 수정 후 잘 수정이 되었는지 확인해 볼 수 있지않을까요?

2023-02-12 11:40 UTC, dbeod2 commented on src/test/java/subway/LineAcceptanceTest.java
> +                .contentType(MediaType.APPLICATION_JSON_VALUE)
delete의 경우 body로 넘기는 값이 없으므로 contentType을 지정할 필요가 없을 것 같습니다~ 🙏

2023-02-13 06:07 UTC, changgunyee commented on src/test/java/subway/LineAcceptanceTest.java
> +                .contentType(MediaType.APPLICATION_JSON_VALUE)
수정했습니다!

2023-02-13 06:07 UTC, changgunyee commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
추가했습니다~

2023-02-13 06:07 UTC, changgunyee commented on src/test/java/subway/LineAcceptanceTest.java
> +                .extract();
수정했습니다.

2023-02-13 06:08 UTC, changgunyee commented on src/main/java/subway/Station.java
> +
요건 추후에 사용할수도있을것 같아서 추가했는데 삭제해야할까요?

2023-02-13 06:08 UTC, changgunyee commented on src/main/java/subway/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(() -> new NoSuchElementException("no line for id"));
중복제거했습니다!

2023-02-13 06:08 UTC, changgunyee commented on src/test/java/subway/StationAcceptanceTest.java
수정했습니다.

2023-02-13 06:08 UTC, changgunyee commented on src/main/java/subway/LineRepository.java
> +    Line save(Line line);
아뇨 없어요 😢  삭제했습니다~

2023-02-13 12:55 UTC, dbeod2 commented on src/main/java/subway/Station.java
> +
지하철역에서 노선 목록이 필요 할 경우가 있을까요 ~ ? 
노선 - 구간 - 지하철 역의 관계를 한번 더 고민해보시면 좋을 것 같아요 ㅎㅎ

2023-02-13 12:57 UTC, dbeod2 approved these changes
2단계 미션 피드백 반영 빠르게 잘해주셨네요 :-) 

따로 이견없어서 바로 머지하겠습니다.
다음미션을 진행해주세요! 💪🏻

2023-02-13 12:57 UTC, dbeod2 commented on src/main/java/subway/LineService.java
> +                .orElseThrow(() -> new NoSuchElementException("no line for id"));
예외 처리시 가독성있게 한글로 예외 내용을 보여줘도 좋을 것 같은데 어떻게 생각하시나요~ ?

2023-02-13 12:57 UTC, merged