Step3 - 지하철 구간 관리 인수테스트
next-step/atdd-subway-map pull request #743
Opened 2023-02-12 13:58 UTC by zz9z9

안녕하세요 개인 일정이 있었어서 PR이 너무 오래걸렸네요 ㅜ 
2단계에서 받은 피드백도 적용해보았습니다.
노선, 구간 테스트 내에서 private 메서드로 중복되는 것들이 있는데 이런 메서드는 어떻게 공통으로 빼야할지를 잘 모르겠네요 ..

전체적으로 피드백 부탁드립니다
감사합니다 !

2023-02-14 02:10 UTC, kang-hyungu requested changes
안녕하세요 재윤님. 많이 바쁘셨군요.
시간 되실 때 미션 진행하고 리뷰 요청주셔도 괜찮으니 마지막 단계도 잘 마무리해보아요.

테스트 코드 깔끔하게 작성해주셨네요 👍 
몇 가지 다듬어보면 좋을 부분에 코멘트 남겼어요.
수정해보시고 리뷰 재요청주세요.

2023-02-14 02:10 UTC, kang-hyungu commented on src/main/java/subway/line/business/service/LineService.java
> +        if (request.getUpStationId() != line.getLastStationId()) {
서비스를 사용하지 않고 직접 Line 객체를 다루는 경우엔 이 내용을 검증할 수 없겠네요.
라인이 섹션을 가져야 한다는 로직은 서비스보다 도메인 객체에서 관리하면 어떨까요?
validateAddSection 메서드를 Line 객체 내부로 옮기는게 좋겠네요.

2023-02-14 02:10 UTC, kang-hyungu commented on src/main/java/subway/line/business/service/LineService.java
> +        if (request.getUpStationId() != line.getLastStationId()) {
하나 더 챙겨보면 좋을 것 같아요.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/15669435/218619177-fdf14038-54e6-4732-8855-11acb7db1e3d.png">

2023-02-14 02:10 UTC, kang-hyungu commented on src/main/java/subway/line/repository/entity/Line.java
> +    public Long getLastStationId() {
아이디를 외부로 건네서 로직을 처리하기 보다 필요한 데이터를 파라미터로 받아와서 Line 내부에서 처리해보면 어떨까요?

2023-02-14 02:10 UTC, kang-hyungu commented on src/main/java/subway/line/web/controller/LineController.java
> +    public ResponseEntity removeSection(@PathVariable Long id, @RequestParam Long stationId) {
ResponseEntity의 제네릭 타입도 명시해주는게 좋겠네요.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/15669435/218620124-e314488a-2eda-4356-b553-b4d1c8c71532.png">

2023-02-14 02:10 UTC, kang-hyungu commented on src/main/java/subway/line/web/controller/LineController.java
> +    public void addSection(@PathVariable Long id, @RequestBody SectionRequest request) {
이 메서드는 ResponseEntity가 생략된 것 같네요. ResponseEntity와 Void 클래스를 써보면 어떨까요?

2023-02-14 13:25 UTC, zz9z9 commented on src/main/java/subway/line/business/service/LineService.java
> +        if (request.getUpStationId() != line.getLastStationId()) {
객체 내부로 옮기면 말씀하신 부분에 더해 캡슐화 측면에서도 더 좋을 것 같네요. 
궁금한 점은 만약 그렇게 된다면 `findStation` 메서드가 불필요하게 호출될 것 같다는 생각이 드는데요, 
지금은 `addSection`이 호출되기 전에  `findStation`이 두 번 호출되는게 전부지만, 만약 훨씬 복잡한 경우라면 
이런 경우에도 객체 내부에 존재하도록 하는게 좋을까요 ?

```java
// validateAddSection(line, request);

Station upStation = stationService.findStation(request.getUpStationId());
Station downStation = stationService.findStation(request.getDownStationId());

line.addSection(new Section(upStation, downStation, request.getDistance()));
lineRepository.save(line);
```

2023-02-14 13:26 UTC, zz9z9 commented
리뷰 감사합니다 ! 피드백 반영하여 수정해보았습니다. 
유효성 검사하는 부분 관련해서 질문도 하나 남겼습니다. 
감사합니다 ~

2023-02-14 13:27 UTC, zz9z9 commented
리뷰 감사합니다 ! 피드백 반영하여 수정해보았습니다.
유효성 검사하는 부분 관련해서 질문도 하나 남겼습니다.
감사합니다 ~

2023-02-16 00:34 UTC, kang-hyungu commented on src/main/java/subway/line/business/service/LineService.java
> +        if (request.getUpStationId() != line.getLastStationId()) {
Line 객체를 생성하려면 Station이 각각 필요하네요.
어떤 Station 객체를 저장해야 하는지 알려면 findStation이 필요하니 코드 내에 존재하는게 자연스럽겠네요.

2023-02-16 00:42 UTC, kang-hyungu approved these changes
재윤님 피드백 반영 잘 해주셨네요.
pr은 머지 처리하겠습니다. 수고하셨습니다!

2023-02-16 00:42 UTC, merged