3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #746
Opened 2023-02-13 15:48 UTC by rolroralra

# 기능 요구사항
- [x] 요구사항 설명에서 제공되는 요구사항을 기반으로 지하철 구간 관리 기능을 구현하세요.
- [x] 요구사항을 정의한 인수 조건을 도출하세요.
- [x] 인수 조건을 검증하는 인수 테스트를 작성하세요.
- [x] 예외 케이스에 대한 검증도 포함하세요.

# 기능 목록
- [x] 자하철 구간 등록
- [x] 지하철 구간 삭제

# 프로그래밍 요구사항
- [x] 인수 테스트 주도 개발 프로세스에 맞춰서 기능을 구현하세요.
  - [x] 요구사항 설명을 참고하여 인수 조건을 정의
  - [x] 인수 조건을 검증하는 인수 테스트 작성
  - [x] 인수 테스트를 충족하는 기능 구현
- [x] 인수 조건은 인수 테스트 메서드 상단에 주석으로 작성하세요.
  - [x] 뼈대 코드의 인수 테스트를 참고
- [x] 인수 테스트의 결과가 다른 인수 테스트에 영향을 끼치지 않도록 인수 테스트를 서로 격리 시키세요.
- [x] 인수 테스트의 재사용성과 가독성, 그리고 빠른 테스트 의도 파악을 위해 인수 테스트를 리팩터링 하세요.

2023-02-14 14:00 UTC, HyunSung-Na requested changes
안녕하세요 신영님!

3단계 미션 잘 진행해주셨습니다! 😊

몇가지 참고할만한 코멘트 남겼으니 확인 후 리뷰 재요청 해주시면 감사하겠습니다! 🙇

2023-02-14 14:02 UTC, rolroralra commented on build.gradle
> +    id 'com.ewerk.gradle.plugins.querydsl' version '1.0.10'
개인적으로 써보려다가, 쓰지 못했습니다.

2023-02-14 14:02 UTC, rolroralra commented on src/main/java/subway/exception/ExceptionController.java
> +        log.info("Not Found Exception: {}", e.getMessage(), e);
넵, error로 변경하곘습니다.

```suggestion
        log.error("Not Found Exception: {}", e.getMessage(), e);
```

2023-02-14 14:03 UTC, rolroralra commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        System.out.println(RestAssured.port);
넵 변경하곘습니다.

2023-02-14 14:05 UTC, rolroralra commented on src/test/java/subway/line/LineDataSet.java
> +    public static Line testData(String name, String color, int distance) {
넵. 변경하겠습니다.

이 네이밍은 결국 팀이나 프로젝트 그라운들 룰에 의존할것이라고 생각이 듭니다.

모든 클래스에 대해서 test data를 뽑을때, 메서드명이 클래스마다 다른 거보다.

오로지 `테스트 데이터를 생산`이라는 의미에서는 간단한 메서드 명이 더 유리할 수도 있다는 생각이 듭니다.

2023-02-15 03:48 UTC, HyunSung-Na commented on src/main/java/subway/exception/ExceptionController.java
> +        log.info("Not Found Exception: {}", e.getMessage(), e);
해당 부분을 error 로 생각하신 이유가 있을까요?
클라이언트에서 잘못된 요청으로 인한 오류는 서버쪽 문제가 아니므로 ERROR 로 보기 어려울 거 같은데 어떻게 생각하시나요?

2023-02-15 03:53 UTC, HyunSung-Na requested changes
안녕하세요 신영님!

저번 리뷰요청때 연관관계에 대한 피드백을 드렸었는데요!
해당 부분에 대해서 개선이 필요한 점이 있을거 같아서 확인해 주시고

리뷰 재요청 해주시면 감사하겠습니다! 🙇‍♂️
궁금하신 점이 있으시면 언제든지 DM 해주시면 감사하겠습니다! 😁

2023-02-15 04:01 UTC, HyunSung-Na commented on src/test/java/subway/line/LineDataSet.java
> +    public static Line testData(String name, String color, int distance) {
네 감사합니다!
신영님이 말씀하신대로 팀이나 프로젝트마다 그라운드 룰이 있지만
해당 룰을 학습하는데에는 시간이 필요하고 다른 관리포인트가 생겨서 비용이 필요한 점이 아닌가 생각됩니다.
클린코드에서 의도를 나타내는 네이밍에 대한 내용이 나오는데 참고해보시면 좋을거 같습니다.
또한 메서드명은 명사보다는 동사와 전치사를 이용하는게 메서드의 행위를 설명하는데 더 좋을것 이라고 생각합니다!
개인적인 견해이니 참고해주시면 감사하겠습니다.

2023-02-18 11:19 UTC, rolroralra commented on src/main/java/subway/line/LineService.java
> +//    private List<LineStation> createAndSaveLineStations(Line line, LineRequest lineRequest) {
넵 주석 삭제하겠습니다.

2023-02-18 11:20 UTC, rolroralra commented on src/main/java/subway/line/LineService.java
> +    private final LineStationRepository lineStationRepository;
넵 제거하곘습니다.

2023-02-18 18:03 UTC, rolroralra commented on src/main/java/subway/test/DatabaseCleanup.java
> +public class DatabaseCleanup implements InitializingBean {
넵 이동해놓겠습니다.

2023-02-18 18:04 UTC, rolroralra commented on src/main/java/subway/test/DatabaseCleanup.java
> +//        List<String> tableNames = new ArrayList<>();
이 메서드의 경우, 제가 개인적으로 코드에 메모상으로 남겨두는 부분이라서,

이부분은 그냥 이해해주십시요. 물론 실제적으로 업무에서는 삭제했을겁니다.

따라서 그냥 다른 private 메서드로 extract 해놓겠습니다.

2023-02-18 18:06 UTC, rolroralra commented on src/test/java/subway/line/LineDataSet.java
> +    public static Line testData(String name, String color, int distance) {
넵. 당연히 팀 그라운드 룰에 따르는게 맞죠.

현재 저는 그냥 모든 테스트에 대한 객체 생성시에는 

`testData`로 통일하는 것으로 진행하곘습니다.

말씀대로 클린 코드를 위해서라면 실제적으로 무엇을 하는지 기입해주는게 좋겠죠.,

2023-02-18 18:06 UTC, rolroralra commented on README.md
> +# 3단계 - 지하철 구간 관리
감사합니다.

2023-02-18 18:07 UTC, rolroralra commented on src/main/java/subway/exception/CannotRemoveLineSectionException.java
> +public class CannotRemoveLineSectionException extends RuntimeException {
감사합니다.

2023-02-18 18:13 UTC, rolroralra commented on src/main/java/subway/line/Line.java
> +    private Station downStation;
저는 우선 컨셉을 

Station <-> Section <-> LineSection <-> Line
으로 ERD 설계도를 잡았습니다.

물론 이렇게 된다면, Station이나 Section이 삭제되었을 때

연계 처리가 문제가 될것이고, 이 부분은 경험이 좀 부족하여, 

우선 현재는 Station, Section을 만들었다면 삭제하는 건 없다는 가정하에서 진행하였습니다. (기회가 된다면 이런 부분들도 꼼꼼하게 진행하겠습니다.)

LineSection의 경우는, Line과 Section의 다대다 관계를 표현하는 테이블로 정의하였습니다.

이부분은 강남-선릉 구간이 2호선에도 포함될수도 있고 9호선에도 포함될 수 있다는 걸 고려해서 반영하였습니다.

2023-02-18 18:13 UTC, rolroralra commented on src/main/java/subway/line/LineRepository.java
> +    @Query(value = "select distinct l from Line l left join fetch l.upStation left join fetch l.downStation left join fetch l.lastLineSection")
Custom을 만들어서 하면됬었는데,

여유가 없어서 하지 못했습니다.

2023-02-19 06:50 UTC, HyunSung-Na commented on src/main/java/subway/line/Line.java
> +    private Station downStation;
`이부분은 강남-선릉 구간이 2호선에도 포함될수도 있고 9호선에도 포함될 수 있다는 걸 고려해서 반영하였습니다.` 해당 부분은 미션 요구사항에는 포함되지 않은 부분으로 보이는데요! 해당 구조로 인해 로직이 더 복잡하게 구성이 된거 같습니다!
추후 다음 주차 미션을 진행해 주시면서 구조에 대해 고려해 보시면 좋을거 같습니다 😊

2023-02-19 06:54 UTC, HyunSung-Na approved these changes
안녕하세요 신영님!

피드백 반영 해주셔서 감사합니다! 머지하도록 하겠습니다! 😊

미션 수행해 주시느냐 고생 많으셨습니다! 다음 미션도 화이팅하세요! 🔥

2023-02-19 06:54 UTC, merged