🚀 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #747
Opened 2023-02-13 16:14 UTC by ji-one

## 기능 요구사항
- [x] 요구사항 설명에서 제공되는 요구사항을 기반으로 지하철 구간 관리 기능을 구현하세요.
- [x] 요구사항을 정의한 인수 조건을 도출하세요.
- [x] 인수 조건을 검증하는 인수 테스트를 작성하세요.
- [x] 예외 케이스에 대한 검증도 포함하세요.

## 프로그래밍 요구사항
- [x] 인수 테스트 주도 개발 프로세스에 맞춰서 기능을 구현하세요.
- [x] 요구사항 설명을 참고하여 인수 조건을 정의
- [x] 인수 조건을 검증하는 인수 테스트 작성
- [x] 인수 테스트를 충족하는 기능 구현
- [x] 인수 조건은 인수 테스트 메서드 상단에 주석으로 작성하세요.
- [x] 뼈대 코드의 인수 테스트를 참고
- [x] 인수 테스트의 결과가 다른 인수 테스트에 영향을 끼치지 않도록 인수 테스트를 서로 격리 시키세요.
- [x] 인수 테스트의 재사용성과 가독성, 그리고 빠른 테스트 의도 파악을 위해 인수 테스트를 리팩터링 하세요.

2023-02-14 02:35 UTC, kang-hyungu requested changes
지원님 3단계 미션도 잘 진행해주셨네요.
몇 가지 챙겨보면 좋을 부분에 코멘트 남겼어요.
수정해보시고 리뷰 재요청주세요.

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/line/Line.java
> +        boolean stationFound = sections.stream().anyMatch(section ->
```suggestion
        boolean stationFound = sections.hasStation(stationId);
```

이렇게 바꾸면 어떨까요?
section에서 값을 꺼내서 비교할 필요가 없어지지 않을가요?

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/line/Line.java
> +        if (!stationId.equals(downStation.getId())) {
station에서 아이디를 꺼내서 비교하는게 아닌, station 객체에게 동일한 아이디인지 물어보는게 어떨까요?

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
Station upStation = stationService.getStationById(request.getUpStationId());

23 라인은 이렇게 써도 되지 않나요?

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
>          return LineResponse.of(
```suggestion
        return LineResponse.of(line);
```

이렇게 줄일 수도 있겠네요.

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +    private List<Station> findAllStations(Line line){
이 메서드를 line으로 옮겨보면 어떨까요?
LineService를 쓰지 않고 Line을 쓰게 되면 Line이 가지고 있는 모든 역을 구하기 위한 stream이 반복되서 나올 수 있겠네요.

```java
line.findAllStations();
```

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/section/Section.java
> +        boolean endStationMismatch = !(line.getSections().isEmpty() || upStation.getId()
객체지향 생활체조
규칙 4: 한 줄에 점을 하나만 찍는다.

꺼내서 비교하는 것보다 객체가 직접 처리할 수 있도록 만드는게 어떨까요?

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/section/Section.java
> +        boolean duplicatedStation = line.getSections().stream()
이 로직도 중복을 제거할 수 있을 것 같네요.

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +    private final SectionRepository sectionRepository;
SectionService 클래스를 쓰는게 어떨까요?

2023-02-14 02:35 UTC, kang-hyungu commented on src/main/java/subway/line/LineService.java
> +        sectionRepository.save(new Section(line, upStation, downStation,
line과 section이 연관관계 매핑이 되어 있어서 repository로 직접 지정을 안해줘도 될거에요.
line 객체에 section을 추가해주시고 line만 repository를 사용해서 저장하면 코드를 줄일 수 있겠네요.

2023-02-14 16:11 UTC, ji-one commented on src/main/java/subway/line/Line.java
> +        boolean stationFound = sections.stream().anyMatch(section ->
리뷰 감사합니다. 따로 함수로 추출하였습니다.

2023-02-14 16:11 UTC, ji-one commented on src/main/java/subway/line/Line.java
> +        if (!stationId.equals(downStation.getId())) {
리뷰 감사합니다! 반영했습니다.

2023-02-14 16:12 UTC, ji-one commented on src/main/java/subway/line/LineService.java
수정했습니다 :)

2023-02-14 16:12 UTC, ji-one commented on src/main/java/subway/line/LineService.java
>          return LineResponse.of(
감사합니다. 반영했습니다!

2023-02-14 16:13 UTC, ji-one commented on src/main/java/subway/line/LineService.java
> +    private List<Station> findAllStations(Line line){
리뷰 감사합니다. 반영했습니다!

2023-02-14 16:14 UTC, ji-one commented on src/main/java/subway/section/Section.java
> +        boolean endStationMismatch = !(line.getSections().isEmpty() || upStation.getId()
넵넵 리뷰 감사합니다! 반영했습니다.

2023-02-14 16:15 UTC, ji-one commented on src/main/java/subway/section/Section.java
> +        boolean duplicatedStation = line.getSections().stream()
반영했습니다!

2023-02-14 16:20 UTC, ji-one commented on src/main/java/subway/line/LineService.java
> +        sectionRepository.save(new Section(line, upStation, downStation,
처음 라인이 저장될 때, 해당 라인은 구간에도 등록되어야하기 때문에 기존에는 직접 repository로 저장을 했습니다. 
현재는 `SectionRepository` 사용하지 않고, `Line`에 `addSection()`을 구현한 후 이를 사용하는 방향으로 개선했습니다..! 

```suggestion
        Section section = new Section(line, upStation, downStation, request.getDistance());
        line.addSection(section);
```

리뷰어님이 의도하신 방향과 맞게 개선되었을까요?

2023-02-16 00:55 UTC, kang-hyungu commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +        CommonRestAssured.post("/lines/1/sections", sectionRequest);
line의 아이디가 항상 1이라고 보장할 수 있을까요?

2023-02-16 00:55 UTC, kang-hyungu approved these changes
지원님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리할게요. 수고하셨습니다.

2023-02-16 00:55 UTC, merged