2단계 지하철 노선 관리
next-step/atdd-subway-map pull request #754
Opened 2023-02-19 08:29 UTC by njw724

리뷰 부탁드립니다.

2023-02-20 05:16 UTC, hjhello423 requested changes
안녕하세요 지원님 😀
요청 주신 pr에 고민해 보면 좋을 코멘트들을 작성해 두었습니다.
확인 후 반영하여 다시 한번 리뷰 요청 주세요.

2023-02-20 11:25 UTC, njw724 commented on src/main/java/lines/LineApplication.java
> +}
LineAcceptanceTest 테스트 코드 실행 시 404 에러가 발생해서 위 코드를 생성하였는데 에러가 나는 원인을 알 수 있을까요?

2023-02-22 08:31 UTC, hjhello423 commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
반복적으로 사용되는 부분들이 분리되었네요. 👍

2023-02-22 08:31 UTC, hjhello423 commented on src/main/java/lines/LineApplication.java
> +}
`@SpringBootApplication`어노테이션을 사용하면 bean을 자동으로 등록해 주는데요.
`@SpringBootApplication`의 위치에 따라 scan 범위가 달라지게 됩니다
component scan을 키워드로 검색해보시면 많은 자료들을 찾을 수 있을거에요.

2023-02-22 08:31 UTC, hjhello423 commented on src/main/java/lines/LineController.java
> +    }
@njw724  이 부분이 반영되지 않았어요.

2023-02-22 08:33 UTC, hjhello423 commented on src/main/java/lines/Line.java
> +    }
@njw724  이 코멘트도 고민해보셨나요?

2023-02-22 08:35 UTC, hjhello423 requested changes
안녕하세요 지원님 😀
질문 주신 내용에 대해 답변 달아두었습니다.
일부 반영이 안된 코멘트들이 있는데 다시 한번 확인 부탁드려요.

2023-02-22 08:35 UTC, hjhello423 commented on src/test/java/subway/LineAcceptanceTest.java
> +    }
반복적으로 사용되던 로직이 분리되었네요. 👍

2023-11-01 14:34 UTC, closed without merging