Step2
next-step/atdd-subway-map pull request #885
Opened 2023-07-04 09:08 UTC by michaelkimm

# 구현 사항
- 지하철 노선 생성(테스트 및 구현)

# 미구현 사항
- 지하철 노선 목록 조회
- 지하철 노선 조회
- 지하철 노선 수정
- 지하철 노선 삭제

# PR 목적
- 구현할 것이 많아져서 복잡했지만🥲 최대한 TDD 방식으로 구현하려고 했습니다. 제대로 하고 있는 것이 맞나 싶어 하나의 기능 구현 후 PR 올렸습니다.
- TDD 방식으로 알맞게 진행하고 있는지 피드백 희망합니다! 피드백 받은 후 미구현 사항 마저 진행하려합니다🙂
- 진행 방식: 인수테스트 작성 -> 컨트롤러 구현 -> 서비스 테스트 작성 -> 서비스 로직 구현 -> 리팩토링

2023-07-04 12:56 UTC, pch8388 requested changes
안녕하세요 민석님
말씀하신대로 ATDD 사이클에 맞게 개발해주고 계십니다. 
앞으로 주차별 강의를 진행하면서 조금 더 ATDD 사이클에 친숙해질 기회가 있습니다. 😄 
일단 보내주신 PR 에 대해서는 코멘트를 드렸으니 참고해주시고, 나머지 구현도 해보시고 리뷰요청해주세요 🔥

2023-07-04 12:56 UTC, pch8388 commented on src/test/java/subway/LineAcceptanceTest.java
> +public class LineAcceptanceTest extends AcceptanceTest {
<img width="293" alt="스크린샷 2023-07-04 오후 9 08 22" src="https://github.com/next-step/atdd-subway-map/assets/17218212/f21de5f2-cbb4-450f-95cf-6a2489b169ce">

테스트가 모두 실패하는 것 같아요 😢 
원인은 `StationRepository`에 선언하신 `findAllByLineName`이라는 메서드 때문인 것으로 보입니다.

2023-07-04 12:56 UTC, pch8388 commented on src/main/java/subway/jpa/StationRepository.java
> +    List<Station> findAllByLineName(String name);
JPA 에서 자동 생성해주는 쿼리는 꽤나 제한적이며, 규칙을 잘치켜야 합니다. 😅 
현재 아무런 연관관계도 없기 때문에 JPA 가 쿼리를 만들어 줄 수 없을 것이라는 생각이 듭니다

2023-07-04 12:56 UTC, pch8388 commented on src/main/java/subway/service/LineService.java
> +        // Response 객체로 변환
불필요한 주석이라고 생각됩니다 👀

2023-07-04 12:56 UTC, pch8388 commented on src/main/java/subway/service/LineService.java
> +                    })
```suggestion
.map(s -> ModelMapperUtil.modelMapper.map(s, StationResponse.class))
```

이렇게 쓸수도 있어요 😅

2023-07-04 12:56 UTC, pch8388 commented on src/main/java/subway/service/LineService.java
> +        Line lineEntity = ModelMapperUtil.modelMapper.map(lineRequest, Line.class);
DTO 성격의 클래스와 엔티티 매핑시에 단순 필드들을 변환 시키는 의미로 여기는 것보다는 엔티티에는 비즈니스 로직이 담길 수 있고, 유효성 검증 등도 객체 생성시에 필요할 수 있습니다.
따라서 mapper 로 단순 매핑은 지양하는 것이 좋다고 생각합니다 😅

2023-07-04 12:56 UTC, pch8388 commented on src/main/java/subway/service/LineService.java
> +        lineResponse.setStations(stationResponses);
lineEntity 를 다시 반환하는게 맞을까요? 🤔 
지금 우리는 해당 내용이 그대로 저장되고 반환될 것이라는 것을 알고 있지만, 코드를 처음 접한 다른 팀원의 입장이라면,  파라미터로 넘겼던걸 그대로 매핑한 `lineEntity`를 다시 반환하는 부분과 `saveLineEntity`로 저장하는 부분이 나뉘어져 있기때문에 더 혼란스러울 것 같아요

그리고 `setter`는 지양해주세요 
[객체지향생활체조](https://edu.nextstep.camp/s/ZlcCZQ2Y/ls/USFEu0qR)

2023-07-04 12:56 UTC, pch8388 commented on src/test/java/subway/service/LineServiceTest.java
> +class LineServiceTest {
서비스 테스트를 진행하셔도 좋으나 2주차 미션에서 따로 다루니 그때 연습해보셔도 좋을 것 같아요 😄 
희망하시면 해도 괜찮지만, 1주차 미션이 너무 밀리면 여러개 진행하시기가 힘드실 것 같습니다 
1주차 미션은 인수 테스트와 친해지는 것이 목적이니 인수테스트를 모두 구현하고 통과시키는 것에 집중해보세요 🔥

2023-07-04 12:56 UTC, pch8388 commented on src/test/java/subway/StationAcceptanceTest.java
> +        ExtractableResponse<Response> YeosamStationCreationRes = 지하철역_생성(역삼역);
변수로 할당 받지 않아도 될 응답인거 같아요
변수에 할당되면 어딘가에 쓸것이라는 추측을 하게 되는 것 같습니다 😄 
그리고, 네이밍 규칙을 일관성있게 유지하면 좋을 것 같아요. 바로 위의 변수는 카멜케이스인데, 이것은 파스칼 케이스네요 😅

2023-07-04 12:56 UTC, pch8388 commented on src/test/java/subway/StationAcceptanceTest.java
> +        ExtractableResponse<Response> getStationRes = 지하철역_조회();
지하철역 조회를 삭제여부검증 안에서 해도 될 것 같은데 어떻게 생각하세요? 🤔

2023-07-04 12:56 UTC, pch8388 commented on src/test/java/subway/StationAcceptanceTest.java
> +        String stationUrl = gangnamStationCreationRes.response().getHeader("Location");
응답을 바로 받는 방법은 없을까요? gangnamStationCreationRes 를 꼭 거쳐야 하나요? 💭

2023-07-04 12:56 UTC, pch8388 commented on src/main/java/subway/vo/LineRequest.java
> +package subway.vo;
VO 라는 네이밍에 대해서는 여러가지 이야기가 많지만 최근에는 어느정도 정리가 되었다고 생각합니다.
[Value Object 참고](https://martinfowler.com/eaaCatalog/valueObject.html)
현재 vo 패키지에 있는 객체들은 [Data Transfer Object](https://martinfowler.com/eaaCatalog/dataTransferObject.html) 의 성격이라고 생각됩니다 😄

2023-07-05 00:20 UTC, michaelkimm commented on src/main/java/subway/service/LineService.java
> +        // Response 객체로 변환
@pch8388 한줄 안에 코드의 의도가 보이니 필요가 없겠군요! 제거했습니다:)

2023-07-05 00:21 UTC, michaelkimm commented on src/test/java/subway/LineAcceptanceTest.java
> +public class LineAcceptanceTest extends AcceptanceTest {
@pch8388 PR 올리기 전에 전체 코드를 돌려보는 습관을 들여야겠군요😢 감사합니다:)

2023-07-05 00:22 UTC, michaelkimm commented on src/main/java/subway/jpa/StationRepository.java
> +    List<Station> findAllByLineName(String name);
@pch8388 Station 엔티티에 lineName을 선언해주지 않았었네요. 전체 테스트 습관을 들여보겠습니다:)

2023-07-05 00:22 UTC, michaelkimm commented on src/main/java/subway/service/LineService.java
> +                    })
@pch8388 훨신 더 깔끔하네요! 한줄로 리턴 값을 만들 수 있으니 가능한거군요! 적극 도입해보겠습니다😄

2023-07-05 00:50 UTC, michaelkimm commented on src/test/java/subway/StationAcceptanceTest.java
> +        ExtractableResponse<Response> getStationRes = 지하철역_조회();
@pch8388 인수 테스트는 블랙박스 테스트이기 때문에 지하철의 삭제 여부를 검증하려면 지하철역 조회를 해야하지 않나요❓

2023-07-05 00:56 UTC, michaelkimm commented on src/test/java/subway/StationAcceptanceTest.java
> +        ExtractableResponse<Response> getStationRes = 지하철역_조회();
@pch8388 또한 주어진 given, when, then 요구사항에서 '지하철역 목록 조회'를 요구하여, 지하철역 조회를 구현한 것도 주 이유중 하나입니다! 혹 리뷰어님은 삭제 인수 테스트에서 조회가 필요 없다고 생각하신건가요?🙂 혹은 delete 요청에 대한 response만으로 검증해도 된다고 생각하신건가요? 피드백 주신 의도가 궁금합니다!

- 지하철 역 삭제 인수 테스트 요구사항 -
/**
     * Given 지하철역을 생성하고
     * When 그 지하철역을 삭제하면
     * Then 그 지하철역 목록 조회 시 생성한 역을 찾을 수 없다
     */

2023-07-05 01:36 UTC, michaelkimm commented on src/main/java/subway/vo/LineRequest.java
> +package subway.vo;
@pch8388 동의합니다! LineRequest의 객체들은 값이 같다고 해서 동일하다고할 수 없으니 DTO가 맞겠군요! 반영하겠습니다!

2023-07-05 01:49 UTC, michaelkimm commented on src/test/java/subway/StationAcceptanceTest.java
> +        String stationUrl = gangnamStationCreationRes.response().getHeader("Location");
@pch8388 응답을 바로 받는 방법이라는 것이 잘 이해가 안됩니다! 아래 방식을 생각하신건가요?

```suggestion
        String stationUrl = 지하철역_생성(강남역).response().getHeader("Location");
```

gangnamStationCreationRes를 명시적으로 만드는 이유는 아래와 같이 인수 테스트의 then(검증) 코드를 두개의 ExtractableResponse<Response>로 표현하기 위해서입니다. E2E 인수 테스트 특성상 when과 then을 위한 api가 한개씩 존재해야한다고 생각했어요. 이에 검증 메소드도 두 api의 응답을 매개변수로 받아야한다고 생각했습니다.  


```
private static void 역_삭제_여부_검증(ExtractableResponse<Response> creationRes, ExtractableResponse<Response> getStationRes) {
        String 삭제된_역 = creationRes.jsonPath().getString("name");

        assertThat(getStationRes.jsonPath().getList("name")).doesNotContain(삭제된_역);
    }
```

2023-07-05 01:55 UTC, michaelkimm commented on src/test/java/subway/service/LineServiceTest.java
> +class LineServiceTest {
@pch8388 이해했습니다! 인수테스트를 주로 진행해보겠습니다:)

2023-07-05 11:53 UTC, michaelkimm commented on src/main/java/subway/service/LineService.java
> +        Line lineEntity = ModelMapperUtil.modelMapper.map(lineRequest, Line.class);
@pch8388 동의합니다! mapper를 사용하면 유효성 검증과 같은 비즈니스 로직을 사용할 수 없겠군요! 새로 커밋한 코드에는 Controller dto와 service dto를 분리하고, 더 자주 바뀌는 클래스가 덜 자주 바뀌는 클래스를 팩토리 메소드 등으로 만드는 방식을 택했습니다!

2023-07-05 11:57 UTC, michaelkimm commented on src/test/java/subway/LineAcceptanceTest.java
> +        assertThat(노선_조회_결과.jsonPath().getList("stations", StationResponse.class))
EtoE 인수 테스트는 요구사항 스펙과 명세를 대표하기에 HTTP response의 body 값이 정해진 형식대로 왔는지 전부 꼼꼼히 검증하는게 맞다고 생각하는데 승철님은 어떻게 생각하시나요? 이 코드를 짜면서도 이게 정말 맞을까..🤔 싶었어서 여쭤봅니다!

2023-07-05 15:29 UTC, pch8388 approved these changes
전체적으로 피드백 반영 잘해주셨습니다 👏 
남겨드린 코멘트 확인해주시고 3단계 바로 진행하시죠 🚀

2023-07-05 15:29 UTC, pch8388 commented on src/main/java/subway/service/LineService.java
> +                .orElseThrow(() -> new IllegalArgumentException(String.format("상행역이 존재하지 않습니다. id:{}", lineDto.getUpStationId())));
```suggestion
                .orElseThrow(() -> new IllegalArgumentException(String.format("상행역이 존재하지 않습니다. id:%s", lineDto.getUpStationId())));
```

와 같이 해야 의도하신 대로 동작할 것 같아요 😄

2023-07-05 15:29 UTC, pch8388 commented on src/test/java/subway/LineAcceptanceTest.java
> +    private static void 지하철_노선_생성_여부_검증(ExtractableResponse<Response> 노선_목록_조회_결과, Map<String, String> 노선_생성_요청_정보, Map<String, String> 상행역_정보, Map<String, String> 하행역_정보) {
`상행역_정보` 와 `하행역_정보` 는 사용하지 않는 것 같은데, 제외시켜도 되지 않을까요? 👀

2023-07-05 15:29 UTC, pch8388 commented on src/test/java/subway/LineAcceptanceTest.java
> +    private static void 지하철_노선_목록_검증(ExtractableResponse<Response> 노선_목록_조회_결과, Map<String, String> 노선1_생성_요청_정보, Map<String, String> 상행역1_정보, Map<String, String> 하행역1_정보, Map<String, String> 노선2_생성_
코드라인이 가로로 너무 길어지면 가독성이 떨어지는 것 같아요(물론 요즘 모니터는 좋아서 잘 보이긴 하지만 💦 )
클린코드에서 로버트 C.마틴은 120자 정도로 글자수를 제한 하라는 조언을 하는 데, 어느정도 보기좋게 개행하는 것이 좋다고 생각합니다 😄

2023-07-05 15:29 UTC, merged