2단계 - 지하철 노선 관리
next-step/atdd-subway-map pull request #895
Opened 2023-07-04 15:39 UTC by Eunhee0119

안녕하세요. 한솔님:]
2단계 미션 구현했습니다! 리뷰 요청드려요^^

2023-07-05 05:37 UTC, catsbi requested changes
은희님 2단계 노선 관리 미션 잘 구현해주셨어요 👍 
몇 가지 피드백 남겨드렸는데 확인 후 다시 리뷰요청 해주세요! 😁

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/controller/LineController.java
> +import org.springframework.web.bind.annotation.*;
import wildcard(`*`)는 최대한 사용을 지양하라고하는데 어째서일까요?!

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/controller/LineController.java
> +    @PostMapping("/line")
Restful API설계시 Resource 이름은 단수보다는 복수로 지칠하는것을 권장합니다. 👍 
여기선 /line -> /lines가 좀 더 적절할 것 같네요!

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/controller/LineController.java
> +    public ResponseEntity<LineResponse> createLine(@RequestBody LineRequest lineRequest) {
수정과 생성에 사용되는 Request가 동일한데요. 생성시점과 수정시점에 필요 유효성이 달라질 수도 있고, 필요한 정보들의 갯수도 다를 수 있는데, CreateRequest, ModifyRequest로 구분지어보는건 어떨까요?

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/controller/LineController.java
> +    @PatchMapping("/line")
Put과 Patch 메서드의 차이점은 뭘까요? 

미션에서 요구하는 명세에서는 PUT인데 Patch로 한 이유가 있을까요?! 
실제 프로토콜이 확정된다면 협업하는 다른 팀에서는 해당 스펙을 가지고 개발을 할 텐데, 이렇게 다른 방식으로 개발되면 이슈가 등록될 확률이 높아질 수 있을 것 같아요.

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/domain/Line.java
> +
불필요한 공백을 제거해주세요!

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/dto/LineRequest.java
> +
불필요한 공백을 제거해주세요!

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/dto/LineRequest.java
> +    private Long id;
CreateRequest였다면 해당 필드는 불필요했겠죠?!

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/dto/LineResponse.java
> +public class LineResponse {
미션에서 요구하는 응답 스펙은 다음과 같아요. 해당 응답 객체가 이 스펙을 충족할 수 없을 것 같아요 👀
![image](https://github.com/next-step/atdd-subway-map/assets/43158866/8292a9b6-8c9e-47e9-a92c-c305803efa0e)

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/service/LineService.java
> +        stationRepository.findById(lineRequest.getDownStationId()).orElseThrow(()-> new IllegalArgumentException("존재하지 않는 역입니다."));
- 코드의 중복이 보이네요! 어떻게 없앨 수 있을까요?
- 노선 서비스에서 지하철역 정보에 대한 예외처리까지 책임지고 있는데 적절한 책임일까요?

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/service/LineService.java
> +        Line line = lineRepository.save(new Line(lineRequest.getId(),lineRequest.getColor(),lineRequest.getName(),lineRequest.getUpStationId(),lineRequest.getDownStationId(),lineRequest.getDistance()
직접 생성자에 모든 필드를 getter로 집어넣으니 코드 가독성이 많이 떨어지고, 휴먼 에러도 발생하기 쉬울 것 같아요. 
특히 상행역 하행역같은경우 필드 타입도 같은데 실수로 뒤바뀌어 넣게된다면, 컴파일러나 런타임에러가 안생기기 때문에 나중에 발견되어 더 큰 문제가 될 수 있을 것 같네요. 

빌더패턴을 사용해보거나, Request객체에서 toEntity메서드를 제공해보는건 어떨까요?

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/service/LineService.java
> +        if(lineRequest.getDistance() != 0) line.setDistance(lineRequest.getDistance());
- 단 한줄이라도 블럭`{}` 생략은 지양해주세요. 코드의 가독성 및 일관성이 꺠질 수 있습니다!
- 현재 서비스 계층에서 직접 비교 및 수정을 수행하고 있는데, 이는 트랜잭션 스크립트 패턴으로 도메인의 책임을 서비스가 가져가버려서 도메인은 사실상 구조체의 역할만 하도록하고 서비스에서 모든 책임을 가져가는 문제가 있어요. 책임을 적절히 분리해보면 어떨까요?

2023-07-05 05:37 UTC, catsbi commented on src/main/java/subway/service/LineService.java
> +    private LineResponse createLineResponse(Line line) {
응답 객체 생성의 책임을 서비스가 아닌 Response가 직접 가지도록 하는건 어떨까요?

2023-07-05 05:37 UTC, catsbi commented on src/test/java/subway/StationLineTest.java
> +    void createLineTest() {
노선 정보를 생성하면, location 헤더 속성으로 식별자가 전달되어올텐데 이를 통해 검증하는건 어떨까요?

2023-07-05 05:37 UTC, catsbi commented on src/test/java/subway/StationLineTest.java
> +        createLine("신분당선","bg-red-600", 신사역, 광교역 , 10);
중복되는 매직리터럴은 상수로 분리하고 픽스쳐 역시 분리해보는건 어떨까요?

2023-07-08 14:23 UTC, Eunhee0119 commented on src/main/java/subway/controller/LineController.java
> +import org.springframework.web.bind.annotation.*;
다른 패키지에 동일한 클래스가 존재할 수도 있기 때문에 실수를 방지하기 위해서 라고 알고 있습니다! 
IDE가 import 해주는 기능 그대로 사용했었는데, 이 부분에 대해 좀 더 주의할 필요가 있겠네요:]

2023-07-08 14:29 UTC, Eunhee0119 commented on src/main/java/subway/controller/LineController.java
> +    @PatchMapping("/line")
Put의 경우 리소스를 전체를 업데이트 할 경우에 사용하고 Patch는 일부분만 수정할 경우 사용한다고 알고 있습니다. 
노선 정보 전체를 수정하는 것이 아니라 부분 수정이라 생각하고 patch가 더 맞을 것이라 생각하고 작성했는데, 명세를 확인 못했네요 ㅠㅜ

2023-07-08 14:30 UTC, Eunhee0119 commented
안녕하세요 한솔님! 2단계 수정사항 반영했습니다.!

---- 수정사항 ----
import wildcard(*) 수정
Restful API URL 수정
노선 생성, 수정 Request 분리
Patch 메서드 -> Put
빌터패턴 적용
도메인 책임 분리
빌더패턴 적용
픽스쳐 분리

2023-07-09 04:58 UTC, lhs0610 approved these changes
은희님 2단계 피드백 반영 잘 해주셨네요!
몇 가지 피드백 남겨드렸으니 다음 미션 진행하시며 같이 고민해보시면 좋을 것 같습니다. 
이만 머지하도록 할게요 👍

2023-07-09 04:58 UTC, lhs0610 commented on src/main/java/subway/controller/LineController.java
> +    @PostMapping("/lines")
/lines 라는 resource가 메서드마다 중복되는 것 같네요! 클래스레벨 공통으로 올려도 될 것 같네요 👍

2023-07-09 04:58 UTC, lhs0610 commented on src/main/java/subway/domain/Line.java
> +    }
단순한 setter보단 좀 더 의도를 나타내는 네이밍을 지어보는건 어떨까요? 
단순 setXXX는 그저 값을 바꾼다는 의미이기 때문에 어디서든 호출할 수 있고 의도를 파악하기 힘들어 디버깅을 힘들게 해주는 요소가됩니다

2023-07-09 05:00 UTC, lhs0610 approved these changes
앗 실수로 request change를 했나보네요 다시 merge하겠습니다

2023-07-09 05:02 UTC, merged