3단계 지하철 구간관리 구현
next-step/atdd-subway-map pull request #926
Opened 2023-07-08 14:55 UTC by yyy9942

안녕하세요 리뷰어님. 구간관리 기능을 구현해보았습니다. 리뷰부탁드립니다.

기존에는 구간이 아니라 역 -  노선역 -  노선 관계로 구현했는데요, 구간이라는 개념이 등장하며 노선역을 제거하고 구간을 도입했습니다.
즉 역 - 구간 - 노선 관계로 변경하여 구현하였습니다.

2023-07-08 23:48 UTC, testrace requested changes
안녕하세요 정준님 😃 
3단계 미션 잘 구현하셨네요 👍 
몇 가지 코멘트 남겨두었는데 확인해 주시고 리뷰 요청해 주세요
궁금한 점이나 의견 있으시면 언제든 DM 부탁드려요

2023-07-08 23:48 UTC, testrace commented on src/main/java/subway/Station.java
> +    private long sequence = 0L;
sequence 변수는 사용되고 있지 않네요 😢 
어떤 용도로 추가하셨나요?

2023-07-08 23:48 UTC, testrace commented on src/main/java/subway/line/Line.java
> +        return optionalSection.orElseThrow();
일급 컬렉션으로 만들어서 Section 과 관련된 책임을 위임하면 어떨까요?

2023-07-08 23:48 UTC, testrace commented on src/main/java/subway/section/Section.java
> +  private Long sequence;
sequence 필드를 가지게 되면 관련된 비즈니스 로직이 필요해 보이는데요
동일 노선의 구간들이 동일한 sequence를 가지게 되면 의도하지 않는 결과가 나올 것 같아요

상행역과 하행역을 linkedList의 이전 노드, 다음 노드처럼 활용하면 구간들의 순서를 알 수 있으니 sequence 변수는 제거해도 될 것 같은데 정준님 생각은 어떠신가요?

2023-07-08 23:48 UTC, testrace commented on src/main/java/subway/section/Section.java
> +      this.sequence = line.getNextSequence();
NPE 발생할 수 있을 것 같아요 😢 
NPE 방어를 위한 코드를 작성하려면 복잡도가 올라갈 것 같은데요
sequence가 필요한지 다시 고민해볼 수 있는 코드인 것 같아요

2023-07-08 23:48 UTC, testrace commented on src/main/java/subway/section/StationDoesNotMatchException.java
> +        super("역이 일치하지 않습니다.");
커스텀 예외를 자주 사용하시네요 👍 
예외 메시지에 예외와 관련된 내용을 조금 더 상세하게 담으면 어떨까요?
StationDoesNotMatchException 는 하행 종점역 삭제 시 사용되니 `xx역은 하행 종점역이 아닙니다` 같은 메시지를 담으면 디버깅에도 유용할 것 같아요

2023-07-08 23:48 UTC, testrace commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @DisplayName("지하철 구간 등록시 구간의 하행 종점역과 요청시 상행 종점역이 일치하지 않으면 예외가 발생한다.")
인수 조건이 누락되었네요 😢 
프로그래밍 요구사항에 맞게 요구사항 설명을 참고해서 인수 조건(시나리오)를 주석으로 먼저 작성하시면 좋을 것 같아요

2023-07-08 23:48 UTC, testrace commented on src/test/java/subway/SectionAcceptanceTest.java
> +                .containsExactly("야탑역", "이매역");
구간을 삭제하거나, 역 목록을 조회하여 검증하는 코드가 반복되니 리팩토링해서 재사용성을 높이면 어떨까요?
노선 인수테스트, 지하철 역 인수 테스트에서도 비슷한 코드가 있다면 재사용성과 가독성을 높일 수 있을 것 같아요

2023-07-09 03:15 UTC, yyy9942 commented on src/main/java/subway/Station.java
> +    private long sequence = 0L;
Section. 즉 구간이 존재한다면 구간의 순서도 존재해야하기 떄문에 추가하였습니다.

2023-07-09 03:15 UTC, yyy9942 commented on src/main/java/subway/section/Section.java
> +  private Long sequence;
구간이라는걸 관리하라는 요구사항으로 이해하였는데요, 구현 요구사항이 LinkedList형식이라면 수정해두겠습니다

2023-07-09 04:04 UTC, yyy9942 commented on src/main/java/subway/Station.java
> +    private long sequence = 0L;
LinkedList형태로 바꾸면 필요하지 않아보여 제거하겠습니다~

2023-07-09 04:27 UTC, yyy9942 commented on src/test/java/subway/SectionAcceptanceTest.java
> +                .containsExactly("야탑역", "이매역");
네 수정해두도록 하겠습니다

2023-07-09 14:02 UTC, testrace approved these changes
안녕하세요 정준님 😃 
피드백 반영 잘해주셨네요 👍 
1주차 미션은 여기서 마무리 하겠습니다
다음 미션도 화이팅입니다 🚀

2023-07-09 14:02 UTC, merged