3단계 - 지하철 구간 관리입니다.
next-step/atdd-subway-map pull request #929
Opened 2023-07-09 08:59 UTC by SongTeaheon

구조 변경을 약간 진행했습니다.
- ASIS: controller -> service -> repository
- TOBE: controller -> CompositeService -> Service -> Repository

2023-07-09 09:04 UTC, SongTeaheon commented on src/main/java/subway/controller/LineController.java
> +    private final LineCompositeService lineCompositeService;
lineService -> lineCompositeService

2023-07-09 09:04 UTC, SongTeaheon commented on src/main/java/subway/controller/StationController.java
> +    private final StationCompositeService stationCompositeService;
stationService -> stationCompositeService

2023-07-09 09:04 UTC, SongTeaheon commented on src/main/java/subway/model/line/LineRepository.java
> +interface LineRepository extends JpaRepository<Line, Long> {
public -> internal로 변경해서 해당 repository는 같은 패키지에 있는 LineService에서만 사용하도록 변경했습니다.

2023-07-09 09:04 UTC, SongTeaheon commented on src/main/java/subway/model/section/SectionService.java
> +                                .orElseThrow(() -> new IllegalArgumentException("section id doesn't exist"));
repository 래핑 클래스를 만든 이유는 위 로직이 계속 반복해서 발생해서 입니다.   
래핑 클래스를 안만드는 경우, 이런 로직들을 하나로 합칠 수가 있을까요..?

2023-07-09 09:04 UTC, SongTeaheon commented on src/test/java/subway/LineAcceptanceTest.java
> -    private static ExtractableResponse<Response> callApiToGetLines() {
ApiHelper 클래스로 옮겼습니다.

2023-07-09 12:08 UTC, hiblue02 commented on src/test/java/subway/LineAcceptanceTest.java
> -    private static ExtractableResponse<Response> callApiToGetLines() {
반복되는 RestAssured 호출을 클래스로 분리해주셨군요! :+1:

2023-07-09 14:52 UTC, hiblue02 commented
안녕하세요! 3단계 미션이 많이 어려웠는데, 빨리 해주셨네요! 💯 
(JPA 수업은 아니지만...) 전체적으로 영속성 전이 대해서 고민해봐주시면 좋을 것 같아요.

2023-07-09 14:55 UTC, hiblue02 requested changes
태헌님! 3단계 미션도 잘 구현해 주셨네요! 💯 
몇가지 코멘트 남겼는데, 확인해주시고 다시 요청주세요!

2023-07-09 14:55 UTC, hiblue02 commented on src/main/java/subway/model/line/Line.java
> +    List<Section> sections;
적절한 책임 분리를 위해서 List`<Section`>을 다루는 일급 컬렉션(Sections)를 만들어보는 건 어떨까요?

2023-07-09 14:55 UTC, hiblue02 commented on src/main/java/subway/controller/SectionController.java
> +    @GetMapping(value = "/lines/{lineId}/sections")
SectionController인데 URI는 lines로 시작하네요. Section은 모두 Line의 라이프사이클에 종속되기 때문에, LineController에서 관리 책임을 가져도 될 것 같아요. :smile:

2023-07-09 14:55 UTC, hiblue02 commented on src/main/java/subway/controller/SectionController.java
> +    }
line을 만드는게 아니라, section을 만들어서 추가하는 api 보이는데요.
createLine 이름이 적절할까요? :thinking:

2023-07-09 14:55 UTC, hiblue02 commented on src/main/java/subway/controller/SectionController.java
> +    }
line을 지우는게 아니라, section만 지우는 api 보이는데요.
deleteLine 이름이 적절할까요? :thinking:

2023-07-09 14:55 UTC, hiblue02 commented on src/main/java/subway/service/SectionCompositeService.java
> +        line.addSection(newSection);
line에 section이 종속되는데요. sectionService의 save를 따로 호출해야 할까요? :thinking:

영속성 전이에 대해 고민해보시면 좋을 것 같아요.

2023-07-09 14:55 UTC, hiblue02 commented on src/main/java/subway/service/SectionCompositeService.java
> +        sectionService.deleteById(targetSection.getId());
line에 section이 종속되는데요. section을 따로 조회해야 할까요? 또 sectionService의 delete를 따로 호출해야 할까요? :thinking:
영속성 전이에 대해 고민해보시면 좋을 것 같아요.

2023-07-09 14:55 UTC, hiblue02 commented on README.md
> +- [X] 새로운 구간 제거시 위 조건에 부합하지 않는 경우 에러 처리한다.
요구사항을 상세하게 작성해주셨네요! :+1:

2023-07-09 14:55 UTC, hiblue02 commented on src/main/java/subway/model/section/SectionService.java
> +                                .orElseThrow(() -> new IllegalArgumentException("section id doesn't exist"));
음 보통은 findById와 Exception 처리가 중복을 없애기 위해서라기 본다는, repository가 다른 도메인 Service와 직접적인 연관을 맺도록 하지 않기 위해서 service를 분리합니다. :smile:

클래스를 안 만들고 로직을 하나로 합친다는 의미는 서비스 1개에 repository를 여러개 주입한다는 말씀이실까요?  그렇다면 위 문장으로 답변이 될 것 같은데 한번 고민해주세요!

2023-07-09 14:59 UTC, hiblue02 commented on src/main/java/subway/model/section/SectionService.java
> +                                .orElseThrow(() -> new IllegalArgumentException("section id doesn't exist"));
음 보통은 findById와 Exception 처리가 중복을 없애기 위해서라기 본다는, repository가 다른 도메인 Service와 직접적인 연관을 맺도록 하지 않기 위해서 service를 분리합니다. 😄

클래스를 안 만들고 로직을 하나로 합친다는 의미는 서비스 1개에 repository를 여러개 주입한다는 말씀이실까요? 그렇다면 위 문장으로 답변이 될 것 같은데 한번 고민해주세요!

2023-07-10 10:55 UTC, SongTeaheon commented on src/main/java/subway/model/line/Line.java
> +        return stations;
https://github.com/next-step/atdd-subway-map/pull/929/commits/ebb4ff11d3178ba131343b4b2be4471d4275c2b8#diff-b6b9d55bfe17d46db8f74024bde36d5693b666994c01f8b1b507a877d7567a54R8

이쪽 커밋 보면, StationDTO를 만들어서 이를 리턴하도록 변경했습니다. 해당 DTO는 setter가 없어서 변경이 불가능한 불변객체인데요. 이를 의미하신게 맞나요?

2023-07-10 10:58 UTC, SongTeaheon commented on src/test/java/subway/SectionAcceptanceTest.java
> +                           .collect(Collectors.toList())).contains(expectedStationNames);
https://github.com/next-step/atdd-subway-map/pull/929/commits/6313eb97a8c045c022e5564cdaac618f9dfdd4a2#diff-a0290ecc8a8b33651a4f26b18597120732c2f17bf9f3be8c3c20f977ba15bf7fR240

위 커밋처럼 assertAll을 사용했습니다. 제가 assertj를 쓰다가 jupiter의 assertion을 섞어서 쓰니까 약간 코드가 헷갈리다는 느낌을 받았는데요. 사용하실 때, assertj의 Assertion과 jupiter의 Assertion을 섞어 쓰기도 하시나요? 

혹은 이런 경우에는 jupiter만 사용하시는걸까요?

2023-07-10 11:03 UTC, SongTeaheon commented on src/test/java/subway/service/LineCompositeServiceIntegrationTest.java
> +        }
line.getStations()은 entity이지만 stationNames을 가져온 객체는 LineResponse라서 객체 자체를 비교하기는 어렵지 않을까 싶은데.. 다른 의견이 이실까요? containsAll은 적용했습니다.

2023-07-10 11:05 UTC, SongTeaheon commented on src/main/java/subway/model/line/Line.java
> +    }
제가 이 부분을 이해를 못하고 있는 거 같습니다.. 제가 이해하기로는 객체가 같기 때문에 session이 사라지지 않는 걸로 이해하고 있는데 잘 못 이해하고 있을까요?

그리고 `this.sections.add(newSection)`을 하면, unsupportedOperationException이 발생해서 위와 같이 수정했습니다. 찾아보니까 PersistantBag은 immutableList라서 이런 오류가 발생한다고 하네요. 

혹시 제가 잘못 알고 있는 부분이 있나요?

2023-07-10 11:07 UTC, SongTeaheon commented on src/main/java/subway/model/line/Line.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "line", cascade = CascadeType.ALL)
https://github.com/next-step/atdd-subway-map/pull/929#discussion_r1258085968

위 코멘트가 작성된 부분에서 sections을 떼어서 새로 만들기 때문에 orphanRemoval = true를 설정하면 delete가 발생하게 됩니다. 이 부분 때문에 orphanRemoval = true를 설정하지 못하는데요. 결국 PersistentBag이 Immutable LIst라서 위 코드를 설정한 것인데요. 

뭔가 다른 방법이 있을까요? 제가 잘못알고 있나 해서요.

2023-07-10 11:11 UTC, SongTeaheon commented on src/main/java/subway/service/SectionCompositeService.java
> +        sectionService.deleteById(targetSection.getId());
[or](https://github.com/next-step/atdd-subway-map/pull/929#discussion_r1258087884)

위 코멘트처럼 orphanRemoval = true를 설정하고 있지 않기 때문에 remove만 한다고 삭제가 자동으로 되지는 않고, deleteById를 호출해야하는 걸로 이해하고 있습니다. 제가 잘못 알고 있는걸까요..?

2023-07-10 12:27 UTC, hiblue02 commented on src/main/java/subway/model/line/Line.java
> +        return stations;
Collection 불변객체를 말씀드린 거였어요! [링크](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/)를 참고해보세요. ㅎㅎ

2023-07-10 12:27 UTC, hiblue02 commented on src/test/java/subway/SectionAcceptanceTest.java
> +                           .collect(Collectors.toList())).contains(expectedStationNames);
섞어쓰기도 합니다.  😄

2023-07-10 12:37 UTC, hiblue02 commented on src/test/java/subway/service/LineCompositeServiceIntegrationTest.java
> +        }
LineResponse를 반환하고 있었군요. ㅠ Line을 반환하는 걸로 보고 리뷰드렸네요. 말씀하신데로 LineResponse 객체이기 때문에 객체 자체를 비교하긴 어렵겠네요.

2023-07-10 13:18 UTC, hiblue02 commented on src/main/java/subway/model/line/Line.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "line", cascade = CascadeType.ALL)
1. List<Section> sections에서 new ArrayList<>(); 초기화를 안해주셔서 그런 것 같아요. ㅠ
2. 그런데, @builder 때문에, 초기화를 하게되면 오류가 날텐데요. [링크](https://velog.io/@mooh2jj/%EC%98%AC%EB%B0%94%EB%A5%B8-%EC%97%94%ED%8B%B0%ED%8B%B0-Builder-%EC%82%AC%EC%9A%A9%EB%B2%95#:~:text=%EC%9D%B4%EB%95%8C%2C%20%27%EC%9D%98%EB%AF%B8%EC%9E%88%EB%8A%94%20%EA%B0%9D%EC%B2%B4%27%20%EC%83%9D%EC%84%B1%EC%9D%84%20%EC%9C%84%ED%95%B4%EC%84%9C%20%40Builder%20%EC%9D%84%20%EC%82%AC%EC%9A%A9%ED%95%A0,1%29%20%ED%81%B4%EB%9E%98%EC%8A%A4%EC%97%90%20%40Builder%EB%A5%BC%20%EB%B6%99%EC%9D%B4%EA%B8%B0%202%29%20%EC%83%9D%EC%84%B1%EC%9E%90%EC%97%90%20%40Builder%EB%A5%BC%20%EB%B6%99%EC%9D%B4%EA%B8%B0)를 참고해주세요. 😄

2023-07-10 13:19 UTC, hiblue02 commented on src/main/java/subway/service/SectionCompositeService.java
> +        sectionService.deleteById(targetSection.getId());
위에 답변 남긴 부분 참고해주세요!

2023-07-12 09:24 UTC, SongTeaheon commented on src/main/java/subway/model/line/Line.java
> +    }
이 부분은 제가 builder로 생성할 때, List.of(section)으로 넣어주고 있었는데, 이 부분이 immutable이라서 발생한 오류였습니다 ㅠㅠ

2023-07-12 09:26 UTC, SongTeaheon commented on src/main/java/subway/model/line/Line.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "line", cascade = CascadeType.ALL)
감사합니다!! builder로 사용하면서 immutable list를 제가 넣어주고 있어서 위 문제가 났었습니다..
주신 링크 참조해서 sections는 builder에서 세팅하지 않고, 따로 addSections를 호출하도록 변경했습니다!

2023-07-12 13:19 UTC, hiblue02 approved these changes
태헌님! 리뷰드린 내용 꼼꼼하게 반영해주셨네요 💯 
1주차 미션 수행하시느라 너무 고생 많으셨습니다. 👏 👏 👏 
다음 미션도 화이팅입니다!

2023-07-12 13:19 UTC, hiblue02 commented on src/main/java/subway/controller/LineController.java
>      }
SectionController의 기능을 LineController로 이동해주셨군요! 👍 리뷰반영 💯

2023-07-12 13:19 UTC, hiblue02 commented on src/main/java/subway/model/line/Line.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
Line 클래스가 깔끔해졌네요! 👍

2023-07-12 13:19 UTC, hiblue02 commented on src/main/java/subway/model/section/SectionService.java
> -
SectionService도 정리해주셨네요! 💯

2023-07-12 13:19 UTC, hiblue02 commented on src/main/java/subway/model/line/Line.java
> +        return Collections.unmodifiableList(stations);
unmodifiableList 적용 👍

2023-07-12 13:19 UTC, hiblue02 commented on src/test/java/subway/SectionAcceptanceTest.java
> +        Assertions.assertAll(
assertAll 사용 👍

2023-07-12 13:19 UTC, hiblue02 commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @Nested
@Nested는 비슷한 테스트를 묶는 기능인데요. 
여기서는 Line 생성 결과(id)를 가지고 검증하기 때문에 적합하지 않은 것 같네요. 혼선을 드려 죄송합니다. 😭 
이런 기능이 있구나 정도로만 기억해주세요. 😅

2023-07-12 13:19 UTC, hiblue02 commented on src/main/java/subway/service/LineCompositeService.java
> +        section.setLine(newLine); // TODO: 삭제
깜빡 하신 것 같네요. 😅

2023-07-12 13:19 UTC, merged

2023-07-15 16:17 UTC, SongTeaheon commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @Nested
@nested는 비슷한 역할의 테스트를 묶는 역할로 이해하고 있고, test result를 깔끔하게 정리하는 용도로 이해하고 있는데요. 

생성 결과를 검증하는 것이 @Nested와 적합하지 않은 이유가 무엇인가요..? 잘 이해를 못해서요..

2023-07-16 13:01 UTC, hiblue02 commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @Nested
앗.. 제가 명확하게 코멘트를 남기지 않아 혼선이 있었군요. ㅠ 
말씀하신 것 처럼 @Nested는 크게 2가지 용도로 사용합니다. 

1. 테스트 코드의 given절이 중복되는 경우
2. 테스트 코드의 맥락이 비슷한 경우 ( ex. 삭제 테스트 여러개) > 가독성 증가

2번 케이스로 @Nested를 잘 적용해주셨어요!
다만 1번 케이스로 given절을 한 곳으로 모을 수 있다는 의미로 말씀드렸던 거라, 요 의미에선 given이 테스트별로 다르고, 테스트의 결과 (id)를 검증에 사용하고 있어서 @Nested가 적합하지 않다는 의미였어요. 

다시 한 번 명확하게 전달하지 못해 죄송합니다. 😭 
테스트의 가독성을 위해 구간 삭제, 구간 생성으로 케이스를 분류해주신 점은 아주 좋았어요! 👍 👍 💯