3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #943
Opened 2023-07-11 16:40 UTC by toongri

2023-07-14 10:15 UTC, heoseungyeon requested changes
안녕하세요 준형님

3단계도 열심히 미션 수행해주셨네요 🔥 

다만, 구간 삭제 기능이 누락되어 있는 것 같은데 한번 확인해주시고 다시 리뷰 요청 부탁드릴게요 :)

2023-07-14 10:15 UTC, heoseungyeon commented on src/test/java/subway/subway/acceptance/SubwaySectionAddAcceptanceTest.java
> +
리팩토링을 잘해주신 덕분에 인수테스트의 시나리오를 알아보기 쉬워진 것 같아요 👍

2023-07-15 15:03 UTC, toongri commented on src/main/java/subway/subway/adapter/in/web/SubwaySectionAddController.java
> +@RestController
추가했습니다 감사합니다!

2023-07-16 11:06 UTC, heoseungyeon approved these changes
안녕하세요 준형님! 

구간 삭제까지 기능 구현과 인수 테스트 작성하신 부분 확인했어요.
워낙 리팩토링이나 구현에 노력을 많이 하셔서 따로 수정이 필요한 부분이 없어보이네요 💯 

간단한 코멘트 남긴 부분 확인해주시고 이번 미션 진행하셨던 것 처럼 다음 단계 미션도 응원할게요 :)
고생하셨습니다 👍

2023-07-16 11:06 UTC, merged

2023-07-17 10:58 UTC, toongri commented on src/test/java/subway/subway/acceptance/SubwaySectionCloseAcceptanceTest.java
> +}
감사합니다 고생 많으셨습니다!

2023-07-17 10:59 UTC, toongri commented on src/main/java/subway/subway/adapter/in/web/SubwaySectionCloseController.java
> +    public ResponseEntity<Void> addSubwaySection(@PathVariable Long id, @RequestParam Long stationId) {
아 감사합니다 수정하겠습니다