🚀 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #954
Opened 2023-07-14 01:49 UTC by jjisun

### 3단계 요구사항
- [x] 지하철 구간 추가
- [x] 지하철 구간 삭제

인수테스트 작성을 한다고 했는데 좀 더 추가했으면 하는 케이스 있으면 코멘트 부탁드립니다!
개선사항 제안이나 리팩토링 부분에서도 코멘트 부탁드려요!

리뷰 감사합니다!! :) 👍

2023-07-14 13:45 UTC, seovalue requested changes
안녕하세요, 지선님ㅎㅎ 3단계 미션 잘 구현해주셨네요.
크게 수정해야할 부분은 없는 것 같은데, 사소한 리팩터링이라도 해보면 좋을 것 같아서요!
확인 후 다시 리뷰 요청 주세요! (지금도 요구사항은 모두 만족합니다 👍)

2023-07-14 13:45 UTC, seovalue commented on src/main/java/subway/exception/ApiExceptionHandler.java
> +    }
전반적인 서비스에서 발생할 수 있는 예외를 하나의 예외 (`ApiException`) 으로 일괄 관리해주시는 이유가 궁금해요. 저는 주로 NotFound, BadRequest 이렇게 `HttpStatus`에 따라서 상위 예외를 나누고 그 하위로 도메인별 예외를 두곤 했거든요. 단순 궁금증입니당 ㅎㅎ

2023-07-14 13:45 UTC, seovalue commented on src/test/java/subway/DatabaseCleanerTest.java
> +    void entities() {
어떤 의미를 갖는 테스트인가요?

2023-07-14 13:45 UTC, seovalue commented on src/test/java/subway/SectionAcceptanceTest.java
> +        assertThat(stations).containsAnyOf("양재시민의숲역");
```suggestion
        List<String> stations = LineAcceptanceTest.findLine(lineId).jsonPath()
            .getList("stations.name", String.class);
        assertThat(stations).containsAnyOf("양재시민의숲역");        // then
        var lineResponse = LineAcceptanceTest.findLine(lineId).as(LineResponse.class);
        assertThat(lineResponse.getStations().stream().map(StationResponse::getName)).containsAnyOf("양재시민의숲역");
```
LineResponse에 빈생성자가 있다면 이런 방법도 가능해요

2023-07-14 13:45 UTC, seovalue commented on src/test/java/subway/SectionAcceptanceTest.java
> +    ExtractableResponse<Response> deleteSection(Long stationId) {
이런 형태의 반복되는 API 요청들은 Fixture처럼 별도로 분리해두면 어떨까요?

2023-07-14 13:45 UTC, seovalue commented on src/main/java/subway/entity/Section.java
> +    private Long distance;
* 필수는 아니에요.
Section에서 distance를 관리하고 있는 만큼, 노선의 최종적인 distance 값을 구할 수 있기 위해 Sections에 getTotalDistance와 같은 메서드가 있으면 좋을 것 같아요. 노선이 추가/삭제될 때마다 거리에 변동이 생겨야하는데, 사실상 그걸 확인할 수 있는게 요구사항엔 없는 것 같은 점이 아쉬워서요..

2023-07-14 13:45 UTC, seovalue commented on src/main/java/subway/entity/Sections.java
> +        var lastSection = sections.get(sections.size() - 1);
구현해두신 `lastSection()`을 사용할 수 있지 않을까요?

2023-07-14 13:45 UTC, seovalue commented on src/main/java/subway/service/LineService.java
> +        return this.toLineResponse(line);
이 부분은 LineResponse.from() 과 같은 팩터리메서드로 책임을 이관할 수 있지 않을까요?

2023-07-14 13:45 UTC, seovalue commented on src/test/java/subway/SectionAcceptanceTest.java
> +     */
위랑 아래 테스트케이스가 같은 주석을 갖고 있는 것 같아요?

2023-07-17 00:27 UTC, jjisun commented on src/test/java/subway/DatabaseCleanerTest.java
> +    void entities() {
DatabaseCleaner 작성할때 엔티티 이름 호출 확인한다고 추가한 테스트인데 의미는 따로 없습니다.ㅎㅎ

2023-07-17 00:29 UTC, jjisun commented on src/test/java/subway/SectionAcceptanceTest.java
> +        assertThat(stations).containsAnyOf("양재시민의숲역");
이것도 좋은 방법이네요!

2023-07-17 04:45 UTC, jjisun commented on src/main/java/subway/exception/ApiExceptionHandler.java
> +    }
httpCode 와 errorMessage 만으로 예외가 구분이 된다 생각해서 하나만 만들어서 관리했습니다. 좀더 복잡하게 예외 처리가 되어야 한다면 말씀하신대로 구분해서 에외를 두고 관리하는편이 더 좋겠네요!

2023-07-17 09:38 UTC, jjisun commented
코멘트 남겨주신부분 리팩토링 해보았습니다! 확인 부탁드려요~

- [x] totalDistance 메소드 생성
- [x] LineResponse.from() 팩토리 매서드 이관
- [x] Fixture 분리
- [x] 주석수정

감사합니다 :)

2023-07-18 09:14 UTC, seovalue approved these changes
안녕하세요, 지선님!
리팩터링도 잘 수행해주셔서 이번 단계는 여기서 머지할게요~
고생 많으셨어요 👍  끝까지 화이팅이에요ㅎㅎ

2023-07-18 09:14 UTC, merged