🚀 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #957
Opened 2023-07-15 19:37 UTC by cohys7

안녕하세요!

3단계 지하철 구간 관리 미션 진행했습니다.
이전 단계 리뷰 주신 사항들도 함께 반영했는데 확인 부탁드립니다!

감사합니다~

2023-07-15 19:49 UTC, cohys7 reviewed
우선은 인수조건을 최대한 자세하게 만들고,
다음으로 Line, Section, Station 간의 관계를 어떻게 할지 많이 고민했는데,
JPA가 익숙하지 않아 구조가 좀 이상해진 것 같습니다... ㅜㅜ

요구 사항을 제대로 이해했는지 모르겠네요...
더 괜찮은 구조가 있다면 조언 부탁드립니다!

2023-07-15 19:49 UTC, cohys7 commented on README.md
> +Then 해당 노선의 하행 종점역과 거리가 업데이트 된다.
인수 조건을 도출하는 과정이 익숙하지 않은데,
이렇게 when과 then이 많아지는 경우에는 따로 분리하는 것이 좋을까요?

2023-07-15 19:49 UTC, cohys7 commented on src/test/java/helper/RequestApiHelper.java
> +    public static ExtractableResponse<Response> get(String path) {
https://github.com/next-step/atdd-subway-map/pull/898#discussion_r1252941242

http method에 따라 분리 했습니다~

2023-07-15 19:49 UTC, cohys7 commented on src/test/java/subway/LineAcceptanceTest.java
> +        지하철역을_생성한다("또다른지하철역");
https://github.com/next-step/atdd-subway-map/pull/898#discussion_r1252947711

반복 수행 되는 테스트 준비 과정 줄이기

2023-07-15 19:49 UTC, cohys7 commented on README.md
> +
예외 처리가 발생하는 상황마다 인수 테스트를 따로 작성했는데,
하나로 통합하는 것이 좋은지, 지금 처럼 나누어 작성하는 것이 좋은지 궁금합니다!

2023-07-15 19:49 UTC, cohys7 commented on src/main/java/subway/model/Section.java
> +    private Line line;
Section에서 Line의 연관관계를 매핑하도록 되어 있는데,
다른 방법이 있을까요?

Line Section에 대한 관계를 가지도록 하는 구조가 더 나을지 고민 됩니다.

2023-07-16 09:30 UTC, hiblue02 commented on README.md
> +Then 해당 노선의 하행 종점역과 거리가 업데이트 된다.
인수테스트는 큰 흐름을 작성하는 것이기 때문에 given과 when이 같다면, 한 테스트에서 검증해도 된다고 생각해요. :smile:

2023-07-16 09:32 UTC, hiblue02 commented on README.md
> +
given과 when이 다르기 때문에 분리될 수 밖에 없다고 생각해요. 
다만, 구간 등록에 관한 예외 테스트라는 걸 명시해주기 위해서, @Nested로 묶어줄 수도 있겠네요. :)

2023-07-16 10:34 UTC, hiblue02 requested changes
채현님! 리뷰 내용도 꼼꼼히 반영해주시고 💯 3단계 미션도 잘 구현해주셨네요! 👍 
코멘트 남겼는데, 확인해주시고 다시 리뷰 요청주세요. 😄

2023-07-16 10:34 UTC, hiblue02 commented on src/main/java/subway/model/Line.java
>      }
이렇게 List 객체를 바로 반환하면, 밖에서 수정될 수 있는 위험이 있어요. 
unmodifiable로 반환하는 걸 추천드려요.

2023-07-16 10:34 UTC, hiblue02 commented on src/main/java/subway/model/Line.java
> +    }
요 기능들은 Line이 아닌 List<'Station'>에 대한 걸로 보이는데요. 일급컬렉션을 사용해 분리해보면 어떨까요?

2023-07-16 10:34 UTC, hiblue02 commented on src/main/java/subway/service/LineService.java
> +                .build();
Builder를 직접 구현해 주셨군요! :+1:
앞에 new가 붙고 있네요. :sweat_smile:

2023-07-16 10:34 UTC, hiblue02 commented on src/main/java/subway/service/SectionService.java
> +        newSection.validate(line);
validate 후에 section을 생성하는 게 자연스러울 것 같아요.
validate 메소드 안에서도 결국 line의 메소드를 이용해 검증하고 있는데요. 검증 부분을 어느 도메인에서 담당하면 좋을지 고민해주시면 좋을 것 같아요. :smile:

2023-07-16 10:34 UTC, hiblue02 commented on src/test/java/subway/SectionAcceptanceTest.java
> +        assertThat(line.jsonPath().getObject("distance", Long.class)).isEqualTo(20);
assertThat이 여러 개면 assertAll로 묶어주는 것도 좋아요.

2023-07-16 10:34 UTC, hiblue02 commented on src/test/java/subway/SectionAcceptanceTest.java
> +class SectionAcceptanceTest {
인수테스트를 꼼꼼하게 작성해주셨네요!

2023-07-16 10:34 UTC, hiblue02 commented on src/main/java/subway/service/SectionService.java
> +        sectionRepository.delete(lastSection);
1. Line에서 Station을 지워주고 나면 save를 해주지 않아도, DB에 저장됩니다. (영속성)
2. line에서 section을 지우고, section도 delete해주는 2ㅗ단계로 가기보단 line에서 section만 지우고 cascade 옵션을 이용해 JPA에서 자동으로 지워주는 방법을 사용해요.
  ``` cascade = CascadeType.PERSIST, orphanRemoval = true ```

2023-07-25 21:48 UTC, cohys7 commented on src/main/java/subway/service/SectionService.java
> +        sectionRepository.delete(lastSection);
JPA를 잘 몰랐는데, 좋은 방식이 있었네요!
반영해서 수정 완료했습니다!

2023-07-25 21:48 UTC, cohys7 commented on src/main/java/subway/service/SectionService.java
> +        newSection.validate(line);
line을 이용해서 생성하고 있어서, line을 통해 생성하도록 바꿔 보았는데 괜찮은가요?

2023-07-25 21:48 UTC, cohys7 commented on src/main/java/subway/service/LineService.java
> +                .build();
앗... new 안붙도록 수정했습니다.. ㅎㅎ

2023-07-25 21:48 UTC, cohys7 commented on src/main/java/subway/model/Line.java
> +    }
@Embedded, @Embeddable 애노테이션을 이용하니 일급컬렉션으로 분리해서 사용가능하네요.
말씀하신대로 분리하니 로직이 더 간결해진 것 같아요!

2023-07-25 21:48 UTC, cohys7 commented on src/main/java/subway/model/Line.java
>      }
외부에서 임의로 수정하지 못하도록 unmodifiable로 반환하도록 수정 했습니다~

2023-07-25 21:48 UTC, cohys7 commented on src/main/java/subway/model/Line.java
> +    private List<Station> stations = new ArrayList<>();
Line에서 Station을 가지고 있어야 stations를 출력할 수 있을 것 같아서 위와 같이진행했는데,
Line -> Section -> Station 구조가 더 좋은 것 같네요!

수정 완료했습니다~

2023-07-25 21:49 UTC, cohys7 commented on src/main/java/subway/model/Line.java
>  import javax.persistence.*;
동일한 패키지에서 4개 이상 참조하게되면 자동으로 wildcard로 업데이트 해주네요.. ㅎㅎ
수정 했습니다!

2023-07-25 21:49 UTC, cohys7 commented on src/main/java/subway/controller/RestControllerAdvice.java
> +    }
깜빡하고 반영하지 못했네요~
수정 했습니다~

2023-07-25 21:49 UTC, cohys7 commented on src/main/java/subway/dto/LineResponse.java
>      private List<Station> stations;
별도의 DTO 사용하도록 변경했습니다!

2023-07-26 12:28 UTC, hiblue02 approved these changes
채현님! 리뷰를 꼼꼼하게 반영해주셨네요. 💯 여기서 머지하겠습니다. 
인수테스트와 E2E 테스트 미션 수행하느라 수고하셨어요.
다음 단계 미션도 화이팅입니다! 🔥

2023-07-26 12:28 UTC, hiblue02 commented on src/main/java/subway/model/Line.java
> +    private Sections sections = new Sections();
@Embedded 사용 :+1:

2023-07-26 12:28 UTC, hiblue02 commented on src/main/java/subway/model/Sections.java
> +    }
리뷰 반영 :+1:

2023-07-26 12:28 UTC, hiblue02 commented on src/main/java/subway/model/Line.java
> +        }
리뷰 반영 :100:

2023-07-26 12:28 UTC, hiblue02 commented on src/main/java/subway/model/Sections.java
> +    private List<Section> sections;
일급컬랙션 사용 :+1:
Persist, orphanRemoval = true 사용 > 리뷰반영 :100:

2023-07-26 12:28 UTC, merged