[3단계] 지하철 구간 관리
next-step/atdd-subway-map pull request #959
Opened 2023-07-16 10:16 UTC by YooInKeun

안녕하세요 리뷰어님~
3단계 지하철 구간 관리부터 노선과의 관계가 있다보니 고려해야할 요소가 더 많아진 거 같습니다~ 😵‍💫 

미션을 하면서 궁금했던 점은 아래와 같이 구간 등록시 upStationId 를 받는 이유에 대해 같이 얘기해볼 수 있을까요?
![image](https://github.com/next-step/atdd-subway-map/assets/41741539/82390444-29ec-4109-9182-246de92bea14)

API 에서는 노선에 대한 id 값을 알고 있기 때문에 구간의 upStationId(노선의 하행 종점역) 값을 받지 않아도 처리 자체는 가능할 거 같은데요~ 제가 고민해봤을 때 upStationId 를 따로 받는 이유는 후에 하행 종점역 뿐만 아니라, 다른 역에 대해서도 구간을 추가 가능한 요구사항에 대해 API 스펙을 바꾸지 않고 유연하게 진행하기 위함으로 생각은 드는데요~ 단점으로는 요청값으로 오는 upStationId 가 실제로 해당 노선의 하행 종점역인지 체크해줘야하는 번거로움이 있을 거 같습니다. 혹시 다른 이유가 더 있는지 궁금합니다.

이번 미션도 잘 부탁드립니다.
감사합니다 : )

2023-07-16 12:34 UTC, junwoochoi requested changes
안녕하세요! 마지막 미션 진행해주셨네요!
개인적으로는 Sections를 잘 생성해주셔서 해당 객체에 조금 더 책임이 부여되면 좋겠다는 생각이 들어서 몇가지 코멘트 남겼습니다. 
추가적으로 테스트케이스도 예외케이스 모두 잘 검증해주셨는데, 조금 더 중복을 줄일 수 있는 방법이 있을지 고민해보셔도 좋을 것 같아요!
피드백 확인해주시고, 궁금한 점이나 이해가 안가는 피드백이 있으면 편하게 연락해주세요!

---
API상에 요청 필드로 upStationId를 받는 이유는 말씀하신 것처럼 항상 하행종점역에만 이어 붙이는 경우 필요가 없는 것이 맞지만 다음주차 미션 요구사항으로 하행종점역이 아닌 역에도 구간이 추가되는 요구사항이 주어지다보니 추가 요구사항에 대한 확장성을 열어두었다고 이해하시면 될 것 같습니다! 😄

2023-07-16 12:34 UTC, junwoochoi commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +        Long newDownStationId = 지하철역_생성_요청_및_아이디_추출(SINBUNDANG_NEW_DOWN_STATION_NAME);
반복되는 테스트 픽스처 셋팅은 @BeforeEach를 활용해보세요 :)
해당 값은 필드변수에 저장해놓으면 각 케이스에 접근해서 사용할 수 있습니다!

2023-07-16 12:34 UTC, junwoochoi commented on src/main/java/subway/section/SectionService.java
> +        }
이 부분의 반복을 제거해볼 수 있을까요?

2023-07-16 12:34 UTC, junwoochoi commented on src/main/java/subway/section/SectionService.java
> +        Section section = sectionRepository.save(new Section(line, upStation, downStation, request.getDistance()));
sectionRepository가 정말 필요할까요? 
Line이 없이는 section이 존재할 수 없고, Line이 제거되는 경우 모든 Section은 제거되어야합니다. 
@ManyToOne의 orphanRemoval과 cascade옵션에 대해 확인해보면 좋을 것 같아요~

2023-07-16 12:34 UTC, junwoochoi commented on src/main/java/subway/section/SectionService.java
> +        }
구간의 하행종점역과 관련된 validation을 service 레이어말고 도메인 레이어로 이동해볼 수 있을까요?

2023-07-16 12:34 UTC, junwoochoi commented on src/main/java/subway/line/Line.java
> +    private Sections sections;
Sections 일급객체를 잘 만드셨는데 활용을 안하고 계셔서 아쉬운 것 같아요 😢

2023-07-16 12:34 UTC, junwoochoi commented on src/main/java/subway/line/Line.java
> +    }
구간 추가, 삭제에 대한 책임을 `노선`에서 `구간`일급객체로 옮겨볼 수 있을까요?

2023-07-16 12:34 UTC, junwoochoi commented on src/main/java/subway/section/SectionController.java
> +    }
요구사항에는 없는 API입니다! 현재 구간 자체는 항상 노선의 하위에 종속된 도메인으로 외부에 따로 노출은 되지 않고 있어요~

2023-07-16 12:34 UTC, junwoochoi commented on src/main/java/subway/util/ObjectMapperHolder.java
> +}
설정이 둘이 특별히 다르지 않다면  spring bean등록 되어있는 ObjectMapper를 활용해도 될 것 같아요~

2023-07-16 12:34 UTC, junwoochoi commented on src/test/java/subway/line/LineAcceptanceTest.java
> +        LineResponse response = ObjectMapperHolder.instance.readValue(showResponse.response().body().asString(), LineResponse.class);
인수테스트는 블랙박스 테스트이다보니 직접적으로 response객체에 매핑하기보다는 jsonPath를 활용해 필요한 필드만 활용해서 뽑아보는 것도 좋답니다 :)
물론 지금도 큰 문제는 없습니다!

2023-07-16 12:34 UTC, junwoochoi commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +        assertThat(changedLineResponse).isEqualTo(new LineResponse(changedLineResponse.getId(), SINBUNDANG_LINE_NAME, SINBUNDANG_LINE_COLOR, stationsOfResponse, sumOfDistance));
거리 검증 👍

2023-07-16 12:34 UTC, junwoochoi commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +        assertThat(showSectionResponse.statusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR.value());
위 코멘트처럼 요 API는 존재하지 않는 요구사항이기 때문에 검증에 사용하지 않아도 될 것 같아요~

2023-07-19 13:03 UTC, YooInKeun commented
@junwoochoi 
리뷰어님~ 리뷰 감사드립니다~
덕분에 잘 챙기지 못한 부분들도 배웠고 꼼꼼한 리뷰 덕분에 많은 인사이트를 얻었습니다 👍 👍 

리뷰 주신 내용에 대해 별다른 이견이 없어 코멘트마다 답글을 달지 않았는데요~
line 과 section 의 관계, 클래스의 역할 분리에 초점을 맞춰서 반영해봤는데 확인 부탁드립니다

좋은 저녁 보내세요 🌙

2023-07-19 13:45 UTC, junwoochoi approved these changes
안녕하세요!! 
피드백을 하나하나 잘 적용해주신게 느껴져서 감사한 마음이 드네요! 😃 
피드백 적용해주신 부분 모두 확인하여 머지하겠습니다~!
3단계 미션까지 진행하느라 고생많으셨습니다! 다음주차 미션도 화이팅하세요! 💪

2023-07-19 13:45 UTC, junwoochoi commented on src/test/java/subway/section/SectionAcceptanceTest.java
> +    void setUpLineAndStation() throws JsonProcessingException {
👍 👍 👍

2023-07-19 13:45 UTC, merged