🚀 3단계 - 지하철 구간 관리
next-step/atdd-subway-map pull request #962
Opened 2023-07-17 15:09 UTC by hellonayeon

## 기능 목록
* 구간 등록 기능
* 구간 제거 기능

## 미션 수행 시 중점적으로 생각했던 부분
* 도메인(Line-Section) 간 의존관계 (간접참조)
* 예외 처리

## 느낀점
* `인수조건도출 - 인수테스트작성 - 프로덕션코드구현 - 테스트실행`
  * 인수조건을 직접 도출하고, 테스트코드 작성 후 프로덕션 코드 구현하는 과정이 낯설었지만 프로덕션 구현 후 인수테스트를 통해 바로 검증할 수 있는 점이 인상깊다.
  * 하지만 인수조건이나 테스트가 정확하게 작성되지 않았다면 검증이 무의미해질 수도 있겠다는 생각이 들었다.
* Line - Section 간의 참조관계를 정의하기가 어려웠다.
  * 서로 ID만 가지고 있도록 하고, 비즈니스 로직 작성 시 추가로 연관된 객체를 조회했는데 이렇게하면 JPA의 연관관계 매핑을 사용하는 이점이 퇴색되지 않나? 라는 생각이 들었다.
  * 💡 피드백 바탕으로 도메인 구현을 다시 해볼 예정

2023-07-18 09:33 UTC, seovalue requested changes
안녕하세요 나연님!
요구사항에 맞게 미션 잘 수행해주셨군요ㅎㅎ 
몇가지 리뷰 남겼는데 확인 후 다시 리뷰 요청 주세요~

2023-07-18 09:33 UTC, seovalue commented on src/main/java/subway/exception/SubwayException.java
> +public class SubwayException extends RuntimeException {
Exception을 커스터마이징해주셨군요 👍

2023-07-18 09:33 UTC, seovalue commented on src/test/java/subway/SectionAcceptanceTest.java
> +    void deleteFirstSection() {
요구사항이 복잡해짐에 따라 인수테스트가 길어지고, 점점 가독성도 떨어지는 것 같아요! (이건 제가 구현해도 마찬가지일거에요) 이런 경우 나연님은 실제 현업에서도 인수테스트를 도입하실 것 같으신가요? 

일일이 Fixture로 구분하고 Step을 나눠 리팩터링한다고 해도, 매 api가 추가될때마다 관리해야하는 대상이 될텐데 어떻게 생각하시는지 궁금해요!

2023-07-18 09:33 UTC, seovalue commented on src/test/java/subway/SectionAcceptanceTest.java
> +     */
전반적으로 테스트 시나리오를 꼼꼼히 짜주셨군요 👍

2023-07-18 09:33 UTC, seovalue commented on src/test/java/subway/SectionAcceptanceTest.java
> +        Assertions.assertThat(sectionResponse.getLineId()).isEqualTo(this.lineResponse.getId());
모든 필드가 아닌 id만 검증해주시는 이유가 궁금해요!

2023-07-18 09:33 UTC, seovalue commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @DisplayName("새로운 구간을 등록한다.")
구간 등록 후 노선 조회도 검증이 되어야할 것 같아요!

2023-07-19 14:46 UTC, hellonayeon commented on src/main/java/subway/service/LineService.java
> +    public SectionResponse createSection(Long id, SectionRequest request) {
피드백 주신대로 Sections 라는 일급컬렉션을 생성해서 LineService 책임을 줄일 수 있었어요 ㅎㅎ 고맙습니다!

> Section 에 대한 Controller/Service 계층도 분리해야하나 고민했으나, 
어쨌든 노선에 대한 구간 리스트가 Line과 연관관계가 있고, 노선의 총 거리도 구간들과 연관이 있어 분리하지 않았습니다.

2023-07-19 14:54 UTC, hellonayeon commented on src/test/java/subway/SectionAcceptanceTest.java
> +     */
3단계 미션 수행 전에 인수조건 먼저 도출해서 문서화하고 테스트코드 작성에 들어갔어요!

처음에는 인수조건 도출하기 막막했는데, 인수조건 도출을 위해서 필요한 데이터 / 시나리오 / 검증값을 생각하다 보니 오히려 구현해야하는 부분이 명확해지더라구요 (하지만 아직 익숙하진 않네요..)

🔗 [README.md](https://github.com/next-step/atdd-subway-map/pull/962/files#diff-4435afb8501f1d476fd58c513cd5ee37d9ce192cc388696c5ba076fcd63a9ed3)

2023-07-19 15:06 UTC, hellonayeon commented on src/test/java/subway/SectionAcceptanceTest.java
> +    @DisplayName("새로운 구간을 등록한다.")
구간 등록 후에 Section에 대한 정보가 아니라, 노선 자체의 정보를 리턴할 수 있도록 수정했어요~ 
노선 안에 구간이 있는 것이니, 새로 등록된 지하철역 정보와 노선의 총 거리를 검증하면 될 것 같아요!

2023-07-20 09:49 UTC, hellonayeon commented on src/test/java/subway/SectionAcceptanceTest.java
> +    void deleteFirstSection() {
질문에 동의해요.. 
미션 주차가 진행될수록 테스트가 길어지고 가독성이 저하되는 것을 느꼈는데 실제 현업에서 적용해보니 가독성이 더 떨어지더라구요. 
(도메인이나 요구사항이 미션보다는 복잡해지니까?)
하지만 이러한 단점보다 도입함으로써 취할 수 있는 장점이 더 많은 것 같아, 저라면 여건이 된다면 도입할 것 같습니다!


최근에 현업에서 새로운 요구사항이 주어졌을때, 강의 들은 내용 바탕으로 인수조건 도출하고 테스트코드 작성 후 요구사항 개발하고 테스트로 검증하는 사이클을 실행해보았는데요.


말씀처럼 Fixture 로 구분하고 중복 제거하려고 리팩토링하더라도, 
검증해야하는 내용이 추가되거나, 프로덕션 코드가 변경되면(전달해야하는 필수 파라미터가 추가되는 등) 기존 테스트를 관리해줘야하더라구요.

그럼에도 불구하고, 테스트를 작성하며 수행했던 아래의 과정들이 개발에 도움이 되었기에 인수테스트에 대해 긍정적인 견해를 가지게 됐어요!
> 변경에 의해 새롭게 검증되어야 하는 값은 무엇일지? 에 대한 고민을 통해 도출하고자 하는 값을 명확하게 인지할 수 있었고...
테스트에 필요한 객체들을 생성하며 미처 발견하지 못한 예외 케이스를 발견하기도 하고, 기존 소스들을 한줄한줄 뜯어보게 되기도 하고...


새내기 개발자의 관점으로 인수 테스트를 적용해봤을때 여러모로 장점이 많았습니다.!
지속적으로 테스트케이스를 만들다 보면 질문에 대해 더 깊이있는 고민을 해볼 수 있을 것 같아요

2023-07-20 09:57 UTC, hellonayeon commented on src/test/java/subway/SectionAcceptanceTest.java
> +    void deleteFirstSection() {
저는 인수테스트를 작성하면서 두 가지 불편함이 있었는데요.
(1) 요구사항 검증을 위해 테스트 케이스에서 사용하는 데이터 생성
(2) 말씀주신 테스트가 길어지면서 가독성 저하

문제에 대한 해결 방안이 무엇일까.. 고민해보았는데요.

> (1) 에 대해서는 크게는 테스트 클래스 단위로, 작게는 테스트 케이스 단위로 
Fixture(@BeforeEach, @AfterEach ...) 말고도 테스트에 필요한 데이터를 관리하는 파일(클래스)를 분리해서 따로 관리해주는게 어떨까 싶어요.

> (2) 에 대해서는 테스트 케이스 라인마다 어떤 행위를 하고자 하는 것인지, 로직의 step 을 명시적으로 표현해주는 방법이 있을 것 같아요. (지금은 메서드 체이닝에 의해 한 로직당 2-3라인씩 차지하고 있어요) 강의에서 알려주신 한글명으로 메서드를 짓고 메서드 내부로 세부 동작을 넣는 방법을 통해 가독성을 높일 수 있을 것 같아요.

2023-07-20 10:28 UTC, seovalue commented on src/test/java/subway/SectionAcceptanceTest.java
> +    void deleteFirstSection() {
ㅎㅎ 넘 고민 많이 해주셨네요. 사실 저는 인수테스트보다는 서비스 테스트를 주로 짜곤 하는데요. 인수테스트가 잘 짜두면 정말 명세서 역할을 할 수 있는 것 같아요. 다만 너무 복잡하고 정말 처음부터 끝까지를 다 다루다보니 속도가 느려지기도 하구요. 여러가지 단점이 있지만 장점을 위해 잘 짜둔다면 결과적으로는 좋지 않을까 싶어요~

2023-07-20 10:32 UTC, seovalue approved these changes
안녕하세요, 나연님!
제가 드린 질문에 대해서 깊게 고민해보시고 답변해주시는 점이 인상깊어요ㅎㅎ
리팩터링 잘 수행해주셔서 훨씬 깔끔해진 것 같아요!
이번 단계는 여기서 끝내도 될 것 같아요. 완주까지 화이팅이에요👍

2023-07-20 10:32 UTC, seovalue commented on src/main/java/subway/domain/Line.java
> +    private Sections sections = new Sections();
👍

2023-07-20 10:32 UTC, seovalue commented on src/main/java/subway/domain/Sections.java
> +    @OneToMany(mappedBy = "line", cascade = { CascadeType.PERSIST, CascadeType.MERGE }, orphanRemoval = true)
오홍! cascade를 두가지 명시해주신 이유가 궁금해요!

2023-07-20 10:32 UTC, seovalue commented on src/test/java/subway/README.md
> +        And: 새롭게 추가된 마지막 지하철역(하행종점) 아이디를 비교한다.
👍

2023-07-20 10:32 UTC, seovalue commented on src/main/java/subway/service/LineService.java
> +    public LineResponse saveLine(LineRequest request) {
LineService가 전반적으로 깔끔해졌네요 👍

2023-07-20 10:32 UTC, merged

2023-07-20 13:17 UTC, hellonayeon commented on src/main/java/subway/domain/Sections.java
> +    @OneToMany(mappedBy = "line", cascade = { CascadeType.PERSIST, CascadeType.MERGE }, orphanRemoval = true)
연관관계가 어떻게 관리되는지 디버깅 해보면서 두 개다 설정해봤던건데 그대로 올려버렸어요.. 
CasecadeType.PERSIST 만 설정하고자 합니다 ㅎㅎ 확인해주셔서 감사해요!!